### ISSUE TITLE
flood : cant connect to rtorrent

### ISSUE THREAD

**Issue by rvpn** [amefs/quickbox-lite#10]
rutorrent is working fine but flood didnt.

![flood](https://user-images.githubusercontent.com/28747439/71300552-d3b14000-23d0-11ea-89a2-57c45b4cea92.png)

can you point me how to troubleshoot this issue?

**Comment by rvpn** [comment]
![image](https://user-images.githubusercontent.com/28747439/71301535-05c79f80-23db-11ea-86a0-12efbea03b8f.png)
 am i doing the right thing here?

**Comment by amefs** [comment]
Please use Unix sockets here. https://github.com/amefs/quickbox-lite/wiki/FAQ#how-to-connect-flood-to-rtorrent

**Comment by rvpn** [comment]
> Please use Unix sockets here. https://github.com/amefs/quickbox-lite/wiki/FAQ#how-to-connect-flood-to-rtorrent

tqsm!! it works now
