### ISSUE TITLE
请问flexget密码是什么呀？

### ISSUE THREAD

**Issue by Hostage-02** [amefs/quickbox-lite#100]
面板安装完之后怎么都找不到密码

**Comment by amefs** [comment]
用户名密码就是你安装时设置的。

**Comment by Hostage-02** [comment]
> 用户名密码就是你安装时设置的。

是面板安装时候设置的面板密码吗？那用户名是什么呢，安装面板的用户名跟flexget加上面板密码都不行....

**Comment by amefs** [comment]
通常来说应该是面板上的用户名和密码。请说明一下你的系统版本

**Comment by Hostage-02** [comment]
> 通常来说应该是面板上的用户名和密码。请说明一下你的系统版本
[系统是debian9,这就很奇怪了，明明quickbox面板能用安装时候的用户名密码登陆进去，但是flexget就不行了。大佬，我发两个日志你看看哪里有问题]](https://raw.githubusercontent.com/Hostage-02/sub-web/master/flexget.log)、(https://raw.githubusercontent.com/Hostage-02/sub-web/master/quickbox.2626.log)

**Comment by amefs** [comment]
Debian9的话有人报告过类似bug, 原因应该是openssl版本造成。这个会造成用户名密码没有被记录到系统中。这个可以通过重新安装openssl 1.1.x版本，并运行 `box set password` 重设密码解决。比较建议用更新一些的系统，我将在下一个大版本放弃老系统支持。

**Comment by Hostage-02** [comment]
> Debian9的话有人报告过类似bug, 原因应该是openssl版本造成。这个会造成用户名密码没有被记录到系统中。这个可以通过重新安装openssl 1.1.x版本，并运行 `box set passwd` 重设密码解决。比较建议用更新一些的系统，我将在下一个大版本放弃老系统支持。



> Debian9的话有人报告过类似bug, 原因应该是openssl版本造成。这个会造成用户名密码没有被记录到系统中。这个可以通过重新安装openssl 1.1.x版本，并运行 `box set passwd` 重设密码解决。比较建议用更新一些的系统，我将在下一个大版本放弃老系统支持。

哈哈，习惯了装debian9。谢谢大佬，密码重写进去了，flexget能进了
