### ISSUE TITLE
装好以后deluge和Transmission提示密码错误

### ISSUE THREAD

**Issue by burtchina** [amefs/quickbox-lite#102]
你好：

装好以后deluge和Transmission提示密码错误，rTorrent和qBittorrent正常，重装了几次都有这个问题

可以重现该 Bug 的操作 (或命令)：bash <(wget -qO- https://git.io/qbox-lite -o /dev/null) COMMAND

**截图** (可选)
deluge:
![deluge](https://user-images.githubusercontent.com/27072523/127835012-631e0713-b7db-49d1-a520-80c06631efba.jpg)
Transmission:
![tr](https://user-images.githubusercontent.com/27072523/127835138-2046ab00-af1c-4da6-844b-1436121e502e.jpg)

---

**服务器系统 (请填写下列信息):**

 - 操作系统: [debian 9]
 - 独服

**Comment by amefs** [comment]
#100 推测问题与这个相同，重新安装 openssl 1.1.0 以后重新设置密码应该可以解决问题。再次建议使用新系统。这些系统将不被继续支持，且 Debian 官方也不再直接做支持。

**Comment by burtchina** [comment]
的确是同样的问题，经过重设密码解决

**Comment by burtchina** [comment]
不过还是建议保留debuan 9 之类的系统，有的供应商面板不提供新系统，比如op

**Comment by amefs** [comment]
计划上是留一个独立分支，不会继续新增功能。
