### ISSUE TITLE
请问如何才能把星大脚本中的一些方便的脚本迁移过来使用

### ISSUE THREAD

**Issue by daomengRen** [amefs/quickbox-lite#104]
例如zuozhong，jietu之类的小脚本，觉得很方便

**Comment by amefs** [comment]
这个就需要看一下源码，有一些脚本本身不需要依赖的话（或者说我已经装过），那就可以直接丢到 `/usr/local/bin` 下面去用。

**Comment by daomengRen** [comment]
好的，我先试试

**Comment by daomengRen** [comment]
另外deluge被汉化了，如何才能恢复英文

**Comment by amefs** [comment]
这个是根据你系统语言自动切换的。你需要将服务器系统语言重新设置为英语。`sudo dpkg-reconfigure locale`

**Comment by daomengRen** [comment]
/usr/sbin/dpkg-reconfigure: locale 未安装，没有这个，另外还有个问题，每次机器ssh进去都是个面板信息，需要输入prompt_OFF才能恢复正常，怎么才能让ssh登录进去直接像原来的一样

**Comment by amefs** [comment]
指令换成 `dpkg-reconfigure locales`，并需要选择 `en_US.UTF-8`。
如果需要默认关闭辅助信息，那么运行
```bash
cat >> /root/.bashrc <<EOF

prompt_OFF
EOF
```

**Comment by daomengRen** [comment]
好了，非常感谢大佬
