### ISSUE TITLE
deluge登录后提示密码错误

### ISSUE THREAD

**Issue by archer-wong** [amefs/quickbox-lite#105]
问题描述：安装后，box可以正登录，但是deluge输入密码后，还有继续弹出一个密码框，该密码框输入总是提示密码错误(You entered an incorrect password
)，如下图，使用的独服，多次重装系统都会出现，用过ubuntu1.8 ubuntu2.0 debin10，更新过openssl到1.1.1，修改密码，依然没有效果，希望的到帮助，多谢

<img width="1566" alt="Snipaste_2021-08-08_21-31-30" src="https://user-images.githubusercontent.com/18587233/128633833-fc837ae6-4ee2-4535-81f3-e9e67223e2fa.png">

**Comment by amefs** [comment]
能不能尝试一下其他软件，比如 Transmission, FlexGet 之类

**Comment by archer-wong** [comment]
@amefs 是的，感谢编写了这么好的工具，目前是可以用transmission跑起来

**Comment by amefs** [comment]
请说明一下你目前使用的是 `master` 还是 `developer` 分支，我将抽空做一些测试。

**Comment by archer-wong** [comment]
@amefs 系统是hz家的   2T*2的硬盘  32g内存

操作系统是用脚本一键处理的：

`echo x | installimage -p /boot:ext3:1G,/:ext4:all -l 0 -r yes -i images/Ubuntu-2004-focal-64-minimal.tar.gz  -a -n Hz && reboot`

同时软件使用的命令：
`bash <(wget -qO- https://git.io/qbox-lite -o /dev/null) --dev -u xxx -p yyy --with-ffmpeg -P 1234 --with-bbr --with-deluge --with-mktorrent --with-linuxrar --with-cf --with-rtorrent  --with-transmission --hostname vmserver --reboot`

**Comment by amefs** [comment]
已修复，见 bdc2973fe9bb695526cd93eb6a47fa2132542b58

**Comment by archer-wong** [comment]
@amefs 多谢多谢
