### ISSUE TITLE
A record not found

### ISSUE THREAD

**Issue by annaparker** [amefs/quickbox-lite#106]
Hello,

Fresh Debian 10. Installing quickbox-lite, chosen Let's Encrypt cert, typing domain and getting error "A record not found" and message "The A record for domain xxx.xx not detected. Please recheck and try again." Xxx.xx is my domain, of course A record is active, it is discovered (even the ping xxx.xx) from machine where quickbox-lite will be. Any help?

Thank you!

**Comment by amefs** [comment]
check your A record with `curl -sH 'accept: application/dns-json' "https://cloudflare-dns.com/dns-query?name=$domain&type=A"`, if still have problem, change https://github.com/amefs/quickbox-lite/blob/master/setup.sh#L293-L301 to
```shell
whiptail --title "$INFO_TITLE_DOMAINCHK" --msgbox "${INFO_TEXT_DOMAINCHK_1}$domain${INFO_TEXT_DOMAINCHK_2}" --ok-button "$BUTTON_OK" 8 72
hostname=$domain
```

**Comment by annaparker** [comment]
That helped, thanks @amefs for your awesome work and your fork. Respect for you.
