### ISSUE TITLE
file browser 安装后 不能使用

### ISSUE THREAD

**Issue by burtchina** [amefs/quickbox-lite#108]
**描述 Bug**
file browser  安装后不能使用，总是显示三个点，重启也不行
**截图** 
![微信截图_20210819091814](https://user-images.githubusercontent.com/27072523/129996292-157ca7f1-711b-4fee-b85f-2935c28db11d.png)

服务器系统 (请填写下列信息):

操作系统: [debian 9]
独服

**Comment by amefs** [comment]
我用本地的测试环境无法重复你的问题，建议尝试一下使用代理等加速手段。该页面可能比较难加载。

**Comment by burtchina** [comment]
这是日志，我看下有错误提示，你可以分析下
[quickbox.2890.log](https://github.com/amefs/quickbox-lite/files/7018824/quickbox.2890.log)

**Comment by amefs** [comment]
可能还是 Debian 9 的 OpenSSL 版本问题，我已经在内部测试版中进行了修复，但因为一些原因暂时没有时间 Release。预计最晚下个月会发布。目前解决方法还是重新安装 OpenSSL，设置密码，重新安装这个软件。

**Comment by burtchina** [comment]
又重装了一遍还是不行，重新安装 OpenSSL，设置密码了，另外试了下先装OpenSSL后装脚本也不行，看来只能期待你下个月的Release了
安装日志：
[quickbox.6863.log](https://github.com/amefs/quickbox-lite/files/7022938/quickbox.6863.log)

**Comment by amefs** [comment]
已经在 dev/legacy 分支实现，但需要等我合并到主分支。
