### ISSUE TITLE
RTMP NGINX Module

### ISSUE THREAD

**Issue by Hipoglos** [amefs/quickbox-lite#11]
Hi amefs,
If I do a clean installation of quickbox-lite, can I install/add rtmp module on the nginx? Just once u have a moment, could you please tell me what I should run to avoid breaking down the whole quickbox-lite? Thanks in advance!

**Comment by amefs** [comment]
Hello, here are some tips for you:
You need to compile the extra module for installed Nginx. For example, my Nginx version is 1.10.3.
- Get dependence
    ```
    sudo apt-get update
    sudo apt-get install dpkg-dev git
    sudo apt-get build-dep nginx-extras
    ```
- Get source
	```
	sudo git clone https://github.com/arut/nginx-rtmp-module.git
	sudo apt-get source nginx
	```
	
	Check if nginx-1.10.3 folder exists. When isn't, execute the command again.
	```
	sudo apt-get source nginx
	```
- Modify configuration file (you can edit the rule with any text editor you like)
	```
	cd nginx-1.10.3
	sudo vi debian/rules
	```
	Add this flag to the extras_configure_flags, just after `--with-stream_ssl_module`
	```
	--add-module=/usr/src/nginx-rtmp-module \
	```
- Build the package
	```
	sudo dpkg-buildpackage -b -uc -us
	```
- Install new package
	```
	sudo apt install ./nginx-common_1.10.3-1+deb9u3_all.deb
	sudo apt install ./nginx-extras_1.10.3-1+deb9u3_amd64.deb
	```
The module needs to be compiled each time after upgrade the Nginx package. So, you can hold your own Nginx package to prevent accidental automatic upgrades
	```
	sudo apt-mark hold nginx
	sudo apt-mark hold nginx-extras
	```
	

Reference: https://github.com/arut/nginx-rtmp-module/wiki/Installing-on-Ubuntu-using-PPAs

**Comment by Hipoglos** [comment]
Thanks amefs :) It helped me a lot. as I'm running Ubuntu 18.04 I needed to change some things, but it worked! Thanks again for your time :)

**Comment by amefs** [comment]
my pleasure
