### ISSUE TITLE
请问有可能安装多个相同或者不同版本的bt客户端吗？

### ISSUE THREAD

**Issue by brsymomo** [amefs/quickbox-lite#112]
抱歉问个小白问题，请问有可能安装多个相同或者不同版本的bt客户端吗？比如安装多个4.2.5版本的qbittorrent客户端这样...网上找不到教程，linux小白，大佬如果有提示我可以去学习一下~

**Comment by amefs** [comment]
你可以通过多个配置文件配合 Systemd 完成。但是多个qBittorrent会需要更多资源。如果说担心PT/BT，那么可以明确告诉你没有影响。而不同的站点你也可以用分类/标签区别。

**Comment by brsymomo** [comment]
谢谢大佬，估计我得从入门开始学习一下...确实是做pt，一个塞了23千种就变卡所以想多个一起用😩
