### ISSUE TITLE
qbittorrent 上传速度极慢是怎么回事啊？

### ISSUE THREAD

**Issue by kaiant924** [amefs/quickbox-lite#115]
speedtest测速上行速度有1G，但是qbittorrent 做种速度只有几Kb/s。应该不是由于种子没人下，我选的是很热门的种子。transmission的上传速度是正常的。请问是是怎么原因呢？
![4BED43F9-AF69-4005-98DB-5590ED48F035](https://user-images.githubusercontent.com/90315803/133418320-bc4ef47b-3cc4-4598-b292-3ef6d62795c4.jpeg)
![41313341-6659-4FC1-9846-B1AE93EB8B4C](https://user-images.githubusercontent.com/90315803/133418345-b6998fb6-aa94-40f1-b9a9-b83079dca0ba.jpeg)

**Comment by amefs** [comment]
你qBittorrent中的种子有41个seeder，如果你连接性不好，则不会有那么多上传速度。

**Comment by kaiant924** [comment]
> 你qBittorrent中的种子有41个seeder，如果你连接性不好，则不会有那么多上传速度。

请问如何提高连接性呢？有47个leecher，按理说上传速度应该很高的。但是已经三个多小时了，一直都是处于几乎没有上传速度的状态。

**Comment by amefs** [comment]
没办法平白无故提高，我的话很简单，用更好的服务器，这是最现实的。其他就是尝试魔改BBR之类的方法倍发包，这样能略微提高一点间接性，效果通常不明显。

**Comment by kaiant924** [comment]
> 没办法平白无故提高，我的话很简单，用更好的服务器，这是最现实的。其他就是尝试魔改BBR之类的方法倍发包，这样能略微提高一点间接性，效果通常不明显。

请问为什么transmission的上传速度是正常的呢？

**Comment by amefs** [comment]
你不是同一个种子

**Comment by kaiant924** [comment]
> 你不是同一个种子

我qb也下了同一个种子测试，transmission是一直有上传速度，而qb一直没有。qb的下载是正常的，差不多跑满带宽。上传为0
![91F21FD2-B72E-4B0C-B31B-5D32796710FC](https://user-images.githubusercontent.com/90315803/133459931-3d976c54-0af3-4493-892f-609f9ab652e8.jpeg)
![6467F02A-FC2D-47B7-9931-4664E7EE7C12](https://user-images.githubusercontent.com/90315803/133459943-f54d4460-073f-4028-b7b1-beb4a3d83883.jpeg)

**Comment by amefs** [comment]
查看一下你tracker的状态。

**Comment by kaiant924** [comment]
> 查看一下你tracker的状态。

![765DA892-96C3-489F-8D6A-6A75461A6C82](https://user-images.githubusercontent.com/90315803/133463285-5e1be844-a23c-4704-890c-4e0fea124e18.jpeg)
是这个吗？

**Comment by amefs** [comment]
看上去 tracker 没有问题，我也判断不出有什么问题。

**Comment by zjh19779** [comment]
我也遇到了一样的问题
![屏幕截图(379)](https://user-images.githubusercontent.com/115462798/208220957-4e622466-1204-49f9-9ead-282a39491e69.png)

**Comment by amefs** [comment]
从你的统计页面来看，5 个 peers 本身已经很少了，而你只能连接到一个；跟你一样的 Seeder 却有 32 个，那没有速度也完全合理。前一位的图中至少 peers 远大于 seeders，只是他完全连不上而已。
