### ISSUE TITLE
请问如何升级qbitorrent至4.3.3版本？

### ISSUE THREAD

**Issue by kaiant924** [amefs/quickbox-lite#116]
如题

**Comment by amefs** [comment]
`box update qbittorrent --qb 4.3.3`

更多信息参见https://cn.wiki.ptbox.dev/qbittorrent/

**Comment by kaiant924** [comment]
> `box update qbittorrent --qb 4.3.3`
> 
> 更多信息参见https://cn.wiki.ptbox.dev/qbittorrent/

你好，可是我输入命令之后是这样的：

[06:54 root@localhost ~] > box update qbittorrent --qb 4.3.3
getopt: unrecognized option '--qb 4.3.3'

QuickBox Lite qBittorrent Updater

Usage: 
updatepackage-qbittorrent [-h] [-l logfile] [-s static] [--qb]

Options:

-l, --log <logfile>       specific log file
--qb <version>            the qbittorrent version you want to install
-s, --static              install qBittorrent with static build
--force                   force downgrade qBittorrent
--with-cf                 use cloudflare instead of github
--with-sf                 use sourceforge instead of github
--with-osdn               use osdn(jp)  instead of github
--with-github             use github

-h, --help                display this help and exit


请问是哪里出了问题呢？

**Comment by amefs** [comment]
你尝试使用 `box update quickbox` 升级一下相关代码以后再运行上述指令升级 qBittorrent

**Comment by kaiant924** [comment]
> 你尝试使用 `box update quickbox` 升级一下相关代码以后再运行上述指令升级 qBittorrent

按照您的做了，升级成功。可是升级之后在dashboard上多次按重启qbittorrent没效果。打开qb网页显示502 bad gateway。我运行了box fix home之后也没成功启动qb，重启vps之后也不行。

**Comment by kaiant924** [comment]
> > 你尝试使用 `box update quickbox` 升级一下相关代码以后再运行上述指令升级 qBittorrent
> 
> 按照您的做了，升级成功。可是升级之后在dashboard上多次按重启qbittorrent没效果。打开qb网页显示502 bad gateway。我运行了box fix home之后也没成功启动qb，重启vps之后也不行。

![E797FD91-3861-4160-9827-08B547A015B8](https://user-images.githubusercontent.com/90315803/133799884-b3a00730-32f3-4f9f-8ef4-83d53167bb20.jpeg)

**Comment by amefs** [comment]
`journalctl -u qbittorrent@改成你的用户名.service`

**Comment by kaiant924** [comment]
> journalctl -u qbittorrent@改成你的用户名.service

结果是这样的：

[07:53 root@localhost ~] > journalctl -u qbittorrent@kaiant.service
-- Logs begin at Fri 2021-09-17 07:20:09 PDT, end at Fri 2021-09-17 07:53:16 PDT. --
9月 17 07:20:09 localhost systemd[1]: Starting qBittorrent Daemon Service...
9月 17 07:20:09 localhost qbittorrent-nox[320]: Could not create required directory '/home/kaiant/.cache/q9月 17 07:20:09 localhost systemd[1]: qbittorrent@kaiant.service: Control process exited, code=killed, sta9月 17 07:20:09 localhost systemd[1]: qbittorrent@kaiant.service: Failed with result 'signal'.
9月 17 07:20:09 localhost systemd[1]: Failed to start qBittorrent Daemon Service.
9月 17 07:20:32 localhost systemd[1]: Starting qBittorrent Daemon Service...
9月 17 07:20:32 localhost qbittorrent-nox[616]: Could not create required directory '/home/kaiant/.cache/q9月 17 07:20:32 localhost systemd[1]: qbittorrent@kaiant.service: Control process exited, code=killed, sta9月 17 07:20:32 localhost systemd[1]: qbittorrent@kaiant.service: Failed with result 'signal'.
9月 17 07:20:32 localhost systemd[1]: Failed to start qBittorrent Daemon Service.
9月 17 07:21:39 localhost systemd[1]: Starting qBittorrent Daemon Service...
9月 17 07:21:39 localhost qbittorrent-nox[1101]: The legacy data directory '/home/kaiant/.local/share/data9月 17 07:21:39 localhost qbittorrent-nox[1101]: The legacy data directory '/home/kaiant/.local/share/data9月 17 07:21:39 localhost systemd[1]: Started qBittorrent Daemon Service.
9月 17 07:21:41 localhost systemd[1]: qbittorrent@kaiant.service: Succeeded.
9月 17 07:21:49 localhost systemd[1]: Starting qBittorrent Daemon Service...
9月 17 07:21:49 localhost qbittorrent-nox[1235]: The legacy data directory '/home/kaiant/.local/share/data9月 17 07:21:49 localhost qbittorrent-nox[1235]: The legacy data directory '/home/kaiant/.local/share/data9月 17 07:21:49 localhost systemd[1]: Started qBittorrent Daemon Service.
9月 17 07:21:50 localhost systemd[1]: qbittorrent@kaiant.service: Succeeded.
9月 17 07:23:07 localhost systemd[1]: Starting qBittorrent Daemon Service...
9月 17 07:23:07 localhost qbittorrent-nox[2368]: The legacy data directory '/home/kaiant/.local/share/data9月 17 07:23:07 localhost qbittorrent-nox[2368]: The legacy data directory '/home/kaiant/.local/share/data9月 17 07:23:07 localhost systemd[1]: Started qBittorrent Daemon Service.
9月 17 07:23:08 localhost systemd[1]: qbittorrent@kaiant.service: Succeeded.
9月 17 07:24:34 localhost systemd[1]: Starting qBittorrent Daemon Service...
9月 17 07:24:34 localhost qbittorrent-nox[2955]: The legacy data directory '/home/kaiant/.local/share/data9月 17 07:24:34 localhost qbittorrent-nox[2955]: The legacy data directory '/home/kaiant/.local/share/data9月 17 07:24:34 localhost systemd[1]: Started qBittorrent Daemon Service.
9月 17 07:24:35 localhost systemd[1]: qbittorrent@kaiant.service: Succeeded.
9月 17 07:46:01 localhost systemd[1]: Starting qBittorrent Daemon Service...
9月 17 07:46:01 localhost qbittorrent-nox[3600]: The legacy data directory '/home/kaiant/.local/share/data9月 17 07:46:01 localhost qbittorrent-nox[3600]: The legacy data directory '/home/kaiant/.local/share/data9月 17 07:46:01 localhost systemd[1]: Started qBittorrent Daemon Service.
9月 17 07:46:02 localhost systemd[1]: qbittorrent@kaiant.service: Succeeded.
9月 17 07:52:39 localhost systemd[1]: Starting qBittorrent Daemon Service...
9月 17 07:52:39 localhost qbittorrent-nox[3887]: The legacy data directory '/home/kaiant/.local/share/data9月 17 07:52:39 localhost qbittorrent-nox[3887]: The legacy data directory '/home/kaiant/.local/share/data

**Comment by amefs** [comment]
在非root账户时运行
```
mkdir -p /home/kaiant/.cache/
mkdir -p /home/kaiant/.local/share/data
```

**Comment by amefs** [comment]
```
chown -R kaiant.kaiant /home/kaiant/.cache/
chown -R kaiant.kaiant /home/kaiant/.local/
```
这说明你的个人文件夹中有很多权限有问题的文件夹

**Comment by kaiant924** [comment]
> ```
> chown -R kaiant.kaiant /home/kaiant/.cache/
> chown -R kaiant.kaiant /home/kaiant/.local/
> ```
> 
> 
>      
>   
> 
> 这说明你的个人文件夹中有很多权限有问题的文件夹

我修改了用户和用户组，尝试启动qb，但还是原来那样。然后我直接把我用户的文件夹权限修改为777。还是无果。附上日志：
![EC84CDFD-864F-444C-A44D-96E8B6C19DA0](https://user-images.githubusercontent.com/90315803/133817722-e93a5e0b-45f9-432f-a668-8dbcf38c61aa.jpeg)

**Comment by amefs** [comment]
你这里并没有提示failed to start。这应该是一个警告，因为低版本升级上来会使用这个老文件夹。

**Comment by kaiant924** [comment]
> 你这里并没有提示failed to start。这应该是一个警告，因为低版本升级上来会使用这个老文件夹。

可是无法访问qb的web ui啊，显示502 Bad Gateway。Dashboard上重启也一直不成功。
![133799884-b3a00730-32f3-4f9f-8ef4-83d53167bb20](https://user-images.githubusercontent.com/90315803/133863191-e078f9c5-7f32-432b-880f-adfb58f3827e.jpeg)

**Comment by amefs** [comment]
尝试重新安装 qBittorrent，安装时使用 `box install qbittorrent --qb 4.3.3` 指定版本。我不清楚你的系统环境，但我无法在自己的虚拟机中复现你的问题。

**Comment by kaiant924** [comment]
> box install qbittorrent --qb 4.3.3

我的系统是Debian 10。我在dashboard上把qb卸载了。然后用命令box install qbittorrent --qb 4.3.3 重新安装qb。之前的问题还是不能解决。vps上安装之后显示qb已经启动。但是dashboard 上显示未启动，而且访问web ui也依然是502 Bad Gateway

**Comment by amefs** [comment]
我使用 Debian 10 重复了你的操作，无法重现。请你尝试如下命令(root权限)，观察输出：
```
systemctl stop qbittorrent@kaiant
sudo -u kaiant qbittorrent-nox
```

**Comment by kaiant924** [comment]
> 我使用 Debian 10 重复了你的操作，无法重现。请你尝试如下命令(root权限)，观察输出：
> 
> ```
> systemctl stop qbittorrent@kaiant
> sudo -u kaiant qbittorrent-nox
> ```

输出如下：
05:16 root@localhost ~] > systemctl stop qbittorrent@kaiant
[05:16 root@localhost ~] > sudo -u kaiant qbittorrent-nox

******** 信息 ********
欲通过 Web UI 控制 qBittorrent，请访问 http://localhost:15154
我加上我的ip访问这个地址，但是显示无法连接

**Comment by amefs** [comment]
这个网址是 localhost，需要通过 ssh tunnel 才能访问。请查看 nginx 中配置的反代端口:
```
cat /etc/nginx/conf.d/kaiant.qbittorrent.conf
```

**Comment by kaiant924** [comment]
> 这个网址是 localhost，需要通过 ssh tunnel 才能访问。请查看 nginx 中配置的反代端口:
> 
> ```
> cat /etc/nginx/conf.d/kaiant.qbittorrent.conf
> ```

[05:40 root@localhost ~] > cat /etc/nginx/conf.d/kaiant.qbittorrent.conf
upstream kaiant.qbittorrent {
  server 127.0.0.1:15154;
}
结果是这样的

**Comment by amefs** [comment]
OK，那么现在你首先运行
```
nginx -s reload
```
然后运行
```
sudo -u kaiant qbittorrent-nox
```
并保留这个session。此时看一下你的面板，应当能显示 qBittorrent 在线，并可以正常访问。

**Comment by kaiant924** [comment]
> OK，那么现在你首先运行
> 
> ```
> nginx -s reload
> ```
> 
> 然后运行
> 
> ```
> sudo -u kaiant qbittorrent-nox
> ```
> 
> 并保留这个session。此时看一下你的面板，应当能显示 qBittorrent 在线，并可以正常访问。

可以了大佬。可以正常访问了。多谢大佬解答！感激不尽！

**Comment by kaiant924** [comment]
发现一个问题，就是先运行nginx -s reload
再运行sudo -u kaiant qbittorrent-nox
当我从ssh客户端退出之后，qb的 web ui又无法访问了，并且dashboard 显示和之前的一样，qb未启动。前面有个红点

**Comment by amefs** [comment]
上面的命令测试说明你的 qBittorrent 是可以运行的，那么尝试 `systemctl restart qbittorrent@kaiant`。如果此方法无效，可能你的 Systemd 收到了不正常的退出指令，请运行 `sudo -u kaiant qbittorrent-nox -d` 。虽然你说的是 Debian 10，但是你的系统与正常的Debian 10 minimal install 有相当多不同的表现。

**Comment by kaiant924** [comment]
> 上面的命令测试说明你的 qBittorrent 是可以运行的，那么尝试 `systemctl restart qbittorrent@kaiant`。如果此方法无效，可能你的 Systemd 收到了不正常的退出指令，请运行 `sudo -u kaiant qbittorrent-nox -d` 。虽然你说的是 Debian 10，但是你的系统与正常的Debian 10 minimal install 有相当多不同的表现。

第一条指令确实无效，第二条生效了。感谢您的解答！
