### ISSUE TITLE
请问rtorrent无法下载是什么原因？

### ISSUE THREAD

**Issue by kaiant924** [amefs/quickbox-lite#117]
我在ruTorrent的网页上上传了种子，但是一直无法下载。以下是日志以及rutorrent的报告
![AA946700-554F-4C14-AFC1-774CBF8A7AE6](https://user-images.githubusercontent.com/90315803/133890139-aa59ca77-7bbe-4184-b4ca-4725894bc3a1.jpeg)
![8CDC540F-B215-4A05-B034-6BED337BE407](https://user-images.githubusercontent.com/90315803/133890145-fb51f4e5-c5be-4592-92a7-4b3e9d026a4b.jpeg)
![25632A7C-E023-4993-ACD0-686C7029DF7B](https://user-images.githubusercontent.com/90315803/133890148-4fc2fc2c-725a-40e6-97e7-e40d7d8a262a.jpeg)

**Comment by amefs** [comment]
最后一张图的报错是说你连不上 tracker，这个意思是你无法获取 peers 列表，那么自然无法下载，最上面 systemd 里面的应该是显示权限错误。这不是我软件的问题，建议你直接 Google 搜索各种错误代码。
