### ISSUE TITLE
 怎么从legacy 分支安装

### ISSUE THREAD

**Issue by burtchina** [amefs/quickbox-lite#118]
你好，

我的服务器只有debian 9，需要通过指定 legacy 分支才能安装，请问怎么通过legacy 分支安装，有具体命令吗？

**Comment by amefs** [comment]
```bash
bash <(wget -qO- https://git.io/qbox-lite -o /dev/null) --legacy COMMAND
```

**Comment by burtchina** [comment]
谢谢，用这个命令在debian 9上成功安装。

通过 https://github.com/DieNacht/debian-ubuntu-upgrade  这个脚本升级以后就ping不通了，改源升级办法试过也不行~

看来只能先用debian 9了，以后再想办法升级debian 10吧
