### ISSUE TITLE
出现502是什么原因

### ISSUE THREAD

**Issue by burtchina** [amefs/quickbox-lite#119]
**描述 Bug**
控制面板不能访问出现502错误是什么原因
ssh可以登录，可以ping通

**重现 Bug**
首次出现不清楚原因

**截图** (可选)
![微信截图_20211004205023](https://user-images.githubusercontent.com/27072523/135855293-453db64f-ee4f-46d6-830a-5f335cd5252f.png)

---

**附加内容**

**桌面系统 (请填写下列信息):**

 - 操作系统: [win 10]
 - 浏览器 [例如 chrome]

**服务器:**

 - 设备: [独服]
 - 操作系统: [debian10]

**Comment by amefs** [comment]
运行 `systemctl status php7.4-fpm` 查看状态。若显示 Stop 则使用 `systemctl restart php7.4-fpm` 重启服务。

**Comment by burtchina** [comment]
那天比较急已经重装了，再发现这个问题试试这个命令~
