### ISSUE TITLE
请问怎么用qbittorrent自带的登录界面

### ISSUE THREAD

**Issue by Pinocchio-x** [amefs/quickbox-lite#120]
小白想问下怎么样才能把qb的nginx的登录取消，用qb自带的登录呢，尝试过把nginx下的qbittorrent..conf里的auth_basic注释掉，结果502 bad getway了，麻烦大佬解惑！

**Comment by amefs** [comment]
你需要修改 qBittorrent 的配置文件，修改为 `WebUI\Address=0.0.0.0`，随后重启 qBittorrent 进程。此时你可以通过 qBittorrent WebUI 的端口访问， WebUI 端口可以通过 `cat /install/<替换为你的用户名>.qbittorrent.port` 获取。注意，此时你的访问都没有 TLS 加密，有安全风险。如果是配置一些自动化程序，那么完全可以直接通过 `https://IP/qbittorrent/` 这样的路径来控制。
