### ISSUE TITLE
file browser依旧无法使用

### ISSUE THREAD

**Issue by w-kun** [amefs/quickbox-lite#123]
#108 
原版和增强版都卡在三个点那。
还有flood也显示502 Bad Gateway，
重装无效，系统是Debian 10

**Comment by amefs** [comment]
三个点无限 Loading 通常是网络问题。Flood 502 需要查看 Flood 进程
```
systemctl status flood@<这里是你的用户名>
```

**Comment by w-kun** [comment]
> systemctl status flood@<这里是你的用户名>



> 三个点无限 Loading 通常是网络问题。Flood 502 需要查看 Flood 进程
> 
> ```
> systemctl status flood@<这里是你的用户名>
> ```

● flood@kyu.service - Flood rTorrent Web UI
   Loaded: loaded (/etc/systemd/system/flood@.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2021-12-02 16:34:23 JST; 2min 23s ago
  Process: 381 ExecStart=/usr/bin/npm start --production /home/kyu/.flood (code=exited, status=1/FAILURE)
 Main PID: 381 (code=exited, status=1/FAILURE)

12月 02 16:34:22 w-kun.tk npm[381]: npm ERR! errno 1
12月 02 16:34:22 w-kun.tk npm[381]: npm ERR! flood@1.0.0 start: `node --use_strict  server/bin/start.js "/home/kyu/.flood"`
12月 02 16:34:22 w-kun.tk npm[381]: npm ERR! Exit status 1
12月 02 16:34:22 w-kun.tk npm[381]: npm ERR!
12月 02 16:34:22 w-kun.tk npm[381]: npm ERR! Failed at the flood@1.0.0 start script.
12月 02 16:34:22 w-kun.tk npm[381]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
12月 02 16:34:22 w-kun.tk npm[381]: npm ERR! A complete log of this run can be found in:
12月 02 16:34:22 w-kun.tk npm[381]: npm ERR!     /home/kyu/.npm/_logs/2021-12-02T07_34_22_720Z-debug.log
12月 02 16:34:23 w-kun.tk systemd[1]: flood@kyu.service: Main process exited, code=exited, status=1/FAILURE
12月 02 16:34:23 w-kun.tk systemd[1]: flood@kyu.service: Failed with result 'exit-code'.


三个点是网络问题的话，有什么能查看状况的指令吗？或者日志

**Comment by amefs** [comment]
你可以查看 log：
```
/home/kyu/.npm/_logs/2021-12-02T07_34_22_720Z-debug.log
```
测试 filebrowser:
```
curl -k -i https://<你的用户名>:<密码>@<服务器域名或者IP>/filebrowser-ee/files/
```
观察返回值

**Comment by w-kun** [comment]
> 

`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'start',
1 verbose cli   '--production',
1 verbose cli   '/home/kyu/.flood'
1 verbose cli ]
2 info using npm@6.14.15
3 info using node@v14.18.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle flood@1.0.0~prestart: flood@1.0.0
6 info lifecycle flood@1.0.0~start: flood@1.0.0
7 verbose lifecycle flood@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle flood@1.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/kyu/.flood/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle flood@1.0.0~start: CWD: /home/kyu/.flood
10 silly lifecycle flood@1.0.0~start: Args: [ '-c', 'node --use_strict  server/bin/start.js "/home/kyu/.flood"' ]
11 silly lifecycle flood@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle flood@1.0.0~start: Failed to exec start script
13 verbose stack Error: flood@1.0.0 start: `node --use_strict  server/bin/start.js "/home/kyu/.flood"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1058:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
14 verbose pkgid flood@1.0.0
15 verbose cwd /home/kyu/.flood
16 verbose Linux 4.19.0-6-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start" "--production" "/home/kyu/.flood"
18 verbose node v14.18.1
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 1
22 error flood@1.0.0 start: `node --use_strict  server/bin/start.js "/home/kyu/.flood"`
22 error Exit status 1
23 error Failed at the flood@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

> 
`HTTP/2 200 
server: nginx
date: Wed, 08 Dec 2021 08:28:09 GMT
content-type: text/html; charset=utf-8
vary: Accept-Encoding
x-ratelimit-limit: 401
x-ratelimit-remaining: 400
x-ratelimit-reset: 1
x-xss-protection: 1; mode=block
x-frame-options: SAMEORIGIN
x-content-type-options: nosniff

<!DOCTYPE html><html lang=en><head><meta charset=utf-8><meta http-equiv=X-UA-Compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1,user-scalable=no"><title>File Browser Enhanced</title><link rel=icon type=image/png sizes=32x32 href="/filebrowser-ee/static/img/icons/favicon-32x32.png"><link rel=icon type=image/png sizes=16x16 href="/filebrowser-ee/static/img/icons/favicon-16x16.png"><link rel=manifest href="/filebrowser-ee/static/manifest.json"><meta name=theme-color content=#2979ff><meta name=apple-mobile-web-app-capable content=yes><meta name=apple-mobile-web-app-status-bar-style content=black><meta name=apple-mobile-web-app-title content=assets><link rel=apple-touch-icon href="/filebrowser-ee/static/img/icons/apple-touch-icon-152x152.png"><meta name=msapplication-TileImage content="/filebrowser-ee/static/img/icons/msapplication-icon-144x144.png"><meta name=msapplication-TileColor content=#2979ff><script>window.FileBrowser = JSON.parse(`{
  "BaseURL": "/filebrowser-ee",
  "CSS": false,
  "CacheRoot": "",
  "Description": "",
  "IndexInterval": "",
  "IndexLocation": "",
  "LoginPage": false,
  "Name": "",
  "NoAuth": true,
  "ReCaptcha": false,
  "Signup": false,
  "Slideshow": {
    "transitionEffect": "",
    "continuous": false,
    "showThumbIndicator": false,
    "showDotIndicator": false,
    "transitionSpeed": 0,
    "preloadRange": 0,
    "autoplaySlide": false,
    "autoplayInterval": 0,
    "autoplayProgressBar": false
  },
  "StaticURL": "filebrowser-ee/static",
  "Thumbnail": {
    "cacheRoot": "",
    "cacheGcProbability": 0,
    "cacheExpireTTL": 0,
    "thumbnailEnabled": false,
    "thumbnailVideo": false,
    "thumbnailWidth": 0,
    "thumbnailVideoWidth": 0,
    "thumbnailVideoColumns": 0,
    "thumbnailVideoNumcaps": 0,
    "thumbnailVideoComment": ""
  },
  "Version": {
    "Version": "2.9.4",
    "CommitSHA": "f014ce8d",
    "BuildDate": "20200523-2316",
    "OS": "linux",
    "Arch": "amd64",
    "GoVersion": "go1.14.3"
  },
  "Video": {
    "autoplay": false,
    "disableHls": false,
    "autoSubExtract": false,
    "disablePreview": false,
    "volume": 0,
    "quality": 0,
    "seekDelta": 0,
    "seekDeltaLong": 0
  },
  "VideoEncoder": "libx264"
}`)</script><style>#loading {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: #fff;
    z-index: 9999;
    transition: .1s ease opacity;
    -webkit-transition: .1s ease opacity;
  }

  #loading.done {
    opacity: 0;
  }

  .spinner {
    width: 70px;
    text-align: center;
    position: fixed;
    top: 50%;
    left: 50%;
    -webkit-transform: translate(-50%, -50%);
            transform: translate(-50%, -50%);
  }

  .spinner > div {
    width: 18px;
    height: 18px;
    background-color: #333;
    border-radius: 100%;
    display: inline-block;
    -webkit-animation: sk-bouncedelay 1.4s infinite ease-in-out both;
    animation: sk-bouncedelay 1.4s infinite ease-in-out both;
  }

  .spinner .bounce1 {
    -webkit-animation-delay: -0.32s;
    animation-delay: -0.32s;
  }

  .spinner .bounce2 {
    -webkit-animation-delay: -0.16s;
    animation-delay: -0.16s;
  }

  @-webkit-keyframes sk-bouncedelay {
    0%, 80%, 100% { -webkit-transform: scale(0) }
    40% { -webkit-transform: scale(1.0) }
  }

  @keyframes sk-bouncedelay {
    0%, 80%, 100% {
      -webkit-transform: scale(0);
      transform: scale(0);
    } 40% {
      -webkit-transform: scale(1.0);
      transform: scale(1.0);
    }
  }</style><link href="/filebrowser-ee/static/css/app.78590095.css" rel=preload as=style><link href="/filebrowser-ee/static/css/chunk-vendors.6a22f2e3.css" rel=preload as=style><link href="/filebrowser-ee/static/js/app.f35de706.js" rel=preload as=script><link href="/filebrowser-ee/static/js/chunk-vendors.de215bb2.js" rel=preload as=script><link href="/filebrowser-ee/static/css/chunk-vendors.6a22f2e3.css" rel=stylesheet><link href="/filebrowser-ee/static/css/app.78590095.css" rel=stylesheet></head><body><div id=app></div><div id=loading><div class=spinner><div class=bounce1></div><div class=bounce2></div><div class=bounce3></div></div></div><script src="/filebrowser-ee/static/js/chunk-vendors.de215bb2.js"></script><script src="/filebrowser-ee/static/js/app.f35de706.js"></script></body></html>`

**Comment by tautcony** [comment]
flood的报错并不是很明确，可以尝试手动重新编译
```shell
username=kyu
sudo -u ${username} -H bash -c "cd /home/${username}/.flood; npm install --force && npm run build"
sudo systemctl restart flood@${username}
```

**Comment by w-kun** [comment]
> flood的报错并不是很明确，可以尝试手动重新编译
> 
> ```shell
> username=kyu
> sudo -u ${username} -H bash -c "cd /home/${username}/.flood; npm install --force && npm run build"
> sudo systemctl restart flood@${username}
> ```

npm好像检查更新失败了
```
[18:08 root@w-kun ~] > sudo chown -R $USER:$(id -gn $USER) /home/kyu/.config
[18:09 root@w-kun ~] > npm -v
6.14.15
[18:10 root@w-kun ~] > sudo -u kyu -H bash -c "cd /home/kyu/.flood; npm install --force && npm run build"
npm WARN using --force I sure hope you know what you are doing.
npm WARN acorn-jsx@5.0.1 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@2.1.0 requires a peer of babel-eslint@^7.2.3 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@2.1.0 requires a peer of eslint@^4.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@2.1.0 requires a peer of eslint-plugin-jsx-a11y@^5.1.1 but none is installed. You must install peer dependencies yourself.

audited 2296 packages in 30.948s

11 packages are looking for funding
  run `npm fund` for details

found 406 vulnerabilities (10 low, 125 moderate, 239 high, 32 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

┌───────────────────────────────────────────────────────┐
│                npm update check failed                │
│          Try running with sudo or get access          │
│         to the local update config store via          │
│ sudo chown -R $USER:$(id -gn $USER) /home/kyu/.config │
└───────────────────────────────────────────────────────┘

> flood@1.0.0 build /home/kyu/.flood
> node client/scripts/build.js

Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run next command `npm update`

<--- Last few GCs --->

[7805:0x562d640]    79652 ms: Scavenge (reduce) 252.4 (257.5) -> 252.5 (258.0) MB, 20.4 / 0.0 ms  (average mu = 0.498, current mu = 0.341) allocation failure 
[7805:0x562d640]    80021 ms: Mark-sweep (reduce) 252.5 (257.0) -> 250.1 (258.3) MB, 368.3 / 0.1 ms  (+ 118.7 ms in 15 steps since start of marking, biggest step 21.2 ms, walltime since start of marking 511 ms) (average mu = 0.388, current mu = 0.239) all

<--- JS stacktrace --->

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
 1: 0xa389b0 node::Abort() [node]
 2: 0x96e0af node::FatalError(char const*, char const*) [node]
 3: 0xbb7a4e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xbb7dc7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd73fd5  [node]
 6: 0xda496e v8::internal::EvacuateNewSpaceVisitor::Visit(v8::internal::HeapObject, int) [node]
 7: 0xdb09a6 v8::internal::FullEvacuator::RawEvacuatePage(v8::internal::MemoryChunk*, long*) [node]
 8: 0xd9cb3f v8::internal::Evacuator::EvacuatePage(v8::internal::MemoryChunk*) [node]
 9: 0xd9cdb8 v8::internal::PageEvacuationTask::RunInParallel(v8::internal::ItemParallelJob::Task::Runner) [node]
10: 0xd8f699 v8::internal::ItemParallelJob::Run() [node]
11: 0xdb2900 void v8::internal::MarkCompactCollectorBase::CreateAndExecuteEvacuationTasks<v8::internal::FullEvacuator, v8::internal::MarkCompactCollector>(v8::internal::MarkCompactCollector*, v8::internal::ItemParallelJob*, v8::internal::MigrationObserver*, long) [node]
12: 0xdb319c v8::internal::MarkCompactCollector::EvacuatePagesInParallel() [node]
13: 0xdb3365 v8::internal::MarkCompactCollector::Evacuate() [node]
14: 0xdc5361 v8::internal::MarkCompactCollector::CollectGarbage() [node]
15: 0xd81628 v8::internal::Heap::MarkCompact() [node]
16: 0xd83118 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
17: 0xd8655c v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
18: 0xd54c3b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
19: 0x109d21f v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
20: 0x1446379  [node]
Aborted
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! flood@1.0.0 build: `node client/scripts/build.js`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the flood@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kyu/.npm/_logs/2021-12-08T09_12_24_473Z-debug.log
```

debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.14.15
3 info using node@v14.18.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle flood@1.0.0~prebuild: flood@1.0.0
6 info lifecycle flood@1.0.0~build: flood@1.0.0
7 verbose lifecycle flood@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle flood@1.0.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/kyu/.flood/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle flood@1.0.0~build: CWD: /home/kyu/.flood
10 silly lifecycle flood@1.0.0~build: Args: [ '-c', 'node client/scripts/build.js' ]
11 silly lifecycle flood@1.0.0~build: Returned: code: 134  signal: null
12 info lifecycle flood@1.0.0~build: Failed to exec build script
13 verbose stack Error: flood@1.0.0 build: `node client/scripts/build.js`
13 verbose stack Exit status 134
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1058:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
14 verbose pkgid flood@1.0.0
15 verbose cwd /home/kyu/.flood
16 verbose Linux 4.19.0-6-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v14.18.1
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 134
22 error flood@1.0.0 build: `node client/scripts/build.js`
22 error Exit status 134
23 error Failed at the flood@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 134, true ]
```

**Comment by tautcony** [comment]
npm check update那个没什么关系，仅指npm本身的版本更新。这次执行过程中主要的问题是编译的过程中内存不够用了……

先执行如下指令再重新build吧

export NODE_OPTIONS=--max_old_space_size=4096

如果是实际内存过小，那你可能需要搞点swap了

**Comment by w-kun** [comment]
> npm check update那个没什么关系，仅指npm本身的版本更新。这次执行过程中主要的问题是编译的过程中内存不够用了……
> 
> 先执行如下指令再重新build吧
> 
> export NODE_OPTIONS=--max_old_space_size=4096
> 
> 如果是实际内存过小，那你可能需要搞点swap了

因为内存只有512mb，安装时已经用着swap了
<img width="218" alt="Snipaste_2021-12-08_18-45-08" src="https://user-images.githubusercontent.com/27620657/145186840-ae10aa33-29cc-43a3-b656-9ce251763252.png">


```
[18:40 root@w-kun ~] > export NODE_OPTIONS=--max_old_space_size=4096
[18:40 root@w-kun ~] > sudo -u kyu -H bash -c "cd /home/kyu/.flood; npm install --force && npm run build"
npm WARN using --force I sure hope you know what you are doing.
npm WARN acorn-jsx@5.0.1 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@2.1.0 requires a peer of babel-eslint@^7.2.3 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@2.1.0 requires a peer of eslint@^4.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-react-app@2.1.0 requires a peer of eslint-plugin-jsx-a11y@^5.1.1 but none is installed. You must install peer dependencies yourself.

audited 2296 packages in 32.116s

11 packages are looking for funding
  run `npm fund` for details

found 406 vulnerabilities (10 low, 125 moderate, 239 high, 32 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

┌───────────────────────────────────────────────────────┐
│                npm update check failed                │
│          Try running with sudo or get access          │
│         to the local update config store via          │
│ sudo chown -R $USER:$(id -gn $USER) /home/kyu/.config │
└───────────────────────────────────────────────────────┘

> flood@1.0.0 build /home/kyu/.flood
> node client/scripts/build.js

Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run next command `npm update`

<--- Last few GCs --->

[12194:0x585c640]    86418 ms: Scavenge 252.1 (257.5) -> 251.4 (257.5) MB, 0.7 / 0.0 ms  (average mu = 0.216, current mu = 0.050) allocation failure 
[12194:0x585c640]    86436 ms: Scavenge 252.1 (257.5) -> 251.7 (257.5) MB, 2.3 / 0.0 ms  (average mu = 0.216, current mu = 0.050) allocation failure 
[12194:0x585c640]    86443 ms: Scavenge 252.5 (257.5) -> 251.9 (258.0) MB, 1.2 / 0.0 ms  (average mu = 0.216, current mu = 0.050) allocation failure 


<--- JS stacktrace --->

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
 1: 0xa389b0 node::Abort() [node]
 2: 0x96e0af node::FatalError(char const*, char const*) [node]
 3: 0xbb7a4e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xbb7dc7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd73fd5  [node]
 6: 0xda496e v8::internal::EvacuateNewSpaceVisitor::Visit(v8::internal::HeapObject, int) [node]
 7: 0xdb09a6 v8::internal::FullEvacuator::RawEvacuatePage(v8::internal::MemoryChunk*, long*) [node]
 8: 0xd9cb3f v8::internal::Evacuator::EvacuatePage(v8::internal::MemoryChunk*) [node]
 9: 0xd9cdb8 v8::internal::PageEvacuationTask::RunInParallel(v8::internal::ItemParallelJob::Task::Runner) [node]
10: 0xd8f699 v8::internal::ItemParallelJob::Run() [node]
11: 0xdb2900 void v8::internal::MarkCompactCollectorBase::CreateAndExecuteEvacuationTasks<v8::internal::FullEvacuator, v8::internal::MarkCompactCollector>(v8::internal::MarkCompactCollector*, v8::internal::ItemParallelJob*, v8::internal::MigrationObserver*, long) [node]
12: 0xdb319c v8::internal::MarkCompactCollector::EvacuatePagesInParallel() [node]
13: 0xdb3365 v8::internal::MarkCompactCollector::Evacuate() [node]
14: 0xdc5361 v8::internal::MarkCompactCollector::CollectGarbage() [node]
15: 0xd81628 v8::internal::Heap::MarkCompact() [node]
16: 0xd83118 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
17: 0xd8655c v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
18: 0xd54c3b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
19: 0x109d21f v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
20: 0x1446379  [node]
Aborted
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! flood@1.0.0 build: `node client/scripts/build.js`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the flood@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kyu/.npm/_logs/2021-12-08T09_42_32_769Z-debug.log

```

**Comment by w-kun** [comment]
flood就算了也不常用，还是麻烦帮忙看下FE三点循环的问题吧
系统我换成了Ubuntu 18.04，这是安装日志
[quickbox.15058.log](https://github.com/amefs/quickbox-lite/files/7734671/quickbox.15058.log)
[output.log](https://github.com/amefs/quickbox-lite/files/7734670/output.log)

**Comment by amefs** [comment]
file browser 应该还是网络问题。之前让你使用 `curl` 测试，返回值看起来一切正常。在最近几次修改中， file browser、file browser-ee 的相关代码仅删除了 `Xenial` 的支持。

**Comment by w-kun** [comment]
重装时没绑域名试了下，file browser能用了
box install lecert -d <domain>，之后继续循环三个点
用的是freenom的免费域名，域名解析从freenom改用成阿里云也没变化
[output_2.log](https://github.com/amefs/quickbox-lite/files/7738632/output_2.log)

**Comment by amefs** [comment]
正常来说，`https://IP或域名/filebrowser/` 都会被重定向到  `https://IP或域名/filebrowser/files/`。根据我的测试不论是浏览器（已测试 Chrome 和 FireFox），还是 Curl 最后返回的内容都应该是一致的。是比较怪。
