### ISSUE TITLE
可能不是bug,就是 box install cifs --compatibility 后 无法删除盒子的文件. 是不是要另外设置什么

### ISSUE THREAD

**Issue by tanpengsccd** [amefs/quickbox-lite#125]
**描述 Bug**
可能不是bug,就是 box install cifs --compatibility 后 无法删除盒子的文件.
**重现 Bug**
无

**Comment by amefs** [comment]
1. 建议查看一下你的文件权限，在你的个人目录下运行 `ls -lah`
2. 在通过 CIFS 连接到服务器时，也有权限可以选择，注意你挂载使用的权限，以及挂载方式是否为 RW

**Comment by tanpengsccd** [comment]
请教 有可以直接安装webdav 的组件吗?

**Comment by amefs** [comment]
没有写过这个组件。一般来说这个要求可直接使用 Nginx 实现
http://nginx.org/en/docs/http/ngx_http_dav_module.html

**Comment by tanpengsccd** [comment]
我换了 这个 工具 完美解决 .

wget  https://github.com/hacdias/webdav/releases/download/v4.1.1/linux-amd64-webdav.tar.gz #下载
tar -zxvf linux-amd64-webdav.tar.gz #解压
mv webdav /usr/bin/webdav #移动到 bin
chmod 777 /usr/bin/webdav
