### ISSUE TITLE
安装tui界面乱码

### ISSUE THREAD

**Issue by ywyha** [amefs/quickbox-lite#127]
**描述 Bug**
使用xshell7和fs客户端都是乱码,切换UEF8 GBK什么的也不好使,系统是使用萌咖大佬DD的ubuntu18^

**重现 Bug**
可以重现该 Bug 的操作 (或命令)：

1. 转到 '...' 页面
2. 点击 '....'
3. 下拉到 '....'
4. 出现错误

**期望的结果**
简单明了的描述一下你期望的表现。

**截图** (可选)

![fjava_zD00D7KxdK.png](https://s2.loli.net/2021/12/22/AVp9rdqLNiMkyuD.png)
![Xshell_k4KzZUNhx3.png](https://s2.loli.net/2021/12/22/wfm4u1rp3BZaWgD.png)
---

**附加内容**
此处添加其他附加信息。

**桌面系统 (请填写下列信息):**

 - 操作系统: [Windows10 21H2]
 - 浏览器 [例如 chrome, safari]
 - 版本 [例如 22]
 - 执行的命令 (如果有) [例如 `box update quickbox`]

**智能手机 (请填写下列信息):**

 - 设备: [例如. iPhone6]
 - 操作系统: [例如. iOS8.1]
 - 浏览器 [例如 stock browser, safari]
 - 版本 [例如 22]

**Comment by tautcony** [comment]
昨日在debian上测试时有遇到类似情况，请问是否在登陆后有提示形如此的报错
`bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)`

可尝试执行如下命令，并重新进行登陆再执行升级命令

```
echo "LANG=en_US.UTF-8" >> /etc/environment
echo "LC_ALL=en_US.UTF-8" >> /etc/environment
```

**Comment by ywyha** [comment]
> 昨日在debian上测试时有遇到类似情况，请问是否在登陆后有提示形如此的报错 `bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)`
> 
> 可尝试执行如下命令，并重新进行登陆再执行升级命令
> 
> ```
> echo "LANG=en_US.UTF-8" >> /etc/environment
> echo "LC_ALL=en_US.UTF-8" >> /etc/environment
> ```

谢谢大佬,使用上边两行命令后重启了机器重新运行命令后不乱码了,脚本以后可不可以加入判定修复这个问题..
我用的系统是用萌咖大佬的脚本DD成的ubuntu18.04.

**Comment by tautcony** [comment]
由于现在还没能找到稳定复现的条件，尚无法针对性的进行处理，后续确认了具体的起因的话会进行相应的处理。
