### ISSUE TITLE
希望增加SS/V2RAY/XRAY/TROJAN等服务支持

### ISSUE THREAD

**Issue by GinChen0525** [amefs/quickbox-lite#128]
虽然quickbox-lite主要用来刷pt，但有时候看着那网速，闲着也是闲着是不~😏

**Comment by MarsBaby9** [comment]
这个是seedbox不是路由器。。。

**Comment by wxs315** [comment]
我觉得还是别自带了，自带了就容易被整个咔嚓掉。为了点个篝火把整个森林烧了不好

**Comment by MarsBaby9** [comment]
说实话，不用带。术业有专攻。如果需要自己安装就行，网上的一键脚本一大堆。

wxs315 ***@***.***> 于2022年4月5日周二 18:35写道：

**Comment by TaoRone** [comment]
我就想知道如何在不清洗Nginx的情况下如何装V2RAY……
