### ISSUE TITLE
无法打开ruTorrent

### ISSUE THREAD

**Issue by SingleRottenChips** [amefs/quickbox-lite#129]
安装，重启，打开控制台，打开ruTorrent.
log显示如下：
```bash
[12.01.2022 04:57:22] WebUI started.
[12.01.2022 04:57:28] Bad response from server: (500 [error,getplugins])
```
OP, Ubuntu 20.04.

根据此帖 [https://giters.com/QuickBox/QB/issues/153](https://giters.com/QuickBox/QB/issues/153)，装了APACHE + PHP 7后，重启，问题仍未解决。

其他BT客户端都正常。请问是哪里出了问题？

**Comment by amefs** [comment]
初步认定是上游代码发生变化，目前解决方法是禁用 logoff 插件。可以通过面板中 ruTorrent 插件管理卸载。请务必删除 Apache 以及它的组件，它可能会干扰 Nginx 的正常运行。QuickBox CE 已经与本项目有较大区别，修复方案不通用。

**Comment by SingleRottenChips** [comment]
> 初步认定是上游代码发生变化，目前解决方法是禁用 logoff 插件。可以通过面板中 ruTorrent 插件管理卸载。请务必删除 Apache 以及它的组件，它可能会干扰 Nginx 的正常运行。QuickBox CE 已经与本项目有较大区别，修复方案不通用。

感谢解疑。禁用logoff插件后就能打开了，虽然我并不知道如何删除Apache及其组件。

**Comment by SingleRottenChips** [comment]
> 初步认定是上游代码发生变化，目前解决方法是禁用 logoff 插件。可以通过面板中 ruTorrent 插件管理卸载。请务必删除 Apache 以及它的组件，它可能会干扰 Nginx 的正常运行。QuickBox CE 已经与本项目有较大区别，修复方案不通用。

删掉apache2, libapache2-mod-php, libapache2-mod-scgi, libapache2-mod-fastcgi, log显示以下：

[12.01.2022 12:44:52] WebUI started.
[12.01.2022 12:45:02] Failed to get directory contents - /
[12.01.2022 12:45:05] autodl-irssi: __init2: ex: Exception info: No content elem with id autodl-prefs-contents-upload

看到网上的帖子说是Apache与Nginx的兼容性问题，请问是还有上面组件未删除吗？虽然刚刚得知刚进皮不能用iRSSi刷，但还是想用ruTorrent的RSS刷其他站。谢谢大佬。

**Comment by amefs** [comment]
请切换到 development 分支，执行 `box update rutorrent` 重新安装 ruTorrent。目前问题应该已经得到修复。

**Comment by SingleRottenChips** [comment]
> 请切换到 development 分支，执行 `box update rutorrent` 重新安装 ruTorrent。目前问题应该已经得到修复。

抱歉，再次打扰大佬了。

我因为没看到 File Browser Enhanced，自己安装了docker和FBE，发现之后将docker清除干净（不会显示版本号了），但仍旧无法在管理中心中安装FBE。显示:
 Docker process running. 
 If you believe this to be in error, please manually remove the /install/.install.lock.
✗ Exiting...

删除这个文件后也没用。请问除了重装系统之外，还有其他解决办法吗？或者，有什么打开通过SSH安装的filebrowser-ee吗？

另外，我不太清楚大佬您说的 development 分支是指什么，在哪里。盒子目前很稳定，感谢！

**Comment by SingleRottenChips** [comment]
> > 请切换到 development 分支，执行 `box update rutorrent` 重新安装 ruTorrent。目前问题应该已经得到修复。
> 
> 抱歉，再次打扰大佬了。
> 
> 我因为没看到 File Browser Enhanced，自己安装了docker和FBE，发现之后将docker清除干净（不会显示版本号了），但仍旧无法在管理中心中安装FBE。显示: Docker process running. If you believe this to be in error, please manually remove the /install/.install.lock. ✗ Exiting...
> 
> 删除这个文件后也没用。请问除了重装系统之外，还有其他解决办法吗？或者，有什么打开通过SSH安装的filebrowser-ee吗？
> 
> 另外，我不太清楚大佬您说的 development 分支是指什么，在哪里。盒子目前很稳定，感谢！

实在抱歉，点击管理中心里的消除锁之后就解决问题了。但还能烦请大佬解释一下这个development分支吗，谢谢。

**Comment by amefs** [comment]
目前 development 分支的更新已经合并到主分支，只需要直接更新即可。切换分支参见[此处](https://cn.wiki.ptbox.dev/getting-started/#%E5%B7%B2%E7%BB%8F%E5%AE%89%E8%A3%85-quickbox-%E5%B8%8C%E6%9C%9B%E5%88%87%E6%8D%A2%E5%88%B0%E5%BC%80%E5%8F%91%E8%80%85%E6%A8%A1%E5%BC%8F)。
