### ISSUE TITLE
[Fixed]update not working

### ISSUE THREAD

**Issue by newage11** [amefs/quickbox-lite#13]
I want to upgrade from version 1.2 to 1.3，staying here no respond

![捕获](https://user-images.githubusercontent.com/49372320/74601365-7ee02c00-50d8-11ea-93c2-e48214014a73.PNG)

===============================
use ssh client run 

 > box update quickbox
➜ QuickBox update is running.
➜ If you believe this to be in error, please manually remove the /install/.install.lock

**Comment by tautcony** [comment]
You can execute `sudo rm /install/.install.lock` and then try to update quickbox by execute `sudo box update quickbox` under this ssh session again.

**Comment by newage11** [comment]
thank you. it work.
