### ISSUE TITLE
升级1.5.2版本后web控制台按钮消失

### ISSUE THREAD

**Issue by wangkeair** [amefs/quickbox-lite#130]
升级1.5.2版本后web控制台按钮消失，在组件控制中心刷新webconsole无效，ssh4747端口也无法连接，小白求助大佬！
<img src="https://img.pterclub.com/images/2022/01/25/quickbox.jpg" alt="quickbox.jpg" border="0" />

**Comment by amefs** [comment]
在这个版本中 Webconsole 使用 ttyd 实现，你这里可能是遇到更新没有完全，可以尝试再次更新。SSH 服务并不会在更新中被修改，建议检查网络连接。

**Comment by wangkeair** [comment]
大佬好！感谢大佬耐心解答，按照大佬提示我重新运行了更新程序，显示更新成功（图1），但是仍然没有出现webconsole按钮，另外我在网页历史记录中找到原来控制台的链接，点击后显示502（图2）。另外ssh无法连接我怀疑是我修改了端口（具体忘记了），但是目前进不去后台，无法查看端口具体是多少。陷入困境，恳请大佬指点。
<img src="https://img.pterclub.com/images/2022/01/26/1.jpg" alt="1" border="0">
<img src="https://img.pterclub.com/images/2022/01/26/2.jpg" alt="2" border="0">

**Comment by tautcony** [comment]
更新的日志发一下，或者观察其中是否包含形如`ttyd binary download success|failed`之类字样的信息。

----

web console的url是对的，但是它当前没启动，导致502，或者你也可以同时试一下点击上面web console右边的刷新按钮。

**Comment by wangkeair** [comment]
楼上大佬好，点击web console刷新按钮无效。另外更新日志我不知道在哪里找...更新完以后显示出来的这些无法复制出来。

**Comment by tautcony** [comment]
fbe是基于docker运行的，挂载的是你自己用户的目录`-v /home/${username}/:/myfiles`，可能你挂载出来的只是容器里的`/etc`。

你访问`https://xxxxx/db/output.log`，应该就能取到了。

**Comment by wangkeair** [comment]
感谢大佬指点，请大佬帮忙看下日志
https://paste.ubuntu.com.cn/4545402

**Comment by tautcony** [comment]
分析下来是你的服务器在升级的过程中`ttyd`下载失败，然后当前脚本中更新的逻辑需要`ttyd`存在才能重新下载。

当前已经在`development`中完成相关逻辑修改，有待验证再并入主分支，故尚需稍等几日。由于你现在无法登陆后台，暂无法通过切换到`development`分支进行修正更新。

**Comment by wangkeair** [comment]
好的，谢谢大佬！等主分支更新后我再更新即可，再次感谢大佬的时间！

**Comment by amefs** [comment]
相关代码已经完成测试，可以通过仪表盘获取更新。

**Comment by wangkeair** [comment]
报告大佬，重新更新后仍未解决问题，面板中WEBcontrol旁边的红点出现了，但是按钮仍然未出现。在服务控制中心种刷新、停止重新启动也无效。见下图及安装日志。
<img src="https://img.pterclub.com/images/2022/01/28/seedbox3.jpg" alt="seedbox3.jpg" border="0" />
https://paste.ubuntu.com.cn/4545411

**Comment by tautcony** [comment]
你需要再点击一下更新，以执行新的更新脚本

**Comment by wangkeair** [comment]
抱歉大佬，仍然不行。
https://paste.ubuntu.com.cn/4545413

**Comment by amefs** [comment]
从日志中无法判定 WebConsole 的工作状态。但我有个两个方案可能可以解决你找不到 ssh 端口的问题：
1. 你使用服务器的 Rescue 救援模式。如果是 Hetzner 的话因为你无法操作关机重启，因此可以开启救援模式后，选择软重启 ( 	`Send CTRL+ALT+DEL to the server`)。在 Rescue 模式中，你挂载磁盘。举例：磁盘为 `/dev/md127`，你运行 `mount /dev/md127 /mnt` 挂载磁盘，随后就可以在 `/mnt` 路径下搜索 `sshd_config` 文件查看你的端口，最后通过 `umount /mnt` 卸除挂载并重启到正常系统即可。
2. 使用端口扫描软件把可能的端口范围扫描一下，尝试连接你的 ssh。

**Comment by wangkeair** [comment]
好的，谢谢大佬指教。我先试试。然后等下次版本更新时再更新一下，看看能否恢复。
