### ISSUE TITLE
安装FBE再次出现问题，一番操作后dashboard无法打开

### ISSUE THREAD

**Issue by SingleRottenChips** [amefs/quickbox-lite#134]
另一个盒子，Ubuntu 18.04系统。

安装FBE卡在设置docker-ce, 显示 failed to activate service 'org.freedesktop.systemd1'

听从网上建议升级systemd，但不料升级过程又要设置docker-ce.

无奈只好强制重启。

重启之后Dashbored就打不开了，rutorrent还正常运行。SSH后好像多了这一行：
|  ###################   This Server is OFF limits   ####################|

继续升级systemd, 显示“正在设置 docker-ce (5:20.10.12~3-0~ubuntu-bionic) ...
Created symlink /etc/systemd/system/multi-user.target.wants/docker.service → /lib/systemd/system/docker.service.
Created symlink /etc/systemd/system/sockets.target.wants/docker.socket → /lib/systemd/system/docker.socket.
W: APT had planned for dpkg to do more than it reported back (0 vs 4).
   Affected packages: docker-ce:amd64”

请问大佬我该怎么应对现在这个情况？

**Comment by SingleRottenChips** [comment]
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2022-01-27 22:32:35 CET; 14min ago
     Docs: man:nginx(8)

1月 27 22:32:35 PAR-350977 systemd[1]: Starting A high performance web server and a reverse proxy server...
1月 27 22:32:35 PAR-350977 systemd[1]: nginx.service: Control process exited, code=exited status=1
1月 27 22:32:35 PAR-350977 nginx[4475]: nginx: [emerg] invalid port in upstream "127.0.0.1:/znc/" in /etc/nginx/apps/znc.conf:3
1月 27 22:32:35 PAR-350977 nginx[4475]: nginx: configuration file /etc/nginx/nginx.conf test failed
1月 27 22:32:35 PAR-350977 systemd[1]: nginx.service: Failed with result 'exit-code'.
1月 27 22:32:35 PAR-350977 systemd[1]: Failed to start A high performance web server and a reverse proxy server.

**Comment by SingleRottenChips** [comment]
[nginx.conf.txt](https://github.com/amefs/quickbox-lite/files/7954101/nginx.conf.txt)

**Comment by SingleRottenChips** [comment]
sudo apt-get remove --purge nginx nginx-full nginx-common 
and sudo apt-get install nginx 之后没问题了：
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
但仪表盘依然无法打开

**Comment by SingleRottenChips** [comment]
请问问题是在这里吗：

✓ Dashboard service updated
/usr/local/bin/quickbox/system/update/qbUpdateService: line 172: /etc/nginx/apps/dashboard.conf: No such file or directory
/usr/local/bin/quickbox/system/update/qbUpdateService: line 176: /etc/nginx/apps/rutorrent.conf: No such file or directory

**Comment by amefs** [comment]
在你执行 `sudo apt-get remove --purge nginx nginx-full nginx-common && sudo apt-get install nginx` 以后所有配置文件已经被重置，因此面板无法正常工作。

**Comment by SingleRottenChips** [comment]
感谢大佬回复。请问配置文件还有可能复原吗？
[nginx.conf.txt](https://github.com/amefs/quickbox-lite/files/7954302/nginx.conf.txt)

**Comment by amefs** [comment]
比较麻烦，如果可能的话建议直接重新安装。

**Comment by SingleRottenChips** [comment]
> 比较麻烦，如果可能的话建议直接重新安装。我猜测你上面的问题可能是安装过程中内存占用过高导致进程自杀造成的。

我当时就开了一个rt，也没在下种子...

我有很多H&R种子，重装系统后逐个重下有点麻烦... 有什么办法的话大佬但说无妨。
请问仅仅把另一个盒子/etc/nginx目录下所有文件照搬过来 管用吗？SCP也连不上，逐个写也好麻烦...
我搬了大部分，但执行sudo nginx -t, 得到：
nginx: [emerg] "user" directive is duplicate in /etc/nginx/nginx.conf:86
nginx: configuration file /etc/nginx/nginx.conf test failed

然而第86行是  # number of requests client can make over keep-alive -- for testing environment.... 
这是怎么回事？
