### ISSUE TITLE
Reboot之后仪表盘无法打开

### ISSUE THREAD

**Issue by SingleRottenChips** [amefs/quickbox-lite#136]
又来麻烦大佬了。发现盒子的下载速度被限制在10MB/s，安装了Speedtest，但打开显示404。于是SSH上盒子后重启。之后仪表盘和rutorrent都无法打开了。SSH照常使用。请问还有补救的方法吗？谢谢大佬。

**Comment by tautcony** [comment]
执行`box troubleshoot `，把`/root/qbLog.tar.gz`传上来看一下

**Comment by SingleRottenChips** [comment]
> 执行`box troubleshoot `，把`/root/qbLog.tar.gz`传上来看一下
[qbLog.tar.gz](https://github.com/amefs/quickbox-lite/files/8021525/qbLog.tar.gz)

**Comment by tautcony** [comment]
```
nginx: [emerg] invalid port in upstream "127.0.0.1:/znc/" in /etc/nginx/apps/znc.conf:3
nginx: configuration file /etc/nginx/nginx.conf test failed
```

znc被配置坏了，要不根据上面的提示把端口给补上，要不卸载掉。然后再重启ngnix

**Comment by SingleRottenChips** [comment]
感谢大佬！卸载znc、重启ngnix问题就解决了。不过我只是用box安装了znc，没有任何后续的操作。装了两次好像都出现了问题，不知道是不是我机子的原因。

**Comment by tautcony** [comment]
```bash
	_print "Please answer the following questions to finish znc Configuration:"
	sleep 2
	sudo -H -u $APP_NAME $APP_NAME --makeconf
```

ZNC安装过程中需要根据提示进行配置的输入，不然会有问题。
