### ISSUE TITLE
下载速度被限制到10MB/s左右

### ISSUE THREAD

**Issue by SingleRottenChips** [amefs/quickbox-lite#137]
又来麻烦大佬了。请问为何我的服务器下载速度被限制到10MB/s左右？G管的服务器。
软件设置都是默认的，唯一的区别可能就是开始使用irssi.
重启没有用。
用安装的speedtest测试，速度上不去1MB/s。
刚给OP交了一张ticket，还没回。
跟空余硬盘容量过低有关系吗？可是我之前的机子从来没有出现过这个情况呀...

**Comment by amefs** [comment]
运行 `ethtool enp1s0 | grep -i speed` enp1s0 为你的网口名称。有些 online 的服务器会遇到被限速。测速建议使用 iperf
```
iperf3 -c ping.online.net -t 20 -d -p 5203 # upload
iperf3 -c ping.online.net -t 20 -d -p 5203 -R # download
```

**Comment by SingleRottenChips** [comment]
> 运行 `ethtool enp1s0 | grep -i speed` 查看你的网络物理连接速度，enp1s0 为你的网口名称。有些 online 的服务器会遇到被限速。此外这些网络并非 1Gbps 保障，会和同机柜的服务器共享带宽。测速建议使用 iperf
> 
> ```
> iperf3 -c ping.online.net -t 20 -d -p 5203 # upload
> iperf3 -c ping.online.net -t 20 -d -p 5203 -R # download
> ```

我测了rt的网口，只有100Mb/s... 请问这是网口被限速了吗。

**Comment by amefs** [comment]
如果你看到
```
Speed: 100Mb/s
```
就代表被限速了，如果重启没有恢复 1Gbps 则只能通过 ticket 解除；此外这种问题在解除后仍然有一定概率发生。

**Comment by SingleRottenChips** [comment]
> 如果你看到
> 
> ```
> Speed: 100Mb/s
> ```
> 
> 就代表被限速了，如果重启没有恢复 1Gbps 则只能通过 ticket 解除；此外这种问题在解除后仍然有一定概率发生。

好的。感谢大佬解疑。
