### ISSUE TITLE
web console不能用box set passwd 改密码了

### ISSUE THREAD

**Issue by burtchina** [amefs/quickbox-lite#138]
**描述 Bug**
web console不能用box set passwd 改密码了
不管输入什么密码(例如：se7qSDphNIMlZ)总是提示：Your password must consist: 1.digital numbers 2.at least one lower case letter 3.one upper case letter

服务器系统是debian10,手机浏览器是chrome

**Comment by amefs** [comment]
你是否测试过 PC 端的 Chrome？我使用 Debian 10，并且使用你的示例密码无法复现这个问题。

**Comment by burtchina** [comment]
![Screenshot_2022-02-12-09-03-05-692_com server auditor ssh client_mh1644628093462](https://user-images.githubusercontent.com/27072523/153690166-24cb77da-b3ca-4e3b-a9f9-649867a95a41.jpg)

我用termius登录测试也不行哦

**Comment by amefs** [comment]
使用 `box` 命令无需指定用户。`box set passwd <password>` 即可。此外 Debian 10 不应该使用 legacy 分支。

**Comment by burtchina** [comment]
更新到最新版本解决了，应该是版本问题，原来1.50，更新到了1.52
