### ISSUE TITLE
安装脚本后，HZ官方提示MAC 滥用

### ISSUE THREAD

**Issue by wansheng88** [amefs/quickbox-lite#140]
安装了QuickBox Lite1.52版本，软件只是用了QB4.19版本，File Browser及flexget，HZ的官方老是提示有MAC 滥用问题（Abuse Message [AbuseID:XXXXXX:XX]: MAC-Errors:），已经换了多个盒子，系统从Debian 10、Ubuntu 18.04和Ubuntu 20.04都进行了更换，一直报错，不知道是什么问题，还望请各位大佬能有解决办法。

**Comment by wansheng88** [comment]
qBittorrent因为需挂PT，所以“启用 DHT (去中心化网络) 以找到更多用户”，“启用用户交换 (PeX) 以找到更多用户”，“启用本地用户发现以找到更多用户”这3项是不开启的，UPNP功能没有开，docker也没用，盒子只安装了QB4.19版本，File Browser及flexget，所以才来求助，若盒子脚本屏蔽掉这个错误，那就好了，另，这是我qBittorrent4.19的设置，不知道是不是哪项设定错了，还望请指出，谢谢。
[AutoRun]
enabled=false
program=

[BitTorrent]
Session\AsyncIOThreadsCount=16
Session\BTProtocol=Both
Session\Categories=@Variant(\0\0\0\b\0\0\0\x1\0\0\0\xe\0L\0\x65\0m\0o\0n\0h\0\x64\0\0\0\n\0\0\0\0)
Session\ChokingAlgorithm=FixedSlots
Session\CreateTorrentSubfolder=true
Session\DisableAutoTMMByDefault=true
Session\DisableAutoTMMTriggers\CategoryChanged=true
Session\DisableAutoTMMTriggers\CategorySavePathChanged=true
Session\DisableAutoTMMTriggers\DefaultSavePathChanged=true
Session\GuidedReadCache=true
Session\MultiConnectionsPerIp=true
Session\SeedChokingAlgorithm=FastestUpload
Session\SendBufferLowWatermark=1024
Session\SendBufferWatermark=3072
Session\SendBufferWatermarkFactor=150

[Core]
AutoDeleteAddedTorrentFile=Never

[LegalNotice]
Accepted=true

[Preferences]
Bittorrent\AddTrackers=false
Bittorrent\DHT=false
Bittorrent\Encryption=0
Bittorrent\LSD=false
Bittorrent\MaxConnecs=-1
Bittorrent\MaxConnecsPerTorrent=-1
Bittorrent\MaxRatioAction=0
Bittorrent\PeX=false
Connection\GlobalDLLimitAlt=10
Connection\GlobalUPLimitAlt=10
Connection\UPnP=false
Downloads\DiskWriteCacheSize=8192
Downloads\DiskWriteCacheTTL=30
Downloads\PreAllocation=false
Downloads\SavePath=/home/name/torrents/qbittorrent
Downloads\ScanDirsV2="@Variant(\0\0\0\x1c\0\0\0\x1\0\0\0,\0/\0h\0o\0m\0\x65\0/\0w\0\x61\0n\0s\0h\0\x65\0n\0g\0/\0q\0\x62\0w\0\x61\0t\0\x63\0h\0\0\0\x2\0\0\0\x1)"
Downloads\StartInPause=false
DynDNS\DomainName=changeme.dyndns.org
DynDNS\Enabled=false
DynDNS\Password=
DynDNS\Service=0
DynDNS\Username=
General\Locale=zh
General\UseRandomPort=false
MailNotification\email=
MailNotification\enabled=false
MailNotification\password=
MailNotification\req_auth=true
MailNotification\req_ssl=false
MailNotification\sender=qBittorrent_notification@example.com
MailNotification\smtp_server=smtp.changeme.com
MailNotification\username=
Queueing\MaxActiveDownloads=-1
Queueing\MaxActiveTorrents=-1
Queueing\MaxActiveUploads=-1
WebUI\Address=127.0.0.1
WebUI\AlternativeUIEnabled=false
WebUI\AuthSubnetWhitelist=@Invalid()
WebUI\AuthSubnetWhitelistEnabled=false
WebUI\CSRFProtection=true
WebUI\ClickjackingProtection=true
WebUI\HTTPS\Enabled=false
WebUI\HostHeaderValidation=true
WebUI\LocalHostAuth=false
WebUI\Password_ha1=@ByteArray(73757106e82d9506d957459b36f915c4)
WebUI\Port=15153
WebUI\RootFolder=
WebUI\ServerDomains=*
WebUI\UseUPnP=false
WebUI\Username=

**Comment by amefs** [comment]
我认为你的 qBittorrent 配置一切正常。建议排查一下有没有其他优化导致滥用问题（例如锐速，改版 BBR 等）。如果有能力的话最好通过 `tcpdump` 确认 Hetzner 警报中出现的内容。
