### ISSUE TITLE
安装时卡在“正在安装ntp"

### ISSUE THREAD

**Issue by Magic-glass** [amefs/quickbox-lite#141]
**描述 Bug**
![图片](https://user-images.githubusercontent.com/49303407/156534767-9a83f955-cf83-4e83-b701-047ebf255173.png)
安装时卡住在“正在安装ntp"

重启后重新安装时提示“dpkg 被中断，您必须手工运行 ‘dpkg --configure -a’ 解决此问题。"

日志提示：
`root@VM-12-7-debian:~# tail -30 quickbox.3692.log 
Selecting previously unselected package libevent-core-2.1-6:amd64.
(Reading database ... 65054 files and directories currently installed.)
Preparing to unpack .../libevent-core-2.1-6_2.1.8-stable-4_amd64.deb ...
Unpacking libevent-core-2.1-6:amd64 (2.1.8-stable-4) ...
Selecting previously unselected package libevent-pthreads-2.1-6:amd64.
Preparing to unpack .../libevent-pthreads-2.1-6_2.1.8-stable-4_amd64.deb ...
Unpacking libevent-pthreads-2.1-6:amd64 (2.1.8-stable-4) ...
Selecting previously unselected package libopts25:amd64.
Preparing to unpack .../libopts25_1%3a5.18.12-4_amd64.deb ...
Unpacking libopts25:amd64 (1:5.18.12-4) ...
Selecting previously unselected package ntp.
Preparing to unpack .../ntp_1%3a4.2.8p12+dfsg-4_amd64.deb ...
Unpacking ntp (1:4.2.8p12+dfsg-4) ...
Selecting previously unselected package sntp.
Preparing to unpack .../sntp_1%3a4.2.8p12+dfsg-4_amd64.deb ...
Unpacking sntp (1:4.2.8p12+dfsg-4) ...
Setting up libopts25:amd64 (1:5.18.12-4) ...
Setting up ntp (1:4.2.8p12+dfsg-4) ...
Installing new version of config file /etc/apparmor.d/usr.sbin.ntpd ...

Configuration file '/etc/ntp.conf'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** ntp.conf (Y/I/N/O/D/Z) [default=N] ? `

![图片](https://user-images.githubusercontent.com/49303407/156536535-3f88cba8-809a-4f8f-9946-c12b477d62f9.png)
并且重新进入TUI界面后界面混乱

---

**附加内容**
此处添加其他附加信息。

**桌面系统 (请填写下列信息):**

 - 操作系统:Debian 10.2 64bit

**Comment by amefs** [comment]
这个问题一般出现在安装有 ntp 并且由于你的 Debian patch 版本比较老(目前最新的是 Debian 10.11)，所以会在更新时提醒你替换配置，目前你可以在运行 `dpkg --configure -a` 后重新运行安装脚本。脚本在完成依赖包安装之前不会进行额外配置，因此可以随时重新运行，无需重装系统。

**Comment by Magic-glass** [comment]
![图片](https://user-images.githubusercontent.com/49303407/156550361-7002801d-8de1-4783-9cb3-bdb33db13d85.png)
现在卡在了setting up webconsole
日志提示最后一步为Processing triggers for man-db (2.8.5-2) ...
![图片](https://user-images.githubusercontent.com/49303407/156550563-c9f82190-ad37-40d8-8cad-9ed14c817be1.png)

**Comment by amefs** [comment]
重启以后尝试手动安装 `apt-get install -y nodejs` 如果没有问题的话，可以尝试继续安装流程。

**Comment by Magic-glass** [comment]
已经安装完毕，感谢大佬...
不过在我自行安装iftop后，dashboard的View Additional Bandwidth Details好像失效了，请问要如何排查
![图片](https://user-images.githubusercontent.com/49303407/156572557-b111d219-5f0a-49b5-9552-2f9c911d01b8.png)
