### ISSUE TITLE
 ruTorrent缺少bulk_magnet插件

### ISSUE THREAD

**Issue by Magic-glass** [amefs/quickbox-lite#142]
https://github.com/Novik/ruTorrent/tree/master/plugins/bulk_magnet

面板中如何指定添加？还是说要使用命令行？

**Comment by amefs** [comment]
由于 3.10 版 ruTorrent 并没有这个模块，因此你需要自行将插件放入 `/srv/rutorrent/plugins`。只需要将这部分代码解压到目标文件夹，并且运行 `chown -R www-data:www-data /srv/rutorrent` 即可。
