### ISSUE TITLE
fio-bench_zh-cn.py脚本未同步更新

### ISSUE THREAD

**Issue by Magic-glass** [amefs/quickbox-lite#143]
[quickbox-lite](https://github.com/amefs/quickbox-lite)/packages/system/auxiliary/fio-bench_zh-cn.py
与[fio-bench](https://github.com/amefs/fio-bench)不同步，还是导出有问题的版本，dalao有空的话fork一下Ψ(￣∀￣)Ψ，萌新不太会操作gayhub

**Comment by tautcony** [comment]
你这个问题说的太模糊了，有问题是什么问题呢，什么目的，什么场景下，怎么操作，什么参数的情况下，能够复现这个问题，其预期的正确的是什么呢，请根据issue template进行问题描述。

两个repo里的代码我比对了一下，就差了一个`encoding`，如果是它，请先自行调整。
```diff
+    fo = open(filename, "w+")
-    with open(filename, "w+", encoding="utf-8") as fo:
```
