### ISSUE TITLE
升级 qbittorrent后无法启动

### ISSUE THREAD

**Issue by Hbxycch** [amefs/quickbox-lite#146]
**描述 Bug**
使用以下命令升级到qbittorrent 4.3.8后，qbittorrent 打不开，无法访问，因为要使用rss，所以要升级到高版本
box update qbittorrent --qb 4.3.8 --force
请问是我方法不对么，有没有具体升级说明，我在wiki只看到了降级说明

**Comment by amefs** [comment]
请你描述你使用的系统，以及你从什么版本升级。

**Comment by Hbxycch** [comment]
操作系统：Ubuntu 20
QuickBox :: v1.5.2
qBittorrent版本号： v4.2.5 Web UI (64-bit)
qBittorrent要升级的版本号：qBittorrent v4.3.8 Web UI (64-bit)
使用的升级命令：
[14:50 root@HZ ~] > 
[14:50 root@HZ ~] > 
[14:50 root@HZ ~] > box update qbittorrent --qb 4.3.8 --force

qBittorrent will now be updated.

This process may take a few minutes
Please wait until the process is completed

➜ Upgrading qBittorrent...
➜ Removing old qBittorrent...
⚠ Use Libtorrent 1.2.12 for qBittorrent 4.3.x
➜ Fetching package list...
➜ building static qBittorrent... 
cp: cannot stat '/tmp/qb-static/qb-build/completed/qbittorrent-nox': No such file or directory
chmod: cannot access '/usr/local/bin/qbittorrent-nox': No such file or directory
➜ cleaning up... 
✓ qBittorrent is now update to date.
[14:51 root@HZ ~] > 

升级后访问qb报错：
502 Bad Gateway

**Comment by amefs** [comment]
请切换到 `development` 分支后再次运行 `box update qbittorrent --qb 4.3.8 --force`。

**Comment by Hbxycch** [comment]
`bash <(wget -qO- https://git.io/qbox-lite -o /dev/null) --dev COMMAND`
执行这个代码是否可以切换到 `development` 分支

**Comment by tautcony** [comment]
root下执行`box enable-dev`，你上面那个是安装的命令

**Comment by Hbxycch** [comment]
运行以下内容：
`box enable-dev`
`box update qbittorrent --qb 4.3.8 --force`
已成功升级，非常感谢!
