### ISSUE TITLE
仪表盘打不开啊？

### ISSUE THREAD

**Issue by hyy34** [amefs/quickbox-lite#148]
online的机器，dd了debian10，安装了之后，网址输入为IP，http自动转https无法打开仪表盘。。。403错误，是nginx有问题了？？

[qbLog.tar.gz](https://github.com/amefs/quickbox-lite/files/8410268/qbLog.tar.gz)

**Comment by hyy34** [comment]
box install transmission
显示的是
box install transmission

**Comment by hyy34** [comment]
尝试用命令行安装，不用TUI安装，
Cloning into '/etc/QuickBox'...
fatal: Unable to read current working directory: No such file or directory
dos2unix: /etc/QuickBox/setup.sh: No such file or directory
dos2unix: Skipping /etc/QuickBox/setup.sh, not a regular file.
/dev/fd/63: line 102: cd: /etc/QuickBox: No such file or directory
提示这个。。

**Comment by tautcony** [comment]
安装过程中出现中断了吧，没有安装完，直接按手册重新安装吧，会覆盖的。

**Comment by tautcony** [comment]
那怎么看着`/etc/QuickBox`好像都没成功拉下来。

看看目录
```bash
ls -la /srv/dashboard
ls -la /etc/QuickBox
```

**Comment by hyy34** [comment]
> 那怎么看着`/etc/QuickBox`好像都没成功拉下来。
> 
> 看看目录
> 
> ```shell
> ls -la /srv/dashboard
> ls -la /etc/QuickBox
> ```

找不到，这俩个目录。。为什么无法创建呢？

**Comment by tautcony** [comment]
那就没装成功，你还是用`bash <(wget -qO- https://git.io/qbox-lite -o /dev/null)`这个重装吧

**Comment by hyy34** [comment]
> 那就没装成功，你还是用`bash <(wget -qO- https://git.io/qbox-lite -o /dev/null)`这个重装吧

shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Cloning into '/etc/QuickBox'...
fatal: Unable to read current working directory: No such file or directory
dos2unix: /etc/QuickBox/setup.sh: No such file or directory
dos2unix: Skipping /etc/QuickBox/setup.sh, not a regular file.
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
/dev/fd/63: line 102: cd: /etc/QuickBox: No such file or directory

**Comment by tautcony** [comment]
你的系统没有`/etc`目录？

**Comment by hyy34** [comment]
> 你的系统没有`/etc`目录？
> 
> 看看
> 
> ```shell
> ls -la /
> ls -la /etc
> ```

有的。。

**Comment by hyy34** [comment]
用ubuntu的系统，可以了。@@
