### ISSUE TITLE
局域网网络文件共享

### ISSUE THREAD

**Issue by Latezly** [amefs/quickbox-lite#15]
**Is your feature request related to a problem? Please describe.**
在局域网内通过windows映射网络驱动器把文件拉回常用电脑上
如同本地NAS一样

**Describe the solution you'd like**
把Samba或者NFS等文件共享功能的apt安装选项集成在panel上

**Describe alternatives you've considered**
直接在系统命令行通过apt安装

**Additional context**
文件共享和Seedbox起着相辅相成的作用，但是直接通过系统安装多多少少会有一些权限、端口、账号、密码、等奇奇怪怪的问题，而通过panel安装直接把这些问题以一个相对的标准设置好，从而减少其他不必要的玄学问题

**Comment by amefs** [comment]
It will be available in the next release.

- [x] add install support Samba Server
- [x] add install support NFS Server
- [ ] check compatibility
