### ISSUE TITLE
ruTorrent 突然打不开了

### ISSUE THREAD

**Issue by SingleRottenChips** [amefs/quickbox-lite#150]
抱歉，我搞错了，ruTorrent能打开，但显示无法连接到rTorrent. 其他软件正常。

执行命令：
```
> systemctl status rtorrent@lochips.service
```

显示：
```
> Loaded: loaded (/etc/systemd/system/rtorrent@.service; indirect; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2022-04-23 10:31:12 CEST; 50s ago
  Process: 2440 ExecStop=/usr/bin/screen -X -S rtorrent quit (code=exited, status=1/FAILURE)
  Process: 826 ExecStart=/usr/bin/screen -d -m -fa -S rtorrent /usr/bin/rtorrent (code=exited, status=0/SUCCESS)
  Process: 622 ExecStartPre=/bin/rm -f /home/lochips/.sessions/rtorrent.lock (code=exited, status=0/SUCCESS)
 Main PID: 1032 (code=exited, status=0/SUCCESS)

4月 23 10:30:29 PAR-350977 systemd[1]: Starting rTorrent...
4月 23 10:30:37 PAR-350977 systemd[1]: Started rTorrent.
4月 23 10:31:12 PAR-350977 screen[2440]: No screen session found.
4月 23 10:31:12 PAR-350977 systemd[1]: rtorrent@lochips.service: Control process exited, code=exited status=1
4月 23 10:31:12 PAR-350977 systemd[1]: rtorrent@lochips.service: Failed with result 'exit-code'.
```

看到一个几乎一样的[帖子：](https://github.com/swizzin/swizzin/issues/195)，但指引的另一个帖子情况又不太一样。

重启了没用。不敢乱执行升级命令。

请问是哪里出了问题，而我应该怎么做？谢谢大佬。

**Comment by amefs** [comment]
请在 SSH 运行 `systemctl start rtorrent@lochips.service` 查看是否存在异常输出。此外请提供 `journalctl  -u rtorrent@lochips.service > rtorrent.log` 得到的 log 文件。

**Comment by SingleRottenChips** [comment]
> 请在 SSH 运行 `systemctl start rtorrent@lochips.service` 查看是否存在异常输出。此外请提供 `journalctl -u rtorrent@lochips.service > rtorrent.log` 得到的 log 文件。

感谢回复。运行之后，仪表盘上rTorrent变绿，但打开ruTorrent还是显示无法连接，rTorrent又变红。
[rtorrent.log](https://github.com/amefs/quickbox-lite/files/8546564/rtorrent.log)

**Comment by amefs** [comment]
日志文件似乎没有足够多的信息用来判断问题，不过我认为是 rtorrent 意外退出导致的问题。建议是尝试删除 rtorrent 运行时的一些残留文件 `/bin/rm -f /home/lochips/.sessions/rtorrent.lock`，`/bin/rm -f /home/lochips/.sessions/rtorrent.dht_cache`，重新为该文件夹赋予权限 `chmod -R 755 /home/lochips/.sessions`。

**Comment by SingleRottenChips** [comment]
> 日志文件似乎没有足够多的信息用来判断问题，不过我认为是 rtorrent 意外退出导致的问题。建议是尝试删除 rtorrent 运行时的一些残留文件 `/bin/rm -f /home/lochips/.sessions/rtorrent.lock`，`/bin/rm -f /home/lochips/.sessions/rtorrent.dht_cache`，重新为该文件夹赋予权限 `chmod -R 755 /home/lochips/.sessions`。

我试了这三个命令，没起作用。我用box命令移除rtorrent后想重装，显示rt正在运行。
照办 `rm -r /lock/.install.lock` 后，还是无法安装。
请问有什么建议吗？

**Comment by amefs** [comment]
你可以查看 `/home/lochips/.sessions/` 所有种子均保存在这里。rtorrent 如果显示正在运行，则可能你有一个 rtorrent 的进程正在运行。你可以运行 `pkill rtorrent` 停止该进程。

**Comment by SingleRottenChips** [comment]
> 你可以查看 `/home/lochips/.sessions/` 所有种子均保存在这里。rtorrent 如果显示正在运行，则可能你有一个 rtorrent 的进程正在运行。你可以运行 `pkill rtorrent` 停止该进程。

我用了 pkill  加  -1 -9 -15后， 都没有反应。还是显示 `rTorrent process running.` ... 这该咋办捏┭┮﹏┭┮

**Comment by amefs** [comment]
运行一下 `ps -aux | grep rtorrent` 查看是否实际存在进程。

**Comment by SingleRottenChips** [comment]
> 运行一下 `ps -aux | grep rtorrent` 查看是否实际存在进程。

`root      5899  0.0  0.0  16128   944 pts/0    S+   18:54   0:00 grep --color=auto rtorrent`

**Comment by amefs** [comment]
这说明没有该进程，你可以删除 `/install/.rtorrent.lock`，然后尝试重新安装 rtorrent。

**Comment by SingleRottenChips** [comment]
> 这说明没有该进程，你可以删除 `/install/.rtorrent.lock`，然后尝试重新安装 rtorrent。

我就是删了重装不了才来问的啊┭┮﹏┭┮

**Comment by amefs** [comment]
有重装报错的日志麽？SSH 运行 `box install rtorrent` 后有什么输出？

**Comment by SingleRottenChips** [comment]
> 有重装报错的日志麽？SSH 运行 `box install rtorrent` 后有什么输出？

请问哪里查看日志？
SSH输出：
```
➜ rTorrent process running.
➜ If you believe this to be in error, please manually remove the /install/.install.lock
✗ Exiting...
```

**Comment by amefs** [comment]
在 `/srv/dashboard/db/output.log`

**Comment by SingleRottenChips** [comment]
> 在 `/srv/dashboard/db/output.log`

```
rTorrent will now be removed.

This process may take a few minutes
Please wait until the process is completed

>> Info: Removing rTorrent service...
Removed /etc/systemd/system/multi-user.target.wants/rtorrent@lochips.service.
>> Success: rTorrent service removed.
>> Info: Removing rTorrent dependencies...
取消保留 rtorrent 的设置。
E: 无法定位软件包 libtorrent18
E: 没有发现匹配的软件包
E: 无法定位软件包 libtorrent19
E: 没有发现匹配的软件包
```

**Comment by amefs** [comment]
这三个都是另外一个 libtorrent，是 qBittorrent/deluge 的依赖，与 rTorrent 无关。你提供的这段内容是卸载只有卸载相关的，且没有问题，这些 Error 只是因为你本地已经删除了 rTorrrent 依赖的 libtorrent。

**Comment by SingleRottenChips** [comment]
> 这三个都是另外一个 libtorrent，是 qBittorrent/deluge 的依赖，与 rTorrent 无关。你提供的这段内容是卸载只有卸载相关的，且没有问题，这些 Error 只是因为你本地已经删除了 rTorrrent 依赖的 libtorrent。

所以为何重装不了呢...？

**Comment by amefs** [comment]
首先运行 `box fix dpkg` 然后运行 `box install rtorrent` 最后将你获取到的新 log 内容反馈给我。

**Comment by SingleRottenChips** [comment]
> 首先运行 `box fix dpkg` 然后运行 `box install rtorrent` 最后将你获取到的新 log 内容反馈给我。

```
>> Success: Resolved installation lock
>> Info: rTorrent process running.
>> Info: If you believe this to be in error, please manually remove the /install/.install.lock
>> Error: Exiting...
```

**Comment by amefs** [comment]
请留下你的联系方式，我可以尝试在你的服务器上找一下原因。

**Comment by SingleRottenChips** [comment]
> 请留下你的联系方式，我可以尝试在你的服务器上找一下原因。

邮箱可以吗？loss9979@gmail.com

**Comment by SingleRottenChips** [comment]
不好意思，又来打扰大佬了。

还是这个盒子，rtorrent又打不开了。

卸载重装后又显示 rt 正在运行。

请问还是需要手动安装吗？请问大佬有空吗？可以麻烦大佬帮我重装一下吗？

谢谢！┭┮﹏┭┮
