### ISSUE TITLE
Port Forward

### ISSUE THREAD

**Issue by Hipoglos** [amefs/quickbox-lite#151]
Hi @amefs ! Sorry for posting here. I'm wondering if you can help me with this issue. My box is behind a home router, so it's not accessible from outside of my network. Could you please tell me which ports I should forward to my local ip, in order to be able to access the Portal and rutorrent outside of my network? I'm using just those 2. Thanks a lot!! and sorry again for bothering!

**Comment by tautcony** [comment]
You can refer to this: [QuickBox Lite application port map](https://github.com/amefs/quickbox-lite/wiki/QuickBox-Lite-application-port-map)

**Comment by amefs** [comment]
They both use port 443. After port forwarding, you can access them via https://yourbox.

**Comment by Hipoglos** [comment]
thanks a lot, and sorry again for bothering you! working now. regards
