### ISSUE TITLE
流量排序在“过去30天”时显示异常

### ISSUE THREAD

**Issue by Magic-glass** [amefs/quickbox-lite#155]
**描述 Bug**
服务器的上行宽带仅为6mbps，在选择过去30天排序时出现了多个突破上限的平均值？

图一是 “过去30天” 排序的截图
图二是6月12日零点左右截图的 “过去24小时” ，这个数据是合理的

对不起又要麻烦大佬了呜呜呜呜_(:зゝ∠)_

**截图** (可选)
![A5BZX5RN4R5A`Z23V@H85PQ](https://user-images.githubusercontent.com/49303407/173197135-079b359e-b094-4b2f-8da4-4f055efb07b3.png)

![%YGU$VZ1KBKQA%K})HW}IZA](https://user-images.githubusercontent.com/49303407/173197064-ac24b824-a12b-4fff-80f6-c2752cc32b7c.png)

**桌面系统 (请填写下列信息):**

  
    CPU model : AMD EPYC 7K62 48-Core Processor
    Number of cores : 2
    CPU frequency : 2595.124 MHz
    Total amount of Mem : 3690 MB (394 MB Used)
    Total amount of Swap : 4095 MB (145 MB Used)
    System uptime : 71 days, 3 hour 54 min
    Load average : 0.02, 0.03, 0.00
    OS : Debian GNU/Linux 10
    Arch : x86_64 (64 Bit)
    Kernel : 4.19.0-18-amd64
    Installed QuickBox : 1.5.2

**Comment by Magic-glass** [comment]
已更新1.5.4
我好傻.jpg

**Comment by Magic-glass** [comment]
![MQ26NYN_IS MK%S3V77SY%O](https://user-images.githubusercontent.com/49303407/173199238-3eb5aa82-8fbf-437c-8186-415e4cc76fc0.png)
![(AL4FLRS~_B1SFA$VD_OWW2](https://user-images.githubusercontent.com/49303407/173199241-053ab979-d010-4286-80a2-e3f4ab1816b8.png)

在1.5.4版本中，“本月”的数据依旧异常ヘ(_ _ヘ)

**Comment by tautcony** [comment]
**在选择过去30天排序时**: 请提供`vnstat -d`与`vnstat -d --json`的输出结果

其他统计时间维度的，若有问题，请一并提供，对应参数参考如下

```
      -5,  --fiveminutes [limit]   show 5 minutes
      -h,  --hours [limit]         show hours
      -hg, --hoursgraph            show hours graph
      -d,  --days [limit]          show days
      -m,  --months [limit]        show months
      -y,  --years [limit]         show years
      -t,  --top [limit]           show top days
```

**Comment by Magic-glass** [comment]
这是过去12个月的排序，“本月”显示为了盒子开始运行的3月
![图片](https://user-images.githubusercontent.com/49303407/173225461-9aa6b2d5-c026-4cb8-8c3a-39b74ecc7797.png)

这是过去24小时的排序，似乎是没有区分好昨天和今天？
![图片](https://user-images.githubusercontent.com/49303407/173225905-6a69afae-a65e-43c3-adaf-89fa4ba4a46c.png)

辛苦大佬了

**Comment by tautcony** [comment]
另一个命令执行输出原始数据，提供一下，截图这边没法测试…

**Comment by Magic-glass** [comment]
<details>
<summary>vnatat -m --json</summary>

`{"vnstatversion":"1.18","jsonversion":"1","interfaces":[{"id":"eth0","nick":"eth0","created":{"date":{"year":2022,"month":3,"day":3}},"updated":{"date":{"year":2022,"month":6,"day":13},"time":{"hour":21,"minutes":27}},"traffic":{"total":{"rx":985745996,"tx":981804653},"days":[{"id":0,"date":{"year":2022,"month":6,"day":13},"rx":1349438,"tx":1590546},{"id":1,"date":{"year":2022,"month":6,"day":12},"rx":945928,"tx":12467679},{"id":2,"date":{"year":2022,"month":6,"day":11},"rx":846531,"tx":21703883},{"id":3,"date":{"year":2022,"month":6,"day":10},"rx":432197,"tx":5770976},{"id":4,"date":{"year":2022,"month":6,"day":9},"rx":1529183,"tx":11083683},{"id":5,"date":{"year":2022,"month":6,"day":8},"rx":514488,"tx":7290262},{"id":6,"date":{"year":2022,"month":6,"day":7},"rx":526774,"tx":6489058},{"id":7,"date":{"year":2022,"month":6,"day":6},"rx":3209285,"tx":4716217},{"id":8,"date":{"year":2022,"month":6,"day":5},"rx":1129741,"tx":3025516},{"id":9,"date":{"year":2022,"month":6,"day":4},"rx":432276,"tx":905945},{"id":10,"date":{"year":2022,"month":6,"day":3},"rx":758487,"tx":8030220},{"id":11,"date":{"year":2022,"month":6,"day":2},"rx":437812,"tx":2877403},{"id":12,"date":{"year":2022,"month":6,"day":1},"rx":2047448,"tx":3088468},{"id":13,"date":{"year":2022,"month":5,"day":31},"rx":378829,"tx":1944078},{"id":14,"date":{"year":2022,"month":5,"day":30},"rx":364937,"tx":2045672},{"id":15,"date":{"year":2022,"month":5,"day":29},"rx":1743827,"tx":3012550},{"id":16,"date":{"year":2022,"month":5,"day":28},"rx":1624830,"tx":3414327},{"id":17,"date":{"year":2022,"month":5,"day":27},"rx":1883253,"tx":3277307},{"id":18,"date":{"year":2022,"month":5,"day":26},"rx":1904484,"tx":2895329},{"id":19,"date":{"year":2022,"month":5,"day":25},"rx":1810984,"tx":3854409},{"id":20,"date":{"year":2022,"month":5,"day":24},"rx":368209,"tx":2633774},{"id":21,"date":{"year":2022,"month":5,"day":23},"rx":2832230,"tx":3650620},{"id":22,"date":{"year":2022,"month":5,"day":22},"rx":371843,"tx":2756219},{"id":23,"date":{"year":2022,"month":5,"day":21},"rx":459663,"tx":2002209},{"id":24,"date":{"year":2022,"month":5,"day":20},"rx":351209,"tx":2112751},{"id":25,"date":{"year":2022,"month":5,"day":19},"rx":974763,"tx":11550503},{"id":26,"date":{"year":2022,"month":5,"day":18},"rx":1047213,"tx":2957183},{"id":27,"date":{"year":2022,"month":5,"day":17},"rx":1590561,"tx":1222063},{"id":28,"date":{"year":2022,"month":5,"day":16},"rx":255029,"tx":796227},{"id":29,"date":{"year":2022,"month":5,"day":15},"rx":1821850,"tx":14331599}],"months":[{"id":0,"date":{"year":2022,"month":6},"rx":14159588,"tx":89039856},{"id":1,"date":{"year":2022,"month":5},"rx":51151292,"tx":164336024},{"id":2,"date":{"year":2022,"month":4},"rx":58811201,"tx":268375357},{"id":3,"date":{"year":2022,"month":3},"rx":861623915,"tx":460053416}],"tops":[{"id":0,"date":{"year":2022,"month":3,"day":7},"time":{"hour":0,"minutes":0},"rx":257814129,"tx":20600657},{"id":1,"date":{"year":2022,"month":3,"day":3},"time":{"hour":18,"minutes":26},"rx":153019863,"tx":9898709},{"id":2,"date":{"year":2022,"month":3,"day":11},"time":{"hour":0,"minutes":0},"rx":77242526,"tx":40867495},{"id":3,"date":{"year":2022,"month":3,"day":4},"time":{"hour":0,"minutes":0},"rx":79511568,"tx":35761932},{"id":4,"date":{"year":2022,"month":3,"day":6},"time":{"hour":0,"minutes":0},"rx":92129468,"tx":14662315},{"id":5,"date":{"year":2022,"month":3,"day":8},"time":{"hour":0,"minutes":0},"rx":39111423,"tx":47943471},{"id":6,"date":{"year":2022,"month":3,"day":9},"time":{"hour":0,"minutes":0},"rx":54746808,"tx":25284482},{"id":7,"date":{"year":2022,"month":4,"day":27},"time":{"hour":0,"minutes":0},"rx":23930139,"tx":27577903},{"id":8,"date":{"year":2022,"month":3,"day":24},"time":{"hour":0,"minutes":0},"rx":9855281,"tx":35647617},{"id":9,"date":{"year":2022,"month":3,"day":10},"time":{"hour":0,"minutes":0},"rx":3244821,"tx":34268549}],"hours":[{"id":0,"date":{"year":2022,"month":6,"day":13},"rx":21559,"tx":247962},{"id":1,"date":{"year":2022,"month":6,"day":13},"rx":12078,"tx":15428},{"id":2,"date":{"year":2022,"month":6,"day":13},"rx":12678,"tx":14530},{"id":3,"date":{"year":2022,"month":6,"day":13},"rx":11269,"tx":12061},{"id":4,"date":{"year":2022,"month":6,"day":13},"rx":14022,"tx":14609},{"id":5,"date":{"year":2022,"month":6,"day":13},"rx":22993,"tx":24267},{"id":6,"date":{"year":2022,"month":6,"day":13},"rx":28037,"tx":28078},{"id":7,"date":{"year":2022,"month":6,"day":13},"rx":17261,"tx":17944},{"id":8,"date":{"year":2022,"month":6,"day":13},"rx":20065,"tx":19167},{"id":9,"date":{"year":2022,"month":6,"day":13},"rx":940602,"tx":178470},{"id":10,"date":{"year":2022,"month":6,"day":13},"rx":28575,"tx":114413},{"id":11,"date":{"year":2022,"month":6,"day":13},"rx":25158,"tx":118751},{"id":12,"date":{"year":2022,"month":6,"day":13},"rx":22645,"tx":143884},{"id":13,"date":{"year":2022,"month":6,"day":13},"rx":25076,"tx":109872},{"id":14,"date":{"year":2022,"month":6,"day":13},"rx":19475,"tx":58615},{"id":15,"date":{"year":2022,"month":6,"day":13},"rx":15623,"tx":96253},{"id":16,"date":{"year":2022,"month":6,"day":13},"rx":18895,"tx":113079},{"id":17,"date":{"year":2022,"month":6,"day":13},"rx":16639,"tx":40016},{"id":18,"date":{"year":2022,"month":6,"day":13},"rx":19421,"tx":50553},{"id":19,"date":{"year":2022,"month":6,"day":13},"rx":24697,"tx":26336},{"id":20,"date":{"year":2022,"month":6,"day":13},"rx":18593,"tx":17091},{"id":21,"date":{"year":2022,"month":6,"day":13},"rx":14077,"tx":129167},{"id":22,"date":{"year":2022,"month":6,"day":12},"rx":18784,"tx":150739},{"id":23,"date":{"year":2022,"month":6,"day":12},"rx":313014,"tx":196133}]}}]}
`
</details>

<details>
<summary>vnatat -h --json</summary>
{"vnstatversion":"1.18","jsonversion":"1","interfaces":[{"id":"eth0","nick":"eth0","created":{"date":{"year":2022,"month":3,"day":3}},"updated":{"date":{"year":2022,"month":6,"day":13},"time":{"hour":21,"minutes":32}},"traffic":{"total":{"rx":985748867,"tx":981808508},"days":[{"id":0,"date":{"year":2022,"month":6,"day":13},"rx":1352309,"tx":1594401},{"id":1,"date":{"year":2022,"month":6,"day":12},"rx":945928,"tx":12467679},{"id":2,"date":{"year":2022,"month":6,"day":11},"rx":846531,"tx":21703883},{"id":3,"date":{"year":2022,"month":6,"day":10},"rx":432197,"tx":5770976},{"id":4,"date":{"year":2022,"month":6,"day":9},"rx":1529183,"tx":11083683},{"id":5,"date":{"year":2022,"month":6,"day":8},"rx":514488,"tx":7290262},{"id":6,"date":{"year":2022,"month":6,"day":7},"rx":526774,"tx":6489058},{"id":7,"date":{"year":2022,"month":6,"day":6},"rx":3209285,"tx":4716217},{"id":8,"date":{"year":2022,"month":6,"day":5},"rx":1129741,"tx":3025516},{"id":9,"date":{"year":2022,"month":6,"day":4},"rx":432276,"tx":905945},{"id":10,"date":{"year":2022,"month":6,"day":3},"rx":758487,"tx":8030220},{"id":11,"date":{"year":2022,"month":6,"day":2},"rx":437812,"tx":2877403},{"id":12,"date":{"year":2022,"month":6,"day":1},"rx":2047448,"tx":3088468},{"id":13,"date":{"year":2022,"month":5,"day":31},"rx":378829,"tx":1944078},{"id":14,"date":{"year":2022,"month":5,"day":30},"rx":364937,"tx":2045672},{"id":15,"date":{"year":2022,"month":5,"day":29},"rx":1743827,"tx":3012550},{"id":16,"date":{"year":2022,"month":5,"day":28},"rx":1624830,"tx":3414327},{"id":17,"date":{"year":2022,"month":5,"day":27},"rx":1883253,"tx":3277307},{"id":18,"date":{"year":2022,"month":5,"day":26},"rx":1904484,"tx":2895329},{"id":19,"date":{"year":2022,"month":5,"day":25},"rx":1810984,"tx":3854409},{"id":20,"date":{"year":2022,"month":5,"day":24},"rx":368209,"tx":2633774},{"id":21,"date":{"year":2022,"month":5,"day":23},"rx":2832230,"tx":3650620},{"id":22,"date":{"year":2022,"month":5,"day":22},"rx":371843,"tx":2756219},{"id":23,"date":{"year":2022,"month":5,"day":21},"rx":459663,"tx":2002209},{"id":24,"date":{"year":2022,"month":5,"day":20},"rx":351209,"tx":2112751},{"id":25,"date":{"year":2022,"month":5,"day":19},"rx":974763,"tx":11550503},{"id":26,"date":{"year":2022,"month":5,"day":18},"rx":1047213,"tx":2957183},{"id":27,"date":{"year":2022,"month":5,"day":17},"rx":1590561,"tx":1222063},{"id":28,"date":{"year":2022,"month":5,"day":16},"rx":255029,"tx":796227},{"id":29,"date":{"year":2022,"month":5,"day":15},"rx":1821850,"tx":14331599}],"months":[{"id":0,"date":{"year":2022,"month":6},"rx":14162459,"tx":89043711},{"id":1,"date":{"year":2022,"month":5},"rx":51151292,"tx":164336024},{"id":2,"date":{"year":2022,"month":4},"rx":58811201,"tx":268375357},{"id":3,"date":{"year":2022,"month":3},"rx":861623915,"tx":460053416}],"tops":[{"id":0,"date":{"year":2022,"month":3,"day":7},"time":{"hour":0,"minutes":0},"rx":257814129,"tx":20600657},{"id":1,"date":{"year":2022,"month":3,"day":3},"time":{"hour":18,"minutes":26},"rx":153019863,"tx":9898709},{"id":2,"date":{"year":2022,"month":3,"day":11},"time":{"hour":0,"minutes":0},"rx":77242526,"tx":40867495},{"id":3,"date":{"year":2022,"month":3,"day":4},"time":{"hour":0,"minutes":0},"rx":79511568,"tx":35761932},{"id":4,"date":{"year":2022,"month":3,"day":6},"time":{"hour":0,"minutes":0},"rx":92129468,"tx":14662315},{"id":5,"date":{"year":2022,"month":3,"day":8},"time":{"hour":0,"minutes":0},"rx":39111423,"tx":47943471},{"id":6,"date":{"year":2022,"month":3,"day":9},"time":{"hour":0,"minutes":0},"rx":54746808,"tx":25284482},{"id":7,"date":{"year":2022,"month":4,"day":27},"time":{"hour":0,"minutes":0},"rx":23930139,"tx":27577903},{"id":8,"date":{"year":2022,"month":3,"day":24},"time":{"hour":0,"minutes":0},"rx":9855281,"tx":35647617},{"id":9,"date":{"year":2022,"month":3,"day":10},"time":{"hour":0,"minutes":0},"rx":3244821,"tx":34268549}],"hours":[{"id":0,"date":{"year":2022,"month":6,"day":13},"rx":21559,"tx":247962},{"id":1,"date":{"year":2022,"month":6,"day":13},"rx":12078,"tx":15428},{"id":2,"date":{"year":2022,"month":6,"day":13},"rx":12678,"tx":14530},{"id":3,"date":{"year":2022,"month":6,"day":13},"rx":11269,"tx":12061},{"id":4,"date":{"year":2022,"month":6,"day":13},"rx":14022,"tx":14609},{"id":5,"date":{"year":2022,"month":6,"day":13},"rx":22993,"tx":24267},{"id":6,"date":{"year":2022,"month":6,"day":13},"rx":28037,"tx":28078},{"id":7,"date":{"year":2022,"month":6,"day":13},"rx":17261,"tx":17944},{"id":8,"date":{"year":2022,"month":6,"day":13},"rx":20065,"tx":19167},{"id":9,"date":{"year":2022,"month":6,"day":13},"rx":940602,"tx":178470},{"id":10,"date":{"year":2022,"month":6,"day":13},"rx":28575,"tx":114413},{"id":11,"date":{"year":2022,"month":6,"day":13},"rx":25158,"tx":118751},{"id":12,"date":{"year":2022,"month":6,"day":13},"rx":22645,"tx":143884},{"id":13,"date":{"year":2022,"month":6,"day":13},"rx":25076,"tx":109872},{"id":14,"date":{"year":2022,"month":6,"day":13},"rx":19475,"tx":58615},{"id":15,"date":{"year":2022,"month":6,"day":13},"rx":15623,"tx":96253},{"id":16,"date":{"year":2022,"month":6,"day":13},"rx":18895,"tx":113079},{"id":17,"date":{"year":2022,"month":6,"day":13},"rx":16639,"tx":40016},{"id":18,"date":{"year":2022,"month":6,"day":13},"rx":19421,"tx":50553},{"id":19,"date":{"year":2022,"month":6,"day":13},"rx":24697,"tx":26336},{"id":20,"date":{"year":2022,"month":6,"day":13},"rx":18593,"tx":17091},{"id":21,"date":{"year":2022,"month":6,"day":13},"rx":16948,"tx":133022},{"id":22,"date":{"year":2022,"month":6,"day":12},"rx":18784,"tx":150739},{"id":23,"date":{"year":2022,"month":6,"day":12},"rx":313014,"tx":196133}]}}]}

**Comment by tautcony** [comment]
相关内容已经在`development`分支中修正。
