### ISSUE TITLE
qBittorrent在面板中无法启动

### ISSUE THREAD

**Issue by wohaocaiji** [amefs/quickbox-lite#156]
没有用一键脚本，那个总是乱码，用的是git clong以后setup的方式安装，TUI界面选了安装qB，安装完成后面板里不管怎么开关都无法启动qB。于是看了看最新的源码，在`installpackage-qbittorrent.sh`的822行服务文件命名为`qbittorrent@.service`，似乎少了`${username}`，修正文件名以后依然没法启动，不太清楚服务为什么启动不了也懒得折腾了，特来提个issue坐等大佬修复🤣

**Comment by amefs** [comment]
请你提供安装的系统版本，并将 `/root/quickbox.$PPID.log` 文件作为附件上传

**Comment by wohaocaiji** [comment]
系统是Debian 10
附件如下
[quickbox.420.log](https://github.com/amefs/quickbox-lite/files/8978370/quickbox.420.log)

**Comment by amefs** [comment]
建议直接重新安装 qbittorrent 即可，面板或者 `box` 命令均可。比较有可能是安装过程出现网络波动，没有下载到 qBittorrent 的可执行文件。

**Comment by wohaocaiji** [comment]
> 建议直接重新安装 qbittorrent 即可，面板或者 `box` 命令均可。比较有可能是安装过程出现网络波动，没有下载到 qBittorrent 的可执行文件。

可执行文件是有的，用命令行`qbittorrent-nox -d`是可以启动的，`--webui-port`如果和box的配置一致的话也能通过面板打开，但是服务那里依然是红的，而且这样启动的qB配置不是按box写好的配置文件来，都是默认配置。
我先试试重装qB。

**Comment by amefs** [comment]
请你查看一下 `/home/${username}/.config/qBittorrent/qBittorrent.conf` 是否有正确的端口号，用户名以及密码。

quickbox 安装的 qbittorrent 是以用户权限运行的，如果使用 root 权限运行，由于 root 用户不具有相应的配置文件，均回滚到默认值。如果配置文件的权限有问题也可能出现无法启动的情况。

`qbittorrent@.service` 是正确的服务名称，在使用 `systemctl start qbittorrent@${username}.service` 调用时，会向该服务传入`${username}` 作为用户名参数。

**Comment by wohaocaiji** [comment]
谢谢提醒，更换用户之后可以用命令行按box的配置启动了，启动之后面板也能看到服务状态的变化，不过面板的服务开关还是不好使，倒是没什么影响，暂且就这么用着吧
再次感谢！
