### ISSUE TITLE
希望集成一个WEBDAV 工具，方便挂载

### ISSUE THREAD

**Issue by tanpengsccd** [amefs/quickbox-lite#158]
**请描述您请求的功能**
希望集成一个WEBDAV 工具，方便挂载
**描述您想要的解决方案**

1. Docker 集成Ngixn Webdav。
2. 手动安装方式：https://github.com/studio-b12/gowebdav

**Comment by amefs** [comment]
目前使用默认安装的 Nginx 是可以设置 webdav 的，但缺点是只能使用 Nginx 进程的账户权限操作 (www-data)。其他方案我需要做一些调研以确定一个合适的服务端。

**Comment by amefs** [comment]
目前计划使用 Rclone 作为后端实现该功能，将在下个版本提供。

**Comment by amefs** [comment]
v1.5.5 已完成支持

**Comment by tanpengsccd** [comment]
请问 这个也可以作为服务端 被连接吗？

**Comment by amefs** [comment]
我在这里实现的是服务端功能，客户端可以用 Rclone 完成。

**Comment by tanpengsccd** [comment]
感谢回答

amefs ***@***.***>于2022年7月20日 周三18:07写道：
