### ISSUE TITLE
Deluge version chosen

### ISSUE THREAD

**Issue by gchigoo** [amefs/quickbox-lite#16]
So far from developer branch just can install the Deluge 1.3.5

**Comment by amefs** [comment]
在 Dashboard 中，暂时无法提供 Deluge 2.0.x 的选项，仅能通过 CLI 安装 (需要 ROOT 权限)：
` box install deluge --de 2.0.3`

**Comment by gchigoo** [comment]
> 在 Dashboard 中，暂时无法提供 Deluge 2.0.x 的选项，仅能通过 CLI 安装 (需要 ROOT 权限)：
> ` box install deluge --de 2.0.3`

Thanks
