### ISSUE TITLE
transmission-web-control失效

### ISSUE THREAD

**Issue by Magic-glass** [amefs/quickbox-lite#163]
**描述 Bug**
应该是1.5.4升级到1.5.5之后失效的，今天才发现
现在打开页面显示的是transmission-web-interface
要怎么恢复呢，如果重装的话要怎么备份？

**Comment by amefs** [comment]
尝试一下覆盖安装 transmission-web-control：
```
echo 1 | bash -c "$(wget -qO- https://github.com/ronggang/transmission-web-control/raw/master/release/install-tr-control.sh)"
```

**Comment by Magic-glass** [comment]
已经恢复，谢谢ヘ(_ _ヘ)
失效之后我检查过nginx配置，也重启过服务，日志也没发现异常
可能问题出现杂在web文件上吧
