### ISSUE TITLE
V1.5.5  deluge升级2.0.3后无法启动

### ISSUE THREAD

**Issue by huanxiangyixia** [amefs/quickbox-lite#167]
**描述 Bug**
V1.5.5  deluge升级2.0.3后无法启动，默认安装的1.3.15版本正常，卸载deluge重新安装后是1.3.15也可以正常使用

**重现 Bug**
可以重现该 Bug 的操作 (或命令)：

对服务器online 3欧进行DD重装debian 10系统后，依旧会出现该现象，另一台数月前安装的3欧是V1.5.4版本可以正常升级deluge！

**期望的结果**
如果想装回V1.5.4版本需要用什么命令安装呢？

**截图** (可选)
![image](https://user-images.githubusercontent.com/54071554/189478957-864afb19-9196-470f-94b4-102244b8a919.png)

---

**附加内容**
此处添加其他附加信息。

 - 操作系统: debian10
 - 当前版本 V1.5.5
 - 执行的命令 (如果有)  box update deluge

**Comment by amefs** [comment]
已查明原因：deluge 2.0.3 的依赖 cryptography 在 9月6日有一次版本升级，造成依赖损坏。
修复补丁将在测试后在 Development 通道发布。
