### ISSUE TITLE
请问为什么我没有下载和上传任务，但是web上一直显示在下载上传啊？

### ISSUE THREAD

**Issue by kaiant924** [amefs/quickbox-lite#170]
**描述 Bug**
简单明了的描述 Bug

**重现 Bug**
可以重现该 Bug 的操作 (或命令)：
![捕获](https://user-images.githubusercontent.com/90315803/200127789-ea1632ca-fbd8-4918-aca4-6d7fd7b83f49.PNG)

1. 转到 '...' 页面
2. 点击 '....'
3. 下拉到 '....'
4. 出现错误

**期望的结果**
简单明了的描述一下你期望的表现。

**截图** (可选)
如果你有合适的截图，在此处添加，他将会帮助你解释问题。你也可以创建一个表格来描述你的信息，这是一个 [在线的表格 markdown 代码生成器](https://www.tablesgenerator.com/markdown_tables).

---

**附加内容**
此处添加其他附加信息。

**桌面系统 (请填写下列信息):**

 - 操作系统: [例如 iOS]
 - 浏览器 [例如 chrome, safari]
 - 版本 [例如 22]
 - 执行的命令 (如果有) [例如 `box update quickbox`]

**智能手机 (请填写下列信息):**

 - 设备: [例如. iPhone6]
 - 操作系统: [例如. iOS8.1]
 - 浏览器 [例如 stock browser, safari]
 - 版本 [例如 22]

**Comment by amefs** [comment]
你打开的面板本身就会会占用流量，如果没有流量就不可能看到你的服务器状态啊。

**Comment by kaiant924** [comment]
明白，谢谢解答！
