### ISSUE TITLE
qBttorrent使用端口访问  无法修改配置

### ISSUE THREAD

**Issue by singworld** [amefs/quickbox-lite#175]
**描述 Bug**
WEB UI 修改为 0.0.0.0 使用端口访问  无法修改配置
点击保存提示
无法保存程序偏好选项，可能是无法连接到 qBttorrent。
/api/v2/app/setPreferences  502 Bad Gateway

**重现 Bug**
qbittorrent 如下连接访问正常
https://ip/qbittorrent/

WEB UI 修改为 0.0.0.0 使用端口访问 页面正常显示
修改设置的时候，大概10秒后响应 提示 无法保存程序偏好选项，可能是无法连接到 qBttorrent。
/api/v2/app/setPreferences  502 Bad Gateway

已勾选
使用我的路由器的 UPnP / NAT-PMP 功能来转发端口
已取消
启用“点击劫持”保护
 启用跨站请求伪造 (CSRF) 保护

尝试过重装和在别的机器装，遇到同样问题

**期望的结果**
可以配置和添加种子
这种方式 https://ip/qbittorrent/，在一些插件 无法连接和使用

**截图**
![image](https://user-images.githubusercontent.com/37404619/207580251-5a918687-5dd6-47b6-9efa-805502288d88.png)

**Comment by singworld** [comment]
> 请注意一下，不要修改端口，修改端口号可以导致你看到的问题。

我没有修改端口
我尝试通过nginx反代  http协议依然无法 修改
使用https协议后可以成功修改

**Comment by singworld** [comment]
我使用不同服务商的vps 均出现这个问题

**Comment by singworld** [comment]
版本 V1.5.6

**Comment by tautcony** [comment]
F12中，提示502的完整请求url是什么呢

**Comment by singworld** [comment]
https://ip/qbittorrent/api/v2/app/setPreferences 正常
http://ip:15191/api/v2/app/setPreferences 502
https://domain/api/v2/app/setPreferences 正常

**Comment by amefs** [comment]
请你运行一下 `netstat -tnlp | grep ":15191"` 查看该端口的监听情况

**Comment by singworld** [comment]
```
$ netstat -tnlp | grep ":15191"
tcp        0      0 0.0.0.0:15191           0.0.0.0:*               LISTEN      2817/qbittorrent-no
```

**Comment by amefs** [comment]
看起来你的 qbittorrent 已经正常监听 0.0.0.0
接下来请你分别运行如下指令：
- 通过 https 访问
  ```bash
  curl -i -k https://用户名:密码@ip/qbittorrent/api/v2/torrents/info
  ```
- 通过端口访问
  ```bash
  curl -i --header 'Referer: http://ip:端口' --data 'username=用户名&password=密码' http://ip:端口/api/v2/auth/login
  ```
  将返回值中的 `SID=hBc7TxF76ERhvIw0jQQ4LZ7Z1jQUV0tQ` 形式的 cookies 记录下来，然后运行：
  ```bash
  curl -i http://ip:端口/api/v2/torrents/info --cookie "SID=你得到的 cookies"
  ```
你可以将测试结果用***替代隐去私密信息后回复。

**Comment by singworld** [comment]
通过 https 访问
curl -i -k https://用户名:密码@ip/qbittorrent/api/v2/torrents/info
```
HTTP/1.1 200 OK
Server: nginx
Date: Thu, 15 Dec 2022 13:05:51 GMT
Content-Type: application/json
Content-Length: 2
Connection: keep-alive
content-security-policy: default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; script-src 'self' 'unsafe-inline'; object-src 'none'; form-action 'self';
referrer-policy: same-origin
set-cookie: SID=JT4B+vV7rWe0ymPFfeW55gvsd1yIZ8QX; HttpOnly; path=/
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
X-Frame-Options: SAMEORIGIN

```
---------

通过端口访问
curl -i --header 'Referer: http://ip:端口' --data 'username=用户名&password=密码' http://ip:端口/api/v2/auth/login
```
HTTP/1.1 200 OK
connection: keep-alive
content-length: 3
content-security-policy: default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; script-src 'self' 'unsafe-inline'; object-src 'none'; form-action 'self';
content-type: text/plain; charset=UTF-8
date: Thu, 15 Dec 2022 13:06:52 GMT
referrer-policy: same-origin
set-cookie: SID=L90PgfAS0ehOpJ5s6jG9zFEgbhNHQj89; HttpOnly; path=/
x-content-type-options: nosniff
x-xss-protection: 1; mode=block


````
---------
将返回值中的 SID=hBc7TxF76ERhvIw0jQQ4LZ7Z1jQUV0tQ 形式的 cookies 记录下来，然后运行：
curl -i http://ip:端口/api/v2/torrents/info --cookie "SID=你得到的 cookies"
```
HTTP/1.1 200 OK
connection: keep-alive
content-length: 2
content-security-policy: default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; script-src 'self' 'unsafe-inline'; object-src 'none'; form-action 'self';
content-type: application/json
date: Thu, 15 Dec 2022 13:07:46 GMT
referrer-policy: same-origin
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
```

**Comment by tautcony** [comment]
看返回，ip端口请求的接口返回确实是由qbittorrent直接提供的，由于这类查询接口与设置保存接口差别几乎只在payload，怀疑你的服务器上或是提供商是否有额外的防火墙设置。

### 从访问的机器请求空配置文件，请求形如下

```shell
curl --location --request POST 'http://ip:port/api/v2/app/setPreferences' \
--header 'Cookie: SID=这里填Cookie' \
--form 'json="{}"'
```

### 在F12中右键对应的请求并获取命令，从服务器终端重放报错的请求：

<img width="460" alt="image" src="https://user-images.githubusercontent.com/8295052/207871534-a544416f-4d0c-4db5-bcdf-c46eab745029.png">

其参数的`--data-raw`可能需要修改为`--data`

#### 若直接重放请求依然报错，将该请求的ip调整为127.0.0.1再重试一次

**Comment by singworld** [comment]
找到原因了  因为代理的原因
刚好走到的规则节点 HTTP 提交会502
更换节点 或者换为https 就可以了
麻烦了，谢谢
