### ISSUE TITLE
安装证书的问题

### ISSUE THREAD

**Issue by marcushsu** [amefs/quickbox-lite#176]
acme.sh 默认使用 ZeroSSL 做发证机构，但是问题颇多，我在HZ的盒子就一直超时拿不到证书。
参考[官方说明](https://github.com/acmesh-official/acme.sh/wiki/Change-default-CA-to-ZeroSSL)，我在脚本
/usr/local/bin/quickbox/package/install/installpackage-lecert 
加上一行：
./acme.sh --set-default-ca --server letsencrypt
（在 ./acme.sh --register-account -m domain@example.com >>"${OUTTO}" 2>&1 之后）
问题迎刃而解。

**Comment by amefs** [comment]
已添加允许使用 letsencrypt ca 的选项。
