### ISSUE TITLE
FBE和File Browser都不能上本地文件

### ISSUE THREAD

**Issue by lengdong863** [amefs/quickbox-lite#177]
FBE和File Browser都不能上文件
![微信截图_20221221221739](https://user-images.githubusercontent.com/46510506/208918101-f2b5a09b-7436-4e40-8101-9478d3172bcf.jpg)
报错都一样。
系统版本信息：ubuntu-22.04 64bit
QuickBox V1.5.6

**Comment by amefs** [comment]
请你在修改 `/etc/nginx/apps/filebrowser.conf` 以解除限制，这是因为你的文件尺寸超过了全局默认值。
```
location /filebrowser {
  return 301 /filebrowser/;
}

location /filebrowser/ {
  client_max_body_size 0;
  auth_basic "Password Required";
  auth_basic_user_file /etc/htpasswd.d/htpasswd.$remote_user;
  rewrite ^/filebrowser/(.*) /$1 break;
  proxy_pass http://$remote_user.filebrowser;
}
```
随后运行 `nginx -s reload`

**Comment by lengdong863** [comment]
![捕获](https://user-images.githubusercontent.com/46510506/209040967-05a607cb-97b2-4bd5-b5e5-08c08f69bcde.JPG)

nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/etc/ssl/certs/ssl-cert-snakeoil.pem"

**Comment by amefs** [comment]
这只是警告，默认使用自签证书就会有，不影响使用。安装 lecert 或者正常的证书就可以解除。

**Comment by lengdong863** [comment]
我这边查看了/etc/nginx/apps/filebrowser.conf，这个文件，已经修改成功了。但是还是会有同样的提示。
我先用Xftp 7替代吧。
