### ISSUE TITLE
Transmission打开时UI不一样

### ISSUE THREAD

**Issue by lengdong863** [amefs/quickbox-lite#178]
Transmission打开时，会切换到不同UI。
没有手动点过切换的按钮。
尝试在地址栏修改，也无法还原。

**Comment by amefs** [comment]
如果你看到的是 [transmission-web-control](https://github.com/ronggang/transmission-web-control)  说明安装正确，切换原版 UI 在右上角。

**Comment by lengdong863** [comment]
重新安装后可以看到transmission-web-control的界面，但是在过一段时间过后（大概半天），就会变成下图这样。
![捕获1](https://user-images.githubusercontent.com/46510506/209042140-54197edd-f585-4f71-99c8-8efbfc760053.JPG)
然后就变不回来了。找遍了所以地方都找不到切换的按钮。
可以通过修改域名：https://XX.XX.XX.XX/transmission/web/index.mobile.html  改为移动版UI。
但是在移动版UI下，点击“桌面UI”，也切换不回来。
![image](https://user-images.githubusercontent.com/46510506/209042999-32931b42-ecfd-480d-b886-8172725e162d.png)

**Comment by amefs** [comment]
请你更新到 `development` 分支，重新安装 transmission，猜测是系统更新将 transmission 覆盖安装。`development` 分支新增了安装包锁定，应该可以解决问题。

**Comment by lengdong863** [comment]
好的，我试一试。
