### ISSUE TITLE
组件管理中心的应用怎么更新？

### ISSUE THREAD

**Issue by lengdong863** [amefs/quickbox-lite#179]
请问一下，组件管理中心的应用怎么更新啊？
例如：File Browser Enhanced V2.9.4
最新版本为v2.23.0 。

系统版本：ubuntu-22.04 64bit
[quickbox-lite] v1.5.6

尝试用box update file browser enhanced更新。
返回的结果是：
✗ file Updater not exist

QuickBox Lite Cli Tools

Usage: 
box update PACKAGE

Available updater:

deluge
filebrowser
filebrowser-ee
flexget
netdata
qbittorrent
rtorrent
rutorrent

——————————
用box update filebrowser-ee更新
结果：
File Browser Enhanced will now be updated.

This process may take a few minutes
Please wait until the process is completed

➜ Updating File Browser Enhanced...
✓ File Browser Enhanced is now update to date.

打开后，还是V2.9.4。

**Comment by amefs** [comment]
[File Browser Enhanced](https://hub.docker.com/r/80x86/filebrowser/tags) 最新版本就是 v2.9.4。

**Comment by lengdong863** [comment]
抱歉，是我没有搞清楚。
