### ISSUE TITLE
delugewebui 打开后一片空白

### ISSUE THREAD

**Issue by deemoartisan** [amefs/quickbox-lite#18]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots** (optical)
If applicable, add screenshots to help explain your problem. You can generate a table to describe your information, here is an [online table generator](https://www.tablesgenerator.com/markdown_tables).

---

**Additional context**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

安装最新版的box之后打开deluge的ui，一片空白，但是标题是正常的，安装qb尝试后是正常的。。求解

**Comment by amefs** [comment]
建议采取如下措施以确认问题：
1. 安装noVNC或者其他远程桌面应用
2. 在远程桌面中打开 Deluge 应用以确认服务是否工作正常，该操作可以确认 Deluge daemon 的工作状态
3. 使用远程桌面中的浏览器访问服务器面板，查看 Deluge WebUI 是否正常
