### ISSUE TITLE
RPC2

### ISSUE THREAD

**Issue by Hipoglos** [amefs/quickbox-lite#180]
Hi [amefs](https://github.com/amefs)! This is not a bug, but more a question about the implementation of rtorrent.
I've installed a dashboard for all my web applications (https://github.com/linuxserver/Heimdall) and it has the option to communicate with rtorrent via RPC2 to show stats on it. I know quickbox doesn't expose any port, so I'm wondering which would be the way to do it, without breaking quickbot lite. Sorry again for posting this here, but I don't know where I could ask for help.

Happy New Year!
Hipo,

**Comment by amefs** [comment]
Just need a scgi pass:
```
server {
    listen 8088;
    server_name _;

 location ^~ /RPC2 {
     include scgi_params;
     scgi_pass  unix:/var/run/${username}/.rtorrent.sock;
     #auth_basic "Password Required";
     #auth_basic_user_file /etc/htpasswd.d/htpasswd.${username};
 }
}
```
After reloading the config, you can access the xmlrpc via `http://IP:8088`
