### ISSUE TITLE
脚本卡在安装nginx-extras

### ISSUE THREAD

**Issue by ggh145** [amefs/quickbox-lite#181]
![AB85AC31-8843-4714-BC1D-67A40D4D470C](https://user-images.githubusercontent.com/97740510/210238659-b3d50b2b-8b76-408e-b7a7-bd9493cb8580.jpeg)
**描述 Bug**

佬，一建脚本安装卡住了，卡在安装nginx-extras，怎么解决呀？

**Comment by ggh145** [comment]
> ![AB85AC31-8843-4714-BC1D-67A40D4D470C](https://user-images.githubusercontent.com/97740510/210238659-b3d50b2b-8b76-408e-b7a7-bd9493cb8580.jpeg) **描述 Bug**
> 
> 佬，一建脚本安装卡住了，卡在安装nginx-extras，怎么解决呀？
>

**Comment by amefs** [comment]
请你把 root 下的 `quickbox.$PID.log` 文件最后大约20行回复在这里。

**Comment by ggh145** [comment]
> 请你把 root 下 `quickbox.$PID.log` 文件最后大约20行回复在这里。（macos `Cmd`+`Shift`+`4`可以选择区域截图）

dpkg: error processing package libnginx-mod-http-upstream-fair (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 nginx-common
 libnginx-mod-stream-geoip
 libnginx-mod-http-uploadprogress
 libnginx-mod-http-xslt-filter
 libnginx-mod-http-auth-pam
 libnginx-mod-http-geoip
 libnginx-mod-nchan
 libnginx-mod-http-cache-purge
 libnginx-mod-http-echo
 libnginx-mod-http-subs-filter
 libnginx-mod-http-perl
 libnginx-mod-http-geoip2
 nginx-extras
 libnginx-mod-stream-geoip2
 libnginx-mod-http-dav-ext
 libnginx-mod-mail
 libnginx-mod-http-fancyindex
 libnginx-mod-http-headers-more-filter
 libnginx-mod-http-image-filter
 libnginx-mod-stream
 libnginx-mod-http-upstream-fair
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by amefs** [comment]
请你尝试一下 `sudo apt-get -f install`，让 dpkg 重新配置一下这个包。

**Comment by ggh145** [comment]
![image](https://user-images.githubusercontent.com/97740510/210241675-bdb0f3a9-882e-45d5-b469-d7de5cd1f87f.jpg)

**Comment by ggh145** [comment]
然后呢？

**Comment by ggh145** [comment]
还是报错

**Comment by amefs** [comment]
你要不看一下`nginx`有没有正常安装/启动吧。`systemctl status nginx.service`

**Comment by ggh145** [comment]
> 你要不看一下`nginx`有没有正常安装/启动吧。`systemctl status nginx.service`

![448EF006-EF4E-414E-B305-4ACEA7E13C71](https://user-images.githubusercontent.com/97740510/210247395-e5c15ebb-3aef-4453-8344-5348a87bea87.jpeg)
死亡
 要怎么办

**Comment by amefs** [comment]
`netstat -tnlp | grep :80`

**Comment by amefs** [comment]
```
nginx -t
systemctl start nginx.service
systemctl status nginx.service
```
应该是系统有什么不太正常的地方导致 nginx 无法启动，手动将它启动再看看日志吧。

**Comment by ggh145** [comment]
> ```
> nginx -t
> systemctl start nginx.service
> systemctl status nginx.service
> ```
> 
> 
>      
>   
> 
> 应该是系统有什么不太正常的地方导致 nginx 无法启动，手动将它启动再看看日志吧。

nginx已经running ,运行脚本还是报错

**Comment by ggh145** [comment]
![image](https://user-images.githubusercontent.com/97740510/210291781-9ad09c5f-92c9-494a-a1bb-dd8ded641ed1.jpg)

**Comment by amefs** [comment]
借用一下[星菊的群](https://gist.github.com/Aniverse/cc885b91fb7c5d5139c3ffce7e28b0da)，进群以后找我。
