### ISSUE TITLE
rutorrent报错

### ISSUE THREAD

**Issue by lanxuewsr** [amefs/quickbox-lite#183]
打开rutorrent，报错如下：

> [23.01.2023 23:30:37] WebUI started.
[23.01.2023 23:30:40] Bad response from server: (500 [error,getplugins]) Internal Server Error

点击rutorrent的设置，也报错：

> [23.01.2023 23:31:21] JS error: [https://lw.17o.bid/rutorrent/js/webui.js : 861] TypeError: this.systemInfo is undefined

rtorrent运行正常。
用的是debian11的系统，其他软件正常。

非常感谢！

**Comment by lanxuewsr** [comment]
我把/srv/rutorrent/conf/users/XXX/config.php改成了

> //$scgi_port = 0;
//$scgi_host = "unix:///var/run/adpt/.rtorrent.sock";
$scgi_port = 5000;
$scgi_host = "127.0.0.1";

把/home/adpt/.rtorrent.rc改成了

> #network.scgi.open_local = /var/run/adpt/.rtorrent.sock
network.scgi.open_port = 127.0.0.1:5000


用5000端口通信，重启rtorrent后，问题依然存在。

**Comment by lanxuewsr** [comment]
我把/srv/rutorrent/conf/users/XXX/config.php改成了

>     //$scgi_port = 0;
    //$scgi_host = "unix:///var/run/adpt/.rtorrent.sock";
    $scgi_port = 5000;
    $scgi_host = "127.0.0.1";

把/home/adpt/.rtorrent.rc改成了

>     #network.scgi.open_local = /var/run/adpt/.rtorrent.sock
    network.scgi.open_port = 127.0.0.1:5000

用5000端口通信，重启rtorrent后，问题依然存在。

**Comment by lanxuewsr** [comment]
我把/srv/rutorrent/conf/users/XXX/config.php改成了

> //$scgi_port = 0;
//$scgi_host = "unix:///var/run/XXX/.rtorrent.sock";
$scgi_port = 5000;
$scgi_host = "127.0.0.1";


把/home/adpt/.rtorrent.rc改成了

> #network.scgi.open_local = /var/run/XXX/.rtorrent.sock
network.scgi.open_port = 127.0.0.1:5000


用5000端口通信，重启rtorrent后，问题依然存在。

**Comment by amefs** [comment]
麻烦你测试一下 [development](https://github.com/amefs/quickbox-lite/tree/development) 分支最新的补丁。

**Comment by lanxuewsr** [comment]
> 麻烦你测试一下 [development](https://github.com/amefs/quickbox-lite/tree/development) 分支最新的补丁。

试了下，现在运行正常了
拜谢大佬！ ^_^
