### ISSUE TITLE
ruTorrent stop working after upgrade

### ISSUE THREAD

**Issue by Hipoglos** [amefs/quickbox-lite#186]
After using "box update rutorrent" from console and ugprading from 3.10 to 4.02 rutorrent is not working anymore.

I tried to uninstalling the app and reinstalling from the dashboard, and still not working.

**Comment by amefs** [comment]
Have you tried the `development` branch? related commit 7d4b313fd0b82a9e23407c5472b5c625f85c0c50 .

**Comment by Hipoglos** [comment]
Hey amefs! Just tried, but now https://myip/rutorrent/ is showing: 404 Not Found. I think I will be not able to recover it.

I tried also:
`box update rutorrent

ruTorrent will now be updated.

This process may take a few minutes
Please wait until the process is completed

➜ Updating ruTorrent...
➜ Fetching v4.0.2
➜ Setting up plugins...
➜ Initializing ruTorrent plugins...
➜ Setting up configs for ruTorrent...
➜ Starting ruTorrent...
✓ ruTorrent is now update to date.
`
but not luck

**Comment by Hipoglos** [comment]
> Have you tried the `development` branch? related commit [7d4b313](https://github.com/amefs/quickbox-lite/commit/7d4b313fd0b82a9e23407c5472b5c625f85c0c50) .

It worked! Thanks!!
