### ISSUE TITLE
autodl-irssi 无法加载

### ISSUE THREAD

**Issue by 9191521** [amefs/quickbox-lite#187]
**描述 Bug**
因为主分支rutorrent 出现问题，切换到development分支，安装rtorrent,安装rutorrent，安装autodl-irssi（第一次装了很长时间，后来卸载重装问题依旧），打开rutorrent，出现以下提示：“autodl-irssi: __init2: ex: Exception info: No content elem with id autodl-prefs-contents-upload”

**重现 Bug**
切换到development分支，安装rtorrent,安装rutorrent，安装autodl-irssi，打开rutorrent

**桌面系统 (请填写下列信息):**

 - 操作系统: Ubuntu 18.04 LTS (The Bionic Beaver), 64 bits
 - 浏览器 ：chrome

https://s1.ax1x.com/2023/03/03/ppkXzon.png
https://s1.ax1x.com/2023/03/03/ppkXxds.png
https://s1.ax1x.com/2023/03/03/ppkXvZj.png

**Comment by amefs** [comment]
请尝试一下修补 2156ad15a8ffa2151bdc2db0e769dad5529e22eb 。 直接更新 `development` 分支，并重新安装 autodl-irssi 即可。

**Comment by 9191521** [comment]
solved thx
