### ISSUE TITLE
如果在VPS中安装了quickbox-lite，那可以安装其他Docker吗？

### ISSUE THREAD

**Issue by lengdong863** [amefs/quickbox-lite#188]
如果在VPS中安装了quickbox-lite，那可以继续在这个VPS里安装其他Docker吗？
安装后，会对硬盘里的文件造成损失吗？

**Comment by tautcony** [comment]
通常服务器上不存在所谓其他docker这一说法，只有一个docker，如果已经安装了如`filebrowser-ee`程序，那么quickbox-lite已经帮你在服务器上通过包管理工具apt安装好了docker，无需重复安装。

而下载、运行、使用其他的docker**镜像**，那么完全可以，没有关联性，并不构成影响。

需要指出的是，如果是网页应用类的，可能涉及到修改quickbox-lite使用的nginx配置以进行访问，需注意不影响到原有配置。

**Comment by lengdong863** [comment]
> 通常服务器上不存在所谓其他docker这一说法，只有一个docker，如果已经安装了如`filebrowser-ee`程序，那么quickbox-lite已经帮你在服务器上通过包管理工具apt安装好了docker，无需重复安装。
> 
> 而下载、运行、使用其他的docker**镜像**，那么完全可以，没有关联性，并不构成影响。
> 
> 需要指出的是，如果是网页应用类的，可能涉及到修改quickbox-lite使用的nginx配置以进行访问，需注意不影响到原有配置。

学习到了，感谢大佬的耐心解答！
