### ISSUE TITLE
监控面板数据不再更新

### ISSUE THREAD

**Issue by TitaniumLithium** [amefs/quickbox-lite#189]
**描述 Bug**
监控面板数据不再更新 实时网速为0 硬盘内存占用等数据无显示
V1.5.6

**重现 Bug**
可以重现该 Bug 的操作 (或命令)：

可能无法重现
好像是按照CF CDN proxy教程改了nginx sites-enable里的default配置后出现的
但是换回仅限dns 改回原配置 面板依旧不更新

**期望的结果**
恢复监控面板数据更新的方法

**截图** (可选)
![20230305171241](https://user-images.githubusercontent.com/48680707/222952755-e57456f1-707a-42f2-ba85-76743b929427.png)

---

**附加内容**
无

**桌面系统 (请填写下列信息):**

 - 操作系统: Ubuntu
 - 版本 20.04 focal
 - 执行的命令 (如果有)  通过quickbox下载flexget 但是安装报错 提示pyenv is running

**Comment by amefs** [comment]
这个一般来说是因为你的服务器特别卡，这个 atom 2 core 的机器显示出面板信息基本需要等 1分钟以上。如果有 BT 客户端在做种则时间可以更长。

**Comment by TitaniumLithium** [comment]
> 这个一般来说是因为你的服务器特别卡，这个 atom 2 core 的机器显示出面板信息基本需要等 1分钟以上。如果有 BT 客户端在做种则时间可以更长。

)当前基本没什么东西在运行
![20230305173927](https://user-images.githubusercontent.com/48680707/222953020-d00d7971-397b-400f-b7d9-c82748962493.png)

**Comment by amefs** [comment]
想要重置面板和 nginx 配置可以先更新 quickbox，然后卸载，安装 LECERT。

**Comment by TitaniumLithium** [comment]
原因就很迷。我是先备份好配置文件再进行修改的，还原配置则使用了备份的文件。虽然我提到了修改过nginx配置文件，但很可能真实原因与配置文件无关。

**Comment by tautcony** [comment]
那你打开F12的窗口并重新刷新页面观察一下，是否存在连接失败的请求。磁盘等状态信息通过websocket从后台获取，既然没有显示，可能是什么配置出问题导致ws连接无法建立。

**Comment by TitaniumLithium** [comment]
> 那你打开F12的窗口并重新刷新页面观察一下，是否存在连接失败的请求。磁盘等状态信息通过websocket从后台获取，既然没有显示，可能是什么配置出问题导致ws连接无法建立。

确实有失败的请求
`[ws] request failed, {key: 'NETWORK', pathName: '/widgets/net_status.php', success: false, message: 'AxiosError: Request failed with status code 404', response: ''}`

**Comment by TitaniumLithium** [comment]
> > 那你打开F12的窗口并重新刷新页面观察一下，是否存在连接失败的请求。磁盘等状态信息通过websocket从后台获取，既然没有显示，可能是什么配置出问题导致ws连接无法建立。
> 
> 确实有失败的请求 `[ws] request failed, {key: 'NETWORK', pathName: '/widgets/net_status.php', success: false, message: 'AxiosError: Request failed with status code 404', response: ''}`

自己用浏览器访问example.com/widgets/net_status.php可正常得到以下响应
`{"NetInputSpeed":[128061,149187,29806906,0,36899347088],"NetOutSpeed":[8574800,8575120,29806906,0,16923564928],"NetTimeStamp":1678017488.455133}`

**Comment by tautcony** [comment]
既然能获得响应，则应为后台服务无法通过`http://127.0.0.1/widgets/net_status.php`请求到相关数据以传输给前端。可以检查对应的配置是否影响到了这一通路。

正常应该是会被nginx的以下配置重定向到对应的url执行的
```
    location / {
      return 301 https://\$host\$request_uri;
    }
```

**Comment by TitaniumLithium** [comment]
已找到原因：
配置文件中
`default_server`不能省去 否则会影响重定向

之前配置frp老是跳转到监控面板所以删去了`default_server`
感谢协助
