### ISSUE TITLE
Can not install Let's Encrypt.

### ISSUE THREAD

**Issue by now163** [amefs/quickbox-lite#19]
安装时，已经设定好了hostname。
> box install lecert
✗ Domain not exist, exiting...

**Comment by amefs** [comment]
hostname 并不用于域名申请。安装 Let's Encrypt 时需要以如下形式输入命令:
```box install lecert -d DOMAIN```
对于多个域名可以多次附加 `-d DOMAIN`

**Comment by now163** [comment]
非常感谢。我就是找不到帮助文档。不知用啥参数。 直接加domain不行。。
建议在tips里写一下就好啦。

**Comment by amefs** [comment]
[这里](https://github.com/amefs/quickbox-lite/wiki/QuickBox-Lite-%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%B7%A5%E5%85%B7)是有写过，不过我考虑增加点帮助信息吧

**Comment by tautcony** [comment]
`box install lecert --help`能唤出帮助信息的。
