### ISSUE TITLE
art安装失败，提示failed to install pyenv

### ISSUE THREAD

**Issue by hanfly** [amefs/quickbox-lite#190]
Debian 11，安装art的时候提示以下信息，删除`/install/.install.lock`和`/opt/pyenv`之后重试，还是以下代码。请问大佬们这是什么原因怎么解决呢？
```
➜ Checking and performing updates to system... 
✓ System updated.
➜ Installing pyenv dependencies...
➜ Installing git... 
➜ Installing make... 
➜ Installing build-essential... 
➜ Installing libssl-dev... 
➜ Installing zlib1g-dev... 
➜ Installing libbz2-dev... 
➜ Installing libreadline-dev... 
➜ Installing libsqlite3-dev... 
➜ Installing wget... 
➜ Installing curl... 
➜ Installing llvm... 
➜ Installing libncursesw5-dev... 
➜ Installing xz-utils... 
➜ Installing tk-dev... 
➜ Installing libxml2-dev... 
➜ Installing libxmlsec1-dev... 
➜ Installing libffi-dev... 
➜ Installing liblzma-dev... 
✓ pyenv dependencies installed.
➜ Building pyenv...
✗ failed to install pyenv
➜ pyenv process running.
➜ If you believe this to be in error, please manually remove the /install/.install.lock
✗ Exiting...
```

**Comment by amefs** [comment]
pyenv 上游在两周前的改动导致了这个问题，目前已经在 `development` 分支发布了[patch](https://github.com/amefs/quickbox-lite/commit/84ebf0f9a02bc1376b34de506a60406b571a7094)。

**Comment by hanfly** [comment]
> 

感谢，问题已经解决了，成功安装了。

**Comment by a1751504** [comment]
我也有这个问题，但是使用--dev安装后还是这样，请问该怎么解决

**Comment by amefs** [comment]
还是上游刚改了代码，又删了东西。重写了一点检测，更新脚本以后重装一下这个软件应该就没问题了。

**Comment by a1751504** [comment]
> 还是上游刚改了代码，又删了东西。重写了一点检测，更新脚本以后重装一下这个软件应该就没问题了。

感谢回复

我已经重装了十几遍了，debian的版本也换了多个，还是不行。
用的是v1.5.7，进入dashboard之后提示也是development版本，但是安装flexget的时候还是报错
我重装还有另外的什么地方有可能出错吗

**Comment by amefs** [comment]
应该没有，你需要立即更新以下脚本，解除 lock，然后直接安装 art/flexget 就可以了。patch是刚推送的。

**Comment by a1751504** [comment]
> 应该没有，你需要立即更新以下脚本，解除 lock，然后直接安装 art/flexget 就可以了。patch是刚推送的。

请问您说的这个刚推送是今天刚刚推送的吗，是的话我就去重新装上

**Comment by amefs** [comment]
是的，刚测试完推送的。命令没问题。目前dev/master分支内容相同，刚做过一次同步。

**Comment by a1751504** [comment]
> 



> 是的，刚测试完推送的。命令没问题。目前dev/master分支内容相同，刚做过一次同步。

已安装成功，万分感谢
