### ISSUE TITLE
Debian 10  buster 安装软件失败解决办法，定位问题报错为连接github失败：Failed sending HTTP2 data

### ISSUE THREAD

**Issue by AisukaYuki** [amefs/quickbox-lite#193]
安装Flexget是Build pyenv时报错，后定位发现问题是连接github报错 Failed sending HTTP2 data。导致无法安装。
google后发现在Debian 10  buster 上由libcurl3-gnutls的bug引起，在降级`sudo apt reinstall libcurl3-gnutls/buster`后解决,，或升级为Debian 11。
其他系统暂未发现问题，有相同环境的问题的朋友可试试，上述办法

**Comment by amefs** [comment]
这个问题通常在启用了 `buster-backport` 之后会出现，之前已经默认禁用了这个repo。如果使用并遇到上述问题，解决方式的确是重新安装，并且建议使用 `apt-mark hold libcurl3-gnutls` 锁定你重新安装的版本。
