### ISSUE TITLE
ubuntu无法加载挂载点，安装界面也直接跳过了挂载点的选项

### ISSUE THREAD

**Issue by z3230442** [amefs/quickbox-lite#196]
ubuntu无法加载挂载点，安装界面也直接跳过了挂载点的选项,文件管理器也无法访问到此路径，

![image](https://user-images.githubusercontent.com/125951622/234655217-9237b9ed-ba7b-4ecc-b2e3-d5d2968c217d.png)
![image](https://user-images.githubusercontent.com/125951622/234655565-efc6087b-9269-431d-a179-176c789e709e.png)

 - 设备: [windows PC]
 - 操作系统: [ubuntu16.0]
 - 浏览器 [EDGE]

**Comment by amefs** [comment]
对于这种用法，目前脚本并没有直接支持，但可以通过手动挂载目录的方式解决。即将你这里的 `/dev/sda1` 重新挂载到 `/home/${username}` 下。

首先将当前 `/home/${username}` 下的内容复制到 `/data1`: `cp -r /home/${username}/* /data1` 

随后重新将 `/data1` 挂载到 `/home/${username}`: 首先确保卸除挂载 `umount /data1`，随后 `mount /dev/sda1 /home/${username}`，最后修改权限 `chown -R ${username}.${username} /home/${username} `。

> 注：如果需要持久化该修改，则还需要相应的修改 `/etc/fstab` 文件。修改 `dev/sda1` 的挂载点即可。
