### ISSUE TITLE
sabnzbd

### ISSUE THREAD

**Issue by Velenski** [amefs/quickbox-lite#197]
where has sabnzbd gone
i could have sworn i could always install it
i really need sabnzbd otherwise QBLite would be useless for my use  :/

**Comment by amefs** [comment]
This feature may be supported in the future, but I don't have a Usenet. I think the testing of the actual functions may need your help.

**Comment by Velenski** [comment]
sure but hardly needs usenet to create the packages and installer does it?
it used to be in the original CE of QB.
however sabnzbd dropped support for python 3.7 and 3.8 and requires new versions in order to work.
if you need anything from me let me know and i will try to oblige  :)

**Comment by amefs** [comment]
If I need any additional information, I will leave a comment here. Once I have completed the basic installation functions, I need you to confirm that the software is working properly.

**Comment by Velenski** [comment]
Wonderful. I'll do that  :)

Op vr 5 mei 2023 19:52 schreef amefs ***@***.***>:

**Comment by amefs** [comment]
Available on [473c907](https://github.com/amefs/quickbox-lite/commit/473c907884e341fbc329e5d3160213ec910542b7). You can switch to the developer branch to check if SABnzbd is working normally.

**Comment by Velenski** [comment]
> Available on [473c907](https://github.com/amefs/quickbox-lite/commit/473c907884e341fbc329e5d3160213ec910542b7). You can switch to the developer branch to check if SABnzbd is working normally.

installs great but slow due to the penvy and then python packages, that is to be expected and perhaps can be little faster with tweaks not sure.
i advice on setting default folders during install where it can download safely (incomplete under user and Complete)
like with torrents folders in rutorrent.
Or the user can set it ofcourse but you know that not everyone understands that lol.
i will create those locations manually now and test the download and unpack functionality and report back

**Comment by Velenski** [comment]
works like a charm buddy
fast speeds on a small VPS no issues at all
looked at logs and theyre empty for errors and warnings
if you ask me you can publish it and add to master
dont forget the menu item hahahaha
