### ISSUE TITLE
希望能加上trasmission美化面板的集成

### ISSUE THREAD

**Issue by lionheart2133** [amefs/quickbox-lite#20]
详见  [这个项目](https://github.com/ronggang/transmission-web-control)

**Describe the solution you'd like**
希望就像安装rtorrent的时候可以选择使用rutorrent或者flood一样，集成在选择transmission后的安装选项中。

**Comment by amefs** [comment]
由于 Transmission 原本的 WebUI 功能实在过于简单，因此安装 Transmission 的时候直接集成了你所说的增强型面板的功能。

**Comment by lionheart2133** [comment]
> 由于 Transmission 原本的 WebUI 功能实在过于简单，因此安装 Transmission 的时候直接集成了你所说的增强型面板的功能。

我在安装流程和dashboard里都没有找到相关选项，然后去wiki里也没找到相关的说明...而我安装后确实默认启用的是原版UI，请提示一下该如何操作...

**Comment by amefs** [comment]
这通常是因为某些网络原因未能成功下载到安装脚本。如果你没有清理日志的话，可以尝试查看 `/srv/dashboard/db/output.log` 的内容以确定原因。
目前你可以直接运行增强面板的安装脚本，在理论上不与 quickbox-lite 的功能有任何冲突

**Comment by lionheart2133** [comment]
好的，谢谢，我本来就是因为尝试自己运行这个脚本没有变化才开的issue。在这之后在面板里重装了一下transmission，然后再运行增强面板的安装脚本就正常了，
虽然解决了output.log中从头到尾都没有错误提示，很迷。。。
