### ISSUE TITLE
rclone webui成功挂载webdav且能正常显示内容，但在命令行rclone config未显示任何挂载信息

### ISSUE THREAD

**Issue by Zeeshan975** [amefs/quickbox-lite#207]
![rclone config](https://github.com/amefs/quickbox-lite/assets/75150657/1bd8f7dc-d2a3-41f3-aba3-108284e821bc)
![rclone mount error](https://github.com/amefs/quickbox-lite/assets/75150657/f17aa7b0-a6e1-44cf-affd-cd72cc156089)
![rclone webui](https://github.com/amefs/quickbox-lite/assets/75150657/60ac48f2-5179-4829-b7f7-5462075bdfa5)

**Comment by amefs** [comment]
用户不同，该 WebUI 的配置使用普通账户，而非 root。
