### ISSUE TITLE
Available space query

### ISSUE THREAD

**Issue by alvin9211** [amefs/quickbox-lite#208]
Hi Sir

First of all many thanks for the code for the quickbox, however i noted there is something wrong with the disk space available , i ordered 2 x 4TB hdd however the dashboard only displayed 3.7 available disk space.

Would like to know is there anything that i need to run via ssh?

Thanks in advance. =)

**Comment by tautcony** [comment]
Please provide the output of the command `df -h| grep -E "^(/dev/)"` from the terminal and a screenshot of the disk data panel.

**Comment by alvin9211** [comment]
/dev/md2       ext4      2.0T  4.2G  1.9T    1% /
/dev/md1       ext3      989M   66M  873M    7% /boot
/dev/md3       ext4      1.7T  1.2T  370G   77% /home

[image: image.png]

**Comment by tautcony** [comment]
Your another disk isn't mounted in system yet, you need to mount it before using. The `lsblk` command can list all available block devices.

**Comment by alvin9211** [comment]
Thanks Cony for the reply, just to double confirm I will need to mount the
second disk before intalling the quickbox lite?

**Comment by tautcony** [comment]
You can mount you disk and use your second disk at any time, quickbox-lite disk widget show info based on the output of command `df -h| grep -E "^(/dev/)"`

**Comment by alvin9211** [comment]
Thanks Cony then i have no further query

Thanks again
