### ISSUE TITLE
Please update Deluge 1.3.15 to 2.0.3

### ISSUE THREAD

**Issue by now163** [amefs/quickbox-lite#21]
OS：ubuntu 18.04

默认安装的是deluge-1.3.15和flexget-3.0.17。
但flexget要求deluge的版本最低为1.5..
deluge-client >=1.5 is required

**Comment by amefs** [comment]
如果你还安装有 qBittorrent 4.2.x 则 FlexGet 默认安装 3.x 版本；
如果没有安装 qBittorrent 或者版本小于 4.2.0 则默认安装 FlexGet 2.x；

因此如果你想安装 Deluge 2.0.3 那么你可以使用命令行工具 `box install deluge --de 2.0.3` 暂时不会提供额外的升级脚本

**Comment by now163** [comment]
噢~是的。还同时安装有qb-4.2.1。
非常感谢提供这么棒的工具。

**Comment by Aniverse** [comment]
其实应该是 `pip3 install deluge-client`

**Comment by now163** [comment]
> 其实应该是 `pip3 install deluge-client`
是的，我发现2.0.3有些问题好多PT站还不支持。比如CHD。
按照错误提示，把deluge-client升级到1.8就能解决问题了。
