### ISSUE TITLE
install on oracle cloud

### ISSUE THREAD

**Issue by jayzmizzou** [amefs/quickbox-lite#210]
![image](https://github.com/amefs/quickbox-lite/assets/134666591/66236e9e-8b39-45ed-94ca-0dc6fb718a96)
It install on the private ip 10.0.0.66. How could I install this to the public ip. Thank you!

**Comment by amefs** [comment]
Oracle has implemented a 1:1 NAT outside your virtual machine, where the public IP address is not directly bound to your interface. As a result, the private address here is by the design. You can still access the panel directly using the public IP address assigned by Oracle.

**Comment by jayzmizzou** [comment]
> Oracle has implemented a 1:1 NAT outside your virtual machine, where the public IP address is not directly bound to your interface. As a result, the private address here is by the design. You can still access the panel directly using the public IP address assigned by Oracle.

Thank you for your reply. I am new to this. It appears that I am unable to log in using the public IP directly. Should I change any settings or use a private key instead? When I try to log in via SSH, it requires the key with the ubuntu name.

**Comment by amefs** [comment]
Did you enable the HTTP/HTTPS ports in the security rules of Oracle Cloud? If you are still using a BitTorrent client, additional ports need to be allowed as well.

**Comment by jayzmizzou** [comment]
> Did you enable the HTTP/HTTPS ports in the security rules of Oracle Cloud? If you are still using a BitTorrent client, additional ports need to be allowed as well.

How to enable the HTTP/HTTPS ports? Just like this? I apologize for any inconvenience I may have caused you. I used HostHatch VPS a year ago, and found it easy to follow their wiki. However, Oracle is more complex for me.
<img width="1208" alt="Screenshot 2023-10-30 at 2 40 08 PM" src="https://github.com/amefs/quickbox-lite/assets/134666591/16cda44d-6a34-4b63-9406-98549cb28de6">

**Comment by amefs** [comment]
instances -> Attached VNICs -> Subnet -> Security Lists -> Add Ingress Rules
setup new rules:
<html>
<body>


| Stateless | Source | IP Protocol | Source Port Range | Destination Port Range | Type and Code | Allows | Description | 
| -- | -- | -- | -- | -- | -- | -- | -- | 
| No | 0.0.0.0/0 | TCP | All | 80 |   | TCP traffic for ports: 80 | HTTP/HTTPS |  
| No | 0.0.0.0/0 | TCP | All | 443 |   | TCP traffic for ports: 443 HTTPS | HTTP/HTTPS |  

</body>
</html>

or simply:

<html>
<body>


| Stateless | Source | IP Protocol | Source Port Range | Destination Port Range | Type and Code | Allows | Description | Actions |
| -- | -- | -- | -- | -- | -- | -- | -- | -- | 
| No | 0.0.0.0/0 | All Protocols |   |   |   | All traffic for all ports

</body>
</html>

**Comment by jayzmizzou** [comment]
> enable the HTTP/HTTPS ports in the security rules of Oracle Cloud

Thank you so much for your assistance. Unfortunately, the issue persists despite our efforts. I will attempt to resolve it by reinstalling quickbox.
<img width="493" alt="Screenshot 2023-10-30 at 3 07 11 PM" src="https://github.com/amefs/quickbox-lite/assets/134666591/15395ab9-271b-42a3-9c04-e0b210780327">

**Comment by amefs** [comment]
It is typically necessary to inspect the Nginx process in this case. Please execute the command `systemctl status nginx` to obtain its status.

**Comment by jayzmizzou** [comment]
> It is typically necessary to inspect the Nginx process in this case. Please execute the command `systemctl status nginx` to obtain its status.

I reinstalled it and now it works. This time, I opened the HTTP/HTTPS port before installing. Thank you for your help!
