### ISSUE TITLE
qbittorrent在下载和上传时会出现webui无法访问的情况

### ISSUE THREAD

**Issue by SevenPlusJun** [amefs/quickbox-lite#211]
qbittorrent在下载和上传时会出现webui无法访问的情况，但是quikboxlite的UI和trans的UI均可以访问。
我是PVE虚拟机硬盘1下安装quickboxlite，硬盘2为3块M2组的raid作为数据盘。

**Comment by amefs** [comment]
qBittorrent 的 WebUI 很容易在高吞吐/高负载时没有响应。考虑到你使用 SSD，那么通常不会遇到明显的 IO 瓶颈，不能简单地通过优化配置改善。较新版本的 qBittorrent 稍有缓解，但依然会有这样的状况。
