### ISSUE TITLE
Installation script failed to check out some files.

### ISSUE THREAD

**Issue by tautcony** [amefs/quickbox-lite#215]
**Describe the bug**

Github had sunset the svn support.

[Sunsetting Subversion support](https://github.blog/2023-01-20-sunsetting-subversion-support/)

**To Reproduce**
Steps to reproduce the behavior (or command):

```shell
./setup.sh
```

When setting up Nginx Fancyindex theme in the installation, it failed to checkout file from github by svn.

May also affect rutorrent installation.

related code:

https://github.com/amefs/quickbox-lite/blob/6b5608dec613929fd2683c2d84a12fef0a2bd697/setup.sh#L805

https://github.com/amefs/quickbox-lite/blob/6b5608dec613929fd2683c2d84a12fef0a2bd697/packages/package/install/installpackage-rutorrent#L195-L201
https://github.com/amefs/quickbox-lite/blob/6b5608dec613929fd2683c2d84a12fef0a2bd697/packages/package/install/installpackage-rutorrent#L258
https://github.com/amefs/quickbox-lite/blob/6b5608dec613929fd2683c2d84a12fef0a2bd697/packages/package/install/installpackage-rutorrent#L271

https://github.com/amefs/quickbox-lite/blob/6b5608dec613929fd2683c2d84a12fef0a2bd697/packages/package/update/updatepackage-rutorrent#L173-L179
https://github.com/amefs/quickbox-lite/blob/6b5608dec613929fd2683c2d84a12fef0a2bd697/packages/package/update/updatepackage-rutorrent#L236
https://github.com/amefs/quickbox-lite/blob/6b5608dec613929fd2683c2d84a12fef0a2bd697/packages/package/update/updatepackage-rutorrent#L249

**Expected behavior**

Check out file successfully.

**Screenshots** (optical)
![2a669a4b765471607468cc92d216840c](https://github.com/amefs/quickbox-lite/assets/8295052/5ff78a48-bb0c-436c-991a-c78dd51fb679)

---

**Additional context**

**Desktop (please complete the following information):**

 - Executed Command (if exist) [e.g. `box update quickbox`]

**Smartphone (please complete the following information):**

**Comment by tautcony** [comment]
Commit b5c67e0edad18756e10e12028d793b3bcd330bb4 should fix this issue.

**Comment by amefs** [comment]
Confirmed fixed.
