### ISSUE TITLE
安装界面一直停在 php7.4-cli   不能前进

### ISSUE THREAD

**Issue by fayswing** [amefs/quickbox-lite#219]
安装界面一直停在 php7.4-cli
![b4c3ddc99ea05bba51eb6c05d45bbb3](https://github.com/amefs/quickbox-lite/assets/44943458/42a9bcab-5228-4765-b19e-ab9db06b6a1e)

esxi8.0 环境下的          ubuntu-18.04.4-live-server  虚拟机

不知道是不是缺少什么插件    请大佬支个招！

**Comment by amefs** [comment]
请检查以下，`/root` 下的 log 文件，很可能是 ppa 取消了 Ubuntu 18.04 的支持。因为该系统已经在去年就 EOL 了。

**Comment by fayswing** [comment]
谢谢大佬的回复     我在root下面没找到log的文件     文件列表在下
![image](https://github.com/amefs/quickbox-lite/assets/44943458/976fcceb-5de1-439a-a16e-b12595d49043)

请问下大佬   简单的解决方法可不可以把Ubuntu18.04直接升级到20.04.6   可以解决这个问题吗

**Comment by fayswing** [comment]
我试着单独安装php7.4      出现了下面的报错

![image](https://github.com/amefs/quickbox-lite/assets/44943458/920019ac-f9d6-49ff-9058-f317aa447e72)

请大佬查阅

**Comment by amefs** [comment]
你可以尝试升级一下，没有特殊需求的话，直接重新安装为更新的系统应该是更好的选择。只需要下载新的安装镜像即可。如果需要逐个版本升级，那么只要遵循 [官方文档](https://ubuntu.com/server/docs/upgrade-introduction) 即可。

**Comment by fayswing** [comment]
好的   谢谢大佬    那我试试直接安装为最新的系统再跑一遍代码    如果还是不行再来请教大佬
非常感谢！

**Comment by fayswing** [comment]
重新安装了最新的Ubuntu 20.04.6的版本   通过了php的界面       安装成功了   
跟大佬汇报一下     看来以后18.04系统用不了了

**Comment by amefs** [comment]
下个版本会取消已经 EOL 系统的支持。通常软件源都会在发行版 EOL 以后删除支持，因此很容易出现各种奇怪的问题。一般比较建议安装比较新的发行版，可以减少麻烦。

**Comment by John-Smith-SG** [comment]
Oneprovider 的 Debian 10 镜像也出现此问题 (php7.4-cli 卡在12%)，有什么解决办法吗？

**Comment by John-Smith-SG** [comment]
似乎是Debian 10 支持到期导致的：
https://forums.debian.net/viewtopic.php?t=159712
