### ISSUE TITLE
Resilio Sync WebUI crash

### ISSUE THREAD

**Issue by John-Smith-2020** [amefs/quickbox-lite#227]
**Describe the bug**

Resilio Sync frequently crashes. No pattern. Crash randomly. Error message: 
=============================
**Resilio Sync connection lost**

Resilio Sync has stopped responding.

Try reloading the page, or restarting the Resilio Sync instance you were connected to. 
=============================
The background process worked fine. File sync was not interrupted by the WebUI crash. 

**To Reproduce**
Steps to reproduce the behavior (or command):

Can happen at any time. No reliable way to reproduce. Try scrolling down the file sync records. Usually it will crash in 30 seconds.

**Expected behavior**

**Screenshots** (optical)

---

**Additional context**
Maybe something related to WebUI was broken during package installation. The quickbox was installed on an OVH dedicated server with 16G memory and 4 cores CPU, so I think it's not system resource problem.  

**Desktop (please complete the following information):**

Server OS: Debian 12, Desktop OS: Windows 10
Browser: Firefox
Version: 131.0.2 (64-bit)

**Comment by amefs** [comment]
Please confirm whether you are using the latest version of Resilio Sync. Recently, Resilio released version 3.0. I haven't extensively tested this version, but during my trials, I noticed that the WebUI seems somewhat unstable, not sure whether caused by Resilio it self or the nginx proxy setting. The exact cause is yet to be determined and requires further investigation. 

![Resilio3.xCrash](https://cdn-image.wenzelu.com/2024/11/10/Resilio3.xCrash.png)

**Comment by amefs** [comment]
Please try updating with the new patch in the development branch (reinstalling the package): 
- utilize the new Resilio Sync configuration file content and structure
- update the systemd unit.

Please let me know if the patch proves effective.

**Comment by John-Smith-2020** [comment]
> Please confirm whether you are using the latest version of Resilio Sync. Recently, Resilio released version 3.0. I haven't extensively tested this version, but during my trials, I noticed that the WebUI seems somewhat unstable, not sure whether caused by Resilio it self or the nginx proxy setting. The exact cause is yet to be determined and requires further investigation.
> 
> ![Resilio3.xCrash](https://camo.githubusercontent.com/1208c28baa9f465f988fa2b7bfd03b213ed969b7952f4a7d5d8de87d9a2ff925/68747470733a2f2f63646e2d696d6167652e77656e7a656c752e636f6d2f323032342f31312f31302f526573696c696f332e7843726173682e706e67)

The current version is: 
Version 3.0.0 (1409)
I will try the development branch.

**Comment by John-Smith-2020** [comment]
> Please try updating with the new patch in the development branch (reinstalling the package):
> 
>     * utilize the new Resilio Sync configuration file content and structure
> 
>     * update the systemd unit.
> 
> 
> Please let me know if the patch proves effective.

This Resilio Sync in development branch works fine. No more crashes. Thanks!

For future users:
1. Click your username on the top right corner, there is an option "switch to development".
2. Run the updater on the panel.
3. Move your backup folder to another place, then delete BTSync package and re-install it.
4. Crash problem solved.
