### ISSUE TITLE
求助，安装Let's Encrypt后域名和ip都无法访问面板

### ISSUE THREAD

**Issue by Aoki-Li** [amefs/quickbox-lite#228]
纯小白，想通过域名访问面板遂安装证书后在cloudflare添加A记录，通过box install lecert -d DOMAIN安装，域名访问提示HOST异常，通过ip访问提示关闭连接，ssh卸载lecert通过ip仍无法进入面板提示关闭了连接，请问我该怎么恢复ip或者域名访问？

**Comment by amefs** [comment]
你已经卸载 LECERT 因此，你的 Nginx 配置会被重置，你可以直接通过 `nginx -t` 命令查看一下目前状态，如果设置正确则应当显示类似如下内容。
```
2024/12/06 17:18:11 [warn] 187923#187923: "ssl_stapling" ignored, issuer certificate not found for certificate "/etc/ssl/certs/ssl-cert-snakeoil.pem"
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```
对于 Cloudflare 启用代理模式，并通过域名访问的方式需要参考 [Wiki](https://wiki.ptbox.dev/zh-Hans/other-faqs/#%E5%A6%82%E4%BD%95%E6%B7%BB%E5%8A%A0%E4%B8%80%E4%B8%AA-cloudflare-cdn)

**Comment by Aoki-Li** [comment]
我使用nginx -t命令查看状态确和您提供的内容一致，但我仍无法通过ip访问面板提示关闭了连接

**Comment by amefs** [comment]
麻烦你运行
```
cat /etc/nginx/sites-enabled/default
```
获取 nginx 配置。如果有你自己的域名等敏感信息请自行删除。

**Comment by Aoki-Li** [comment]
非常抱歉直接重装系统了，放弃域名访问了，看了Cloudflare 启用代理模式觉得我自己弄不明白

**Comment by amefs** [comment]
代理模式的作用是将你的原 ip 通过 CF CDN 进行转发，因此你访问的是 CF IP。其中有个设置是让 CF 选择通过 443 还是 80 访问原站。在开启 Full 的时候是 443，Flex 是 80。

在 QuickBox 的设计中有一个默认的 443 -> 80 的自动重定向，如果 CF 设置为 Flex 访问 80 端口则会被反复重定向到 443，但是 CF 不认为这是 HTTPS 链接因此会使用错误的方式访问。这个是你最初遇到问题的理由。

如果你不需要隐藏 IP，最简单的方法就是直接关闭 CF 对该域名的代理模式即可（直连）。如需代理模式则需要根据 WIKI 所述内容进行设置。

**Comment by Aoki-Li** [comment]
我安装lecert两次都失败了，第一次是开启代理无法访问经过您的解释和wiki问题我已经明白了，我重装系统后第二次在CF中设置的是仅DNS，访问的时候是CF在提示我网址不存在，那我估计是中间时间太短导致的，或者我浏览器等缓存出了问题，让我先刷一阵子，等服务器快到期了我在安一次lecert用仅DNS看看能不能复现

**Comment by amefs** [comment]
我先关闭该 ISSUE，如果还有问题你可以选择 reopen。
