### ISSUE TITLE
不好意思，麻烦问一下怎么进入GUI

### ISSUE THREAD

**Issue by RtYkk** [amefs/quickbox-lite#23]
![Xshell_5DWpagYVSW](https://user-images.githubusercontent.com/45971730/76416634-652fbd00-63d6-11ea-9216-e55ba90d9a30.png)
纯小白，看起来是装好了。请问怎么进入wiki里那样的[控制台](https://github.com/amefs/quickbox-lite/wiki/%E4%BB%AA%E8%A1%A8%E7%9B%98)……谢谢，Wiki我都仔细看过了，应该没写……是装在一台Vultr上，Debian9

**Comment by tautcony** [comment]
访问你盒子对应的ip

**Comment by RtYkk** [comment]
> 访问你盒子对应的ip

我刚刚访问的时候把端口也加进去了，结果就挂了……谢谢
