### ISSUE TITLE
Syncthing安装失败

### ISSUE THREAD

**Issue by Latezly** [amefs/quickbox-lite#24]
**描述 Bug**
Web界面中Syncthing应用已安装并启动，但是在中间“服务监控中心显示为红点状态”
打开页面后显示502 Bad Gateway

**重现 Bug**
尝试在Online独立主机和Vultr的KVM主机中重新安装都出现此状态
刷新、重启、在web以及ssh中重装都尝试过，依旧无法运行

**期望的结果**
Syncthing正常运行

**截图** (可选)
![VGGC@$%5D`3K B)OMC04BK7](https://user-images.githubusercontent.com/17759624/76537441-bf08b380-64b8-11ea-916b-ee4787a64c65.png)

---

**附加内容**
output.log
> https://send.firefox.com/download/116a0149cb26e52e/#jsxDG5sARkojNpEdGazNUA

**桌面系统 (请填写下列信息):**

 - 操作系统:Ubuntu18.04
 - 浏览器 :chrome
 - 版本 80.0.3987.132
 - 执行的命令 无

**Comment by tautcony** [comment]
```bash
chown: invalid user: ‘efs.efs’                                                                                                                                                                                     
grep: /home/efs/.config/syncthing/config.xml: No such file or directory                                                                                                                                            
chown: invalid user: ‘efs.efs’   
```

在终端执行了一下安装指令，可见如上报错，查看对应安装脚本可以发现当前脚本配置存在几处错误[L233](https://github.com/amefs/quickbox-lite/blob/master/packages/package/install/installpackage-syncthing#L233), [L238](https://github.com/amefs/quickbox-lite/blob/master/packages/package/install/installpackage-syncthing#L238), [L242](https://github.com/amefs/quickbox-lite/blob/master/packages/package/install/installpackage-syncthing#L242)

临时的绕行方案的话可手动修改并执行以上链接附近的指令以完成安装。

**Comment by amefs** [comment]
最新 [commit](https://github.com/amefs/quickbox-lite/commit/7d19027c894d5fe1941520104fb19961b5115bdb) 已修复该问题，更新后，重新安装 Syncthing 即可
