### ISSUE TITLE
public download directory not working

### ISSUE THREAD

**Issue by rvpn** [amefs/quickbox-lite#26]
![nginx](https://user-images.githubusercontent.com/28747439/77677235-6104c180-6fca-11ea-91de-1813839c3136.PNG)

![404](https://user-images.githubusercontent.com/28747439/77677296-737efb00-6fca-11ea-82da-546bd4411809.PNG)

How to troubleshoot this error?

**Comment by amefs** [comment]
make sure you have the public dir in your home location, it means exist `/home/z47/public` for you, It should work.

**Comment by rvpn** [comment]
> /home/z47/public

ls: cannot access '/home/z47/public': No such file or directory

can i just mkdir /home/z47/public?

sorry i am not good at linux command line.

**Comment by amefs** [comment]
yep, just `mkdir /home/z47/public`

**Comment by amefs** [comment]
No more information, close issue
