### ISSUE TITLE
增加rclone及webui

### ISSUE THREAD

**Issue by qzydustin** [amefs/quickbox-lite#30]
rclone可以挂载网盘Google Drive Onedrive等
https://github.com/rclone/rclone
https://github.com/rclone/rclone-webui-react
感谢作者付出!

**Comment by Cysime** [comment]
RClone直接安装后，GUI可以运行：

**Comment by Cysime** [comment]
我自己试了下反向代理RcloneGUI，安装后可以运行GUI：
`rclone rcd --rc-web-gui --rc-user=user --rc-pass=pass --rc-addr=:5572
`
可以自己做一个简单的systemd来开机自启后台运行。

然后做反代，亲测这样可以直接用：
然后编辑` /etc/nginx/apps/rclone.conf`内容是：
```
location /rclone {
  return 301 /rclone/;
}

location /rclone/ {
    proxy_pass http://127.0.0.1:5572/;
    rewrite ^/rclone/(.*) /$1 break;
    proxy_redirect  off;
    proxy_cache_bypass  $http_upgrade;
    proxy_set_header Host              $host;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-Host  $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Port  $server_port;
}
```
再`nginx -s reload`重载nginx就可以直接访问`https://seedboxurl/rclone`使用了

剩下的需要修改面板，增加一项，但是好像没看到面板自定义的文档，Quickbox.io原版是有一个增加[自定义链接的选项](https://quickbox.io/knowledge-base/custom-menu-links/) ，文档说里面有php文件可以编辑，这边我有注意到 `/srv/dashboard/custom` 有这个目录，但是里面是空的，想请教一下作者 @amefs 如果可行的话自己添加自定义链接需要如何做，谢谢

**Comment by tautcony** [comment]
项目的前端部分相较于原始项目区别还是比较大的，如果你想要利用custom，可以参照[这里](https://github.com/amefs/quickbox-lite/blob/master/setup/dashboard/inc/panel.menu.php#L201)，新建`/custom/custom.menu.php`并添加代码。

但是完整的，包括菜单与服务面板显示的，与原始项目已经完全不同了，需要维护如下文件：
- https://github.com/amefs/quickbox-lite/blob/master/setup/dashboard/ws/commands.json
- https://github.com/amefs/quickbox-lite/blob/master/setup/dashboard/inc/info.package.php

**Comment by Cysime** [comment]
> @Cysime 项目的前端部分相较于原始项目区别还是比较大的，如果你想要利用custom，可以参照[这里](https://github.com/amefs/quickbox-lite/blob/master/setup/dashboard/inc/panel.menu.php#L201)，新建`/custom/custom.menu.php`并添加代码。
> 
> 但是完整的，包括菜单与服务面板显示的，与原始项目已经完全不同了，需要维护如下文件：
> 
> * https://github.com/amefs/quickbox-lite/blob/master/setup/dashboard/ws/commands.json
> * https://github.com/amefs/quickbox-lite/blob/master/setup/dashboard/inc/info.package.php
> * https://github.com/amefs/quickbox-lite/blob/master/setup/dashboard/inc/panel.app_status.ws.js

感谢指点，因为只需在面板左侧主菜单添加链接，实际上不需要动别的地方，直接在`/custom/custom.menu.php` 添加即可
<li><a href="RCLONE_URL" target="_blank"><img src="RCLONE_LOGO.SVG" class="mr-2 img-fluid rounded-circle" style="width:18px;height:18px;background-color:#171e27;"> <span>RClone</span></a></li>

**Comment by amefs** [comment]
v1.5.5 已完成支持
