### ISSUE TITLE
建议安装时提示挂载swap

### ISSUE THREAD

**Issue by qzydustin** [amefs/quickbox-lite#31]
**问题**
1. 1G内存的VPS安装rt失败，显示成功但是并没有安装成功
2. tr挂载1000小种频繁杀进程
3. rt挂载1000小种频繁杀进程

**解决方案**
问题一：使用update rtorrent后修复好了
问题二三：生成了2G文件作为SWAP后，不再崩溃

**替代方案**
可以在安装过程中提示是否增加SWAP空间，大部分VPS都没有SWAP
1.创建要作为swap分区的文件
```
# dd if=/dev/zero of=/root/swapfile bs=1M count=2048
```
2.格式化为交换分区文件:
```
# mkswap /root/swapfile 
```
3.启用交换分区文件:
```
# swapon /root/swapfile 
```
4.使系统开机时自启用，在文件/etc/fstab中添加一行：
```
/root/swapfile swap swap defaults 0 0
```

*****************************************************************************
直接安装rt失败，但是update可以安装，不知道是不是bug

**Comment by amefs** [comment]
将在 v1.4.1 提供该功能
