### ISSUE TITLE
Netdata问题

### ISSUE THREAD

**Issue by qzydustin** [amefs/quickbox-lite#34]
我想让A服务器安装netdata后接受BCD服务器的netdata数据

官方Wiki有教程，有两种方式，第二种stream方式就是BCD把数据发送到A服务器，然后教程端口默认19999，我试了一下好像不行，是不是quickbox的netdata默认端口改了，还是我操作问题。
https://docs.netdata.cloud/streaming/

第一种方式好像也接收不到数据

还有别的方法更好的集中监控多个服务器吗

感谢

**Comment by amefs** [comment]
是的，在quickbox 中我使用的是 unix socket，如果你想要集中管理，那么删除
```
[web]
    bind to = unix:/run/netdata/netdata.sock
```
重启服务即可，缺点是nginx 反代的设置会失效，你需要修改 `proxy_pass http://unix:/run/netdata/netdata.sock:/\$ndpath\$is_args\$args;`

**Comment by qzydustin** [comment]
nginx反向代理我遇到了一点问题， 我打开了/etc/nginx/sites-enabled/default ，在server里面添加location /netdata/{
     proxy_pass http://unix:/run/netdata/netdata.sock:/\$ndpath\$is_args\$args;
    }
然后service nginx restart重启了，还是无法打开https://*****/netdata/网址
ip＋端口号可以打开，好像是反向代理失败了

**Comment by amefs** [comment]
解释一下具体的操作方法：
netdata 在安装时我会提供一个默认的反代，`/etc/nginx/apps/netdata.conf`，你需要修改
```
proxy_pass http://unix:/run/netdata/netdata.sock:/\$ndpath\$is_args\$args;
```
为
```
proxy_pass http://127.0.0.1:19999/$ndpath$is_args$args;
```
不要直接修改 `/etc/nginx/sites-enabled/default`

**Comment by qzydustin** [comment]
解决问题了，感谢
