### ISSUE TITLE
lecert问题及更换端口

### ISSUE THREAD

**Issue by qzydustin** [amefs/quickbox-lite#36]
环境: 国内阿里云安装quickbox-lite，安装后ip可以访问，但是网址不行（应该是因为国内屏蔽了80）

问题一：我改了nginx site-enabled中的default 把listen端口改成了81，可以网址加端口访问了，是应该这样修改的吗。。。还是我碰巧对了

问题二：box install lecert -d 域名，安装成功，nginx重启失败提示证书问题，然后我去nginx/ssl/网址里面，发现就一个pem文件0kb。我之前的服务器安装有三个pem文件。不知道是什么问题。

我希望可以网址加444端口访问https（有证书的），可以实现吗

如果以后可以更方便的改网页端口就更好了

感谢作者解答

**Comment by amefs** [comment]
第一：你所说的屏蔽80/443端口说明你没有备案；

第二：letsencrypt必须使用80端口验证或者你可以自己用dns纪录完成验证；

第三：如果你搞定了证书，确实可以用444或者其他端口访问，原理同80端口。

我并不打算支持网页修改这些端口。这类的操作本身需要理解 nginx 配置，并配合一些命令做 debug 不适合网页完成。

**Comment by qzydustin** [comment]
好的感谢
