### ISSUE TITLE
大佬求助,qb4.2.3无法接收flexget推送

### ISSUE THREAD

**Issue by Sizukaze** [amefs/quickbox-lite#38]
任务一运行就报错:Error when trying to send request to qBittorrent: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/v2/app/webapiVersion (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f751bef3438>: Failed to establish a new connection: [Errno 111] Connection refused'))
确认了端口是没错的

**Comment by tautcony** [comment]
qbittorrent 的端口肯定不是8080，你flexget配置有问题，见[wiki](https://github.com/amefs/quickbox-lite/wiki/QuickBox-Lite-application-port-map)

**Comment by Sizukaze** [comment]
> qbittorrent 的端口肯定不是8080，你flexget配置有问题，见[wiki](https://github.com/amefs/quickbox-lite/wiki/QuickBox-Lite-application-port-map)

额,解决了,把QB降级到4.1.9就能推送了...

**Comment by amefs** [comment]
通过 box 命令或者面板安装 flexget 会根据你的 qBittorrent 版本安装所需的 flexget（flexget3.x), 如果直接使用pip之类安装则不会有，且并不会有配置文件模板
