### ISSUE TITLE
请问下qbittorrent是否可以选择安装4.1.9呢，

### ISSUE THREAD

**Issue by piaoyun** [amefs/quickbox-lite#39]
不想安装最新的版本呢

**Comment by Aniverse** [comment]
[WiKi 如何升级/降级软件版本？](https://github.com/amefs/quickbox-lite/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E5%A6%82%E4%BD%95%E5%8D%87%E7%BA%A7%E9%99%8D%E7%BA%A7%E8%BD%AF%E4%BB%B6%E7%89%88%E6%9C%AC)
问之前最好先看完 README 和 WiKi
