### ISSUE TITLE
502

### ISSUE THREAD

**Issue by techguruz** [amefs/quickbox-lite#42]
**Describe the bug**
when trying to share a link with file browser I get error 502 bad gateway
**To Reproduce**
links work if I am authenticated in my dashboard but if I load up a private window and enter the shared link I just get 502 bad gateway.

**Comment by amefs** [comment]
See manual here https://github.com/amefs/quickbox-lite/wiki/FAQ#how-to-enable-the-share-link-of-file-browser

**Comment by techguruz** [comment]
yeah already followed the guide in the manual.

**Comment by amefs** [comment]
oh, that is my mistake. One more step:
change /etc/nginx/apps/filebrowser.conf:
```proxy_pass http://$remote_user.filebrowser;```
to
```proxy_pass http://yourusername.filebrowser;```

**Comment by techguruz** [comment]
cheers buddy that was the missing step all working now.
