### ISSUE TITLE
磁盘剩余空间百分比显示错误

### ISSUE THREAD

**Issue by kolicime** [amefs/quickbox-lite#44]
在磁盘剩余空间不足1%时(并非具体数值)，磁盘剩余空间百分比会出现问题
系统：Debian9、Debian10
![显示状态](https://s1.ax1x.com/2020/04/30/Jqhm90.png)

**Comment by tautcony** [comment]
请提供一下复现该问题时，终端执行`df -h`后的输出结果

**Comment by kolicime** [comment]
![JL9gTs.png](https://s1.ax1x.com/2020/04/30/JL9gTs.png)

**Comment by amefs** [comment]
请切换到 development 分支并更新，确认一下是否修复

**Comment by kolicime** [comment]
![JjAADx.png](https://s1.ax1x.com/2020/05/01/JjAADx.png)
已修复，感谢
