### ISSUE TITLE
面板网速不显示，报错

### ISSUE THREAD

**Issue by wendaleruan** [amefs/quickbox-lite#45]
failed: WebSocket is closed before the connection is established.

**Comment by tautcony** [comment]
提issue建议使用模板填写

- quickbox-lite当前是什么版本？
- qyickbox-lite是升级到新版本的还是全新安装的新版本？
- 用的是什么浏览器打开的面板？
- 浏览器什么版本？
- 有没有修改过ngnix的配置？

**Comment by wendaleruan** [comment]
quickbox-lite当前是1.3.4版本
qyickbox-lite是全新安装的新版本
用的是chrome浏览器打开的面板
浏览器 chrome 81.0.4044.138（正式版本）版本
有没有修改过ngnix的配置？刚刚安装没改过
后台执行systemctl status quickbox-ws确认一下服务是否正常运行
Active: active (running)
node[387]: 1H269Dh2nOyHmfebAACT disconnect

应该怎么办？

**Comment by tautcony** [comment]
首先呢，这个面板的状态更新的服务，是存在fallback的。当websocket失败的时候也是能使用long pull来确保整体功能仍然正常可用的。

所以你说的这个面板状态无法正常更新显示，我倾向于认为你与所部署的服务器，在网络上可能存在一些问题，不知是哪家的独服/VPS呢？

此外，`systemctl status quickbox-ws`返回的信息其实挺丰富的，既然你只放了这这一小段那剩下的只能你自己去分析了。

**Comment by chenfangshuo** [comment]
升级ubuntu至“Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-72-generic x86_64)”，quickbox lite至1.46后，出现类似情况，不显示状态

### **quickbox-lite当前是什么版本？**
1.4.6
### **quickbox-lite是升级到新版本的还是全新安装的新版本**
从1.4.5升级至1.4.6
### **用的是什么浏览器打开的面板？**
chrome
### **浏览器什么版本？**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36
其他浏览器edge,firefox也试过了，不行
### **有没有修改过ngnix的配置？**
没有
### **后台执行systemctl status quickbox-ws确认一下服务是否正常运行**
```
> systemctl status quickbox-ws
● quickbox-ws.service - QuickBox Status Update WebSocket Interface
Loaded: loaded (/etc/systemd/system/quickbox-ws.service; enabled; vendor preset: enabled)
Active: activating (auto-restart) (Result: exit-code) since Tue 2021-04-20 23:00:55 CST; 17s ago
Process: 87355 ExecStart=/usr/bin/node /srv/dashboard/ws/dist/server.js (code=exited, status=1/FAILURE)
Main PID: 87355 (code=exited, status=1/FAILURE)
```
![Snipaste_2021-04-20_18-51-33.png](https://i.loli.net/2021/04/20/UO1tTiN7Chn6dqe.png)
