### ISSUE TITLE
QB 4.23重启问题

### ISSUE THREAD

**Issue by pnsroc** [amefs/quickbox-lite#46]
一直使用quickbox-lite非常好，在1.32里，使用的qb4.1版本没重新问题，但是1.33里使用qb4.2，经常在面板里发现qb停止运行

**Comment by amefs** [comment]
请在你的 /home/你的用户名/.config/qBittorrent/qBittorrent.conf 中添加(路径需要替换)
```
[Application]
FileLogger\Enabled=true
FileLogger\Age=6
FileLogger\DeleteOld=true
FileLogger\Backup=true
FileLogger\AgeType=1
FileLogger\Path=/home/你的用户名/.config/qBittorrent/qBittorrent.Log
FileLogger\MaxSize=20
```
然后重启 qBittorrent 以获取相关日志用于 Debug。

**Comment by Aniverse** [comment]
试试 `grep qbittorrent-nox /var/log/syslog`？
