### ISSUE TITLE
这个怎么解决

### ISSUE THREAD

**Issue by qcppl5** [amefs/quickbox-lite#49]
![Screenshot_20200630-013134](https://user-images.githubusercontent.com/61025967/86037197-8f82b480-ba71-11ea-8c52-0762904d949f.jpg)
执行的时候提示这个
![Screenshot_20200630-013313](https://user-images.githubusercontent.com/61025967/86037296-b80aae80-ba71-11ea-84cb-f2139adf1cc7.jpg)
这是配置，麻烦大佬了

**Comment by amefs** [comment]
example 本身并不包含任何实际配置，需要取消下方带 `#` 的注释标记的配置范例，启用必要的配置。也就是你要需要按照自己的具体用途进一步设置。

**Comment by qcppl5** [comment]
> example本身不一定包含任何实际配置，需要取消下方带`#`的注释标记的配置范例，启用必要的配置。也就是你要需要按照自己的具体用途进一步设置。

![Screenshot_20200630-133925](https://user-images.githubusercontent.com/61025967/86087643-46654b80-bad7-11ea-998a-31595e872843.jpg)
现在提示这个大佬怎么解决，麻烦了
