### ISSUE TITLE
qBittorrent webui error 502

### ISSUE THREAD

**Issue by zlspiderman** [amefs/quickbox-lite#56]
访问 qBittorrent webui （即https://我的域名/qbittorrent/）时提示 error 502，QuickBox-Lite 面板可以打开。
        在 vps 上新安装的 Ubuntu18.04 64bit，之后安装了 QuickBox-Lite ，安装后 qBittorrent webui 可以使用，并且下载种子没有问题，之后打开 qBittorrent webui 的设置页，没有修改任何选项，点击保存后页面刷新，提示 error 502，重启 qBittorrent 依然提示 error 502，使用 box remove 、box install 命令重新安装 qBittorrent 后可以使用，但是如果再次点击 qBittorrent webui 的设置，点击保存，error 502 还会出现。
        附件是 qBittorrent 重新启动的日志
[qbittorrent.log](https://github.com/amefs/quickbox-lite/files/5062357/qbittorrent.log)

**Comment by amefs** [comment]
请尝试如下操作：在出现 502 Bad Gateway 的时候
1. 查看你的 qBittorrent 配置文件确认一次配置文件中的 `WebUI\Port` 参数
2. 查看 `/etc/nginx/conf.d/[username].qbittorrent.conf` 中显示的端口，该端口理应与你配置文件中显示的一致
3. `netstat -tlnp | grep qbittorrent-nox` 查看监听端口，确认是否有 `qbittorrent-nox` 监听了正确端口 (`qbittorrent-nox` 通常来说至少会监听两个端口，一个是 bt 入栈端口，另一个是 WebUI 端口，该端口理应与你配置文件中显示的一致)
4. 如果上述操作找到的端口均一致，则尝试使用 `curl -i http://127.0.0.1:[你配置文件中的端口]`，正常情况下应该是 `HTTP/1.1 200 OK` 并显示一段 HTML 代码

**Comment by zlspiderman** [comment]
1和2查询到的端口不一致，3查询到监听的端口是1的端口

**Comment by zlspiderman** [comment]
另外向你反映一下，我的进程列表中运行的进程名称是qbittorrent-n，运行 netstat -tlnp | grep qbittorrent-nox 没有找到进程，运行 netstat -tlnp | grep qbittorrent-n 才找到的进程

**Comment by amefs** [comment]
这里比较大的概率是你的浏览器自动填充功能错误的填写了端口信息。解决方法就是把配置文件中的端口再修改回 2 中显示的端口。进程名称 `qbittorrent-n` 只是被截断了

**Comment by zlspiderman** [comment]
问题解决了，感谢大佬
