### ISSUE TITLE
vps重启后qBittorrent无法下载

### ISSUE THREAD

**Issue by zlspiderman** [amefs/quickbox-lite#58]
**描述 Bug**
qbittorrent本来可以下载，vps重启后qBittorrent无法下载，下载的是bt热种，tracker正常工作，能找到种子，但是无法连接到种子，可以连接到部分下载者，但下载速度为0
[qbittorrent.log](https://github.com/amefs/quickbox-lite/files/5072566/qbittorrent.log)

**Comment by zlspiderman** [comment]
无法连接到种子说的不太准确，具体情况是显示连接到的种子数有时为0，有时不为0，但是不为0时，用户栏显示他们的进度都为0
![截图](https://user-images.githubusercontent.com/50906887/90212513-17f0c500-de26-11ea-89f7-ad8dd225baf5.PNG)

**Comment by tautcony** [comment]
注意到日志中有报`Permission denied`，你可以先提供一下在终端下执行`ls -la /home/spider/torrents/qbittorrent/`的结果，确认一下报错文件的权限信息。

**Comment by zlspiderman** [comment]
total 1.5G
drwxr-xr-x 2 root      888 4.0K 8月  13 23:39  .
drwxr-xr-x 4 spider spider 4.0K 8月  13 23:37  ..
-rw-r--r-- 1 root      888 1.5G 8月  13 23:40 '[HorribleSubs] Re Zero kara Hajimeru Isekai Seikatsu - 31 [1080p].mkv'

**Comment by tautcony** [comment]
qbittorrent是以用户`spider`用户运行的，其创建的文件也是如此，或许是你在重启前是使用`root`用户启动了qbittorrent进行了下载，导致改文件为`root`所拥有。既然进度约为0%，建议使用`root`用户对该文件进行删除并在qbittorrent中重新添加该种子，应该就能正常下载了。

**Comment by zlspiderman** [comment]
我使用root用户删除了该文件
```
rm "/home/spider/torrents/qbittorrent/[HorribleSubs] Re Zero kara Hajimeru Isekai Seikatsu - 31 [1080p].mkv"
```
然后在qbittorrent中重新添加了该种子，下载速度还是为0，日志中增加了下面两条
```
(N) 2020-08-14T00:22:03 - '[HorribleSubs] Yahari Ore no Seishun Love Come wa Machigatteiru Kan - 06 [1080p].mkv' 已添加到下载列表。
(W) 2020-08-14T00:22:05 - 文件错误警告。Torrent："[HorribleSubs] Yahari Ore no Seishun Love Come wa Machigatteiru Kan - 06 [1080p].mkv"。文件："/home/spider/torrents/qbittorrent/[HorribleSubs] Yahari Ore no Seishun Love Come wa Machigatteiru Kan - 06 [1080p].mkv"。原因：[HorribleSubs] Yahari Ore no Seishun Love Come wa Machigatteiru Kan - 06 [1080p].mkv open (/home/spider/torrents/qbittorrent/[HorribleSubs] Yahari Ore no Seishun Love Come wa Machigatteiru Kan - 06 [1080p].mkv) error: Permission denied
```

**Comment by zlspiderman** [comment]
我的qbittorrent是通过`box remove, box install`重新安装的，重装之前也是出现了qbittorrent不能下载的问题，重装之后就能下载了，然后重启就又出现了问题

**Comment by tautcony** [comment]
遗漏了一点，`drwxr-xr-x 2 root 888 4.0K 8月 13 23:39 .`
还需要执行 `chown spider:spider /home/spider/torrents/qbittorrent`，该下载目录也为`root`所有。

有在安装quickbox之前安装过qbittorrent么？

**Comment by zlspiderman** [comment]
执行之后可以正常下载了，在安装quickbox之前没有安装过qbittorrent。
之前就在使用quickebox，前天重装了系统，重新安装的quickbox，另外有一个奇怪的地方我很在意，我重新安装quickbox后qbittorrent的界面设置保留了我重装系统前的界面设置，rutorrent的界面设置恢复默认了，这可能是什么原因造成的
![截图1](https://user-images.githubusercontent.com/50906887/90214513-4cb34b00-de2b-11ea-9204-2e97f0192b1b.PNG)

**Comment by zlspiderman** [comment]
我重启vps之后又不能下载了，`ls -la /home/spider/torrents/qbittorrent/`运行结果
```
drwxr-xr-x 2 root      888 4.0K 8月  14 00:34  .
drwxr-xr-x 4 spider spider 4.0K 8月  13 23:37  ..
-rw-r--r-- 1 root      888 773M 8月  14 00:34 '[HorribleSubs] Re Zero kara Hajimeru Isekai Seikatsu - 31 [720p].mkv'
```
qbittorrent日志
```
(N) 2020-08-14T00:44:40 - '[HorribleSubs] Re Zero kara Hajimeru Isekai Seikatsu - 31 [720p].mkv' 已恢复。
(N) 2020-08-14T00:45:10 - '[HorribleSubs] Re Zero kara Hajimeru Isekai Seikatsu - 31 [1080p].mkv' 已添加到下载列表。
(W) 2020-08-14T00:45:11 - 文件错误警告。Torrent："[HorribleSubs] Re Zero kara Hajimeru Isekai Seikatsu - 31 [1080p].mkv"。文件："/home/spider/torrents/qbittorrent/[HorribleSubs] Re Zero kara Hajimeru Isekai Seikatsu - 31 [1080p].mkv"。原因：[HorribleSubs] Re Zero kara Hajimeru Isekai Seikatsu - 31 [1080p].mkv open (/home/spider/torrents/qbittorrent/[HorribleSubs] Re Zero kara Hajimeru Isekai Seikatsu - 31 [1080p].mkv) error: Permission denied
```

**Comment by zlspiderman** [comment]
`ls -la /home/spider/torrents/`运行结果
```
total 76K
drwxr-xr-x   4 spider spider 4.0K 8月  13 23:37 .
drwxr-xr-x   9 spider spider 4.0K 8月  13 23:37 ..
drwxr-xr-x   2 root      888 4.0K 8月  14 00:34 qbittorrent
drwxr-xr-x 249 spider spider  60K 8月  13 06:56 rtorrent
```

**Comment by tautcony** [comment]
现在这个文件夹的权限一直在被重置回`root:888`。同时你说重装系统后配置还保留，想必home目录是被保留了吧，不像个正常的完整重装系统的操作。

**Comment by zlspiderman** [comment]
我的home目录是挂载盘，可能是重装系统之后格式化挂载盘的时候出了点差错，我再重新装一遍系统试一下，感谢大佬的指导

**Comment by zlspiderman** [comment]
我找到原因了，我新安装的`aria2-pro`使用`docker`容器时将`/home/spider/torrents/qbittorrent/`映射为下载目录了，把这个容器删除掉就没问题了
