### ISSUE TITLE
没有上传速度？是我服务器问题吗？

### ISSUE THREAD

**Issue by zhujitop** [amefs/quickbox-lite#61]
前几个月安装过这个脚本，是可以正常用的。

今天新买了台服务器，安装之后，发现没上传速度，Deluge、qBittorrent、rTorrent都不行。
开始以为是种子不行，但是找了几个热门种子，在网站上显示这些种子还有人在下载的。

但我这边就是没有任何上传。
下载速度超快，就是没上传。

请问这是我服务器问题吗？
带宽G口的独立服务器。

**Comment by amefs** [comment]
是的，应该是服务器问题，1Gbps Linkspeed 只代表你服务器最大支持的上下行速度，并不能与种子的上传速度直接挂钩。你可以通过 Speedtest / iperf 等方式测试你的服务器上行带宽。网站显示存在 Leechers 并不等于这些下载者能够连接到你的服务器。当且仅当你能够与 Leechers 保持高速稳定的连接时才会有较多的上行流量。
