### ISSUE TITLE
绑定cloudflare之后访问不了，请问怎么取消？

### ISSUE THREAD

**Issue by zhujitop** [amefs/quickbox-lite#62]
根据这里：
[如何添加一个Cloudflare CDN？](https://github.com/amefs/quickbox-lite/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E5%A6%82%E4%BD%95%E6%B7%BB%E5%8A%A0%E4%B8%80%E4%B8%AA-cloudflare-cdn)
绑定了域名。

但是访问不了，Error 521，服务器端有问题。

之前直接用服务器ip是可以访问的，现在直接访问ip也不行了。
请问怎么恢复呢？

**Comment by zhujitop** [comment]
我用netstat -ltn看端口情况，80和443并没有在里面开启。

单独另外开启sudo ufw allow 80和433，但是也没用。

不知道是不是因为端口问题不能访问。

所以就想干脆取消算了，不过没找到在那恢复原来ip访问的文档。

**Comment by amefs** [comment]
先用 `nginx -t` 测试一下你的配置文件，应该是包含一些错误，导致 nginx 没有正常启动

**Comment by zhujitop** [comment]
nginx没有报错。

是不是和srv文件夹或者dashboard文件夹不是www所有者权限有关？

**Comment by amefs** [comment]
没有报错的话你在 netstat 中应该会看到 nginx 监听 80/443 端口。你可以尝试 `systemctl restart nginx` 看一下是否正常监听。至于 521 的问题你可以通过修改本地 hosts 再你电脑上直接写入服务器 IP 绕过 Cloudflare 访问网站。或者将 Cloudflare 中 Proxy 修改为 Direct 直接访问你的服务器。

**Comment by zhujitop** [comment]
nginx重启也没报错，看了下netstat。
里面却没有80、443的端口开启。

是ubuntu18.04系统.

`netstat
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 zinc.datafaber.net:ssh  49.88.112.65:17347      ESTABLISHED
tcp        0      0 zinc.datafaber.ne:42051 104-179-213-157.li:6881 TIME_WAIT  
tcp        0    200 zinc.datafaber.net:ssh  119.85.110.176:27037    ESTABLISHED
tcp        0      0 zinc.datafaber.ne:53103 104-179-213-157.li:6881 TIME_WAIT  
tcp        0      0 zinc.datafaber.net:ssh  119.85.110.176:26380    ESTABLISHED
tcp        0      0 localhost:10031         localhost:45992         ESTABLISHED
tcp        0      0 zinc.datafaber.ne:42705 64.42.179.43:53046      ESTABLISHED
tcp        0      0 localhost:45992         localhost:10031         ESTABLISHED
Active UNIX domain sockets (w/o servers)
Proto RefCnt Flags       Type       State         I-Node   Path
unix  2      [ ]         DGRAM                    319      /run/systemd/journal/syslog
unix  2      [ ]         DGRAM                    384931   /run/user/1000/systemd/notify
unix  12     [ ]         DGRAM                    335      /run/systemd/journal/dev-log
unix  8      [ ]         DGRAM                    339      /run/systemd/journal/socket
unix  3      [ ]         DGRAM                    311      /run/systemd/notify
unix  3      [ ]         STREAM     CONNECTED     17153    
unix  3      [ ]         STREAM     CONNECTED     16675    /var/run/dbus/system_bus_socket
unix  2      [ ]         DGRAM                    385648   
unix  3      [ ]         STREAM     CONNECTED     15792    /run/systemd/journal/stdout
unix  2      [ ]         DGRAM                    396271   
unix  3      [ ]         STREAM     CONNECTED     14955    
unix  3      [ ]         STREAM     CONNECTED     777      /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     18524    
unix  3      [ ]         STREAM     CONNECTED     15207    
unix  3      [ ]         STREAM     CONNECTED     15077    
unix  3      [ ]         STREAM     CONNECTED     16270    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     150117   
unix  3      [ ]         STREAM     CONNECTED     15853    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     15332    
unix  3      [ ]         STREAM     CONNECTED     15660    /run/systemd/journal/stdout
unix  2      [ ]         DGRAM                    13789    
unix  3      [ ]         STREAM     CONNECTED     15445    /run/systemd/journal/stdout
unix  3      [ ]         DGRAM                    384933   
unix  3      [ ]         DGRAM                    13703    
unix  3      [ ]         STREAM     CONNECTED     16007    
unix  2      [ ]         DGRAM                    14961    
unix  3      [ ]         STREAM     CONNECTED     15785    /run/systemd/journal/stdout
unix  3      [ ]         DGRAM                    384932   
unix  3      [ ]         DGRAM                    13796    
unix  2      [ ]         DGRAM                    385632   
unix  3      [ ]         STREAM     CONNECTED     17933    
unix  3      [ ]         DGRAM                    13799    
unix  3      [ ]         STREAM     CONNECTED     15917    
unix  3      [ ]         DGRAM                    13797    
unix  3      [ ]         STREAM     CONNECTED     16285    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     13784    
unix  3      [ ]         STREAM     CONNECTED     16677    /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     15017    
unix  3      [ ]         STREAM     CONNECTED     384961   
unix  3      [ ]         STREAM     CONNECTED     16422    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     13696    
unix  3      [ ]         STREAM     CONNECTED     149355   /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     384962   
unix  3      [ ]         STREAM     CONNECTED     17934    
unix  3      [ ]         STREAM     CONNECTED     16674    /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     15016    
unix  2      [ ]         DGRAM                    15933    
unix  3      [ ]         STREAM     CONNECTED     794      /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     18525    
unix  2      [ ]         DGRAM                    13698    
unix  3      [ ]         STREAM     CONNECTED     16419    
unix  3      [ ]         DGRAM                    13702    
unix  2      [ ]         DGRAM                    497      
unix  3      [ ]         DGRAM                    13798    
unix  3      [ ]         STREAM     CONNECTED     16000    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     385638   /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     16960    
unix  3      [ ]         STREAM     CONNECTED     17410    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     435764   
unix  3      [ ]         STREAM     CONNECTED     17902    /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     17834    
unix  2      [ ]         DGRAM                    433147   
unix  3      [ ]         STREAM     CONNECTED     426983   
unix  3      [ ]         STREAM     CONNECTED     17716    
unix  3      [ ]         DGRAM                    313      
unix  3      [ ]         STREAM     CONNECTED     435909   
unix  3      [ ]         STREAM     CONNECTED     435765   
unix  3      [ ]         STREAM     CONNECTED     16557    
unix  3      [ ]         STREAM     CONNECTED     18449    
unix  3      [ ]         STREAM     CONNECTED     18531    /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     435763   
unix  3      [ ]         STREAM     CONNECTED     17511    /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     384912   
unix  3      [ ]         STREAM     CONNECTED     16259    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     435762   
unix  2      [ ]         DGRAM                    385752   
unix  3      [ ]         STREAM     CONNECTED     16742    
unix  3      [ ]         STREAM     CONNECTED     16249    
unix  2      [ ]         DGRAM                    16641    
unix  3      [ ]         STREAM     CONNECTED     18450    
unix  3      [ ]         STREAM     CONNECTED     16042    /run/systemd/journal/stdout
unix  2      [ ]         DGRAM                    16031    
unix  3      [ ]         STREAM     CONNECTED     18758    
unix  2      [ ]         DGRAM                    16671    
unix  3      [ ]         STREAM     CONNECTED     17341    
unix  2      [ ]         DGRAM                    384919   
unix  3      [ ]         STREAM     CONNECTED     16673    
unix  3      [ ]         STREAM     CONNECTED     16112    
unix  3      [ ]         STREAM     CONNECTED     150138   /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     16625    
unix  2      [ ]         DGRAM                    385768   
unix  2      [ ]         DGRAM                    427359   
unix  3      [ ]         STREAM     CONNECTED     17070    
unix  3      [ ]         STREAM     CONNECTED     18749    /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     16672    
unix  3      [ ]         STREAM     CONNECTED     426984   
unix  3      [ ]         DGRAM                    312      
unix  2      [ ]         DGRAM                    18609    
unix  3      [ ]         STREAM     CONNECTED     16629    
unix  3      [ ]         STREAM     CONNECTED     16743    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     149475   
unix  3      [ ]         STREAM     CONNECTED     16876    /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     435910   
unix  3      [ ]         STREAM     CONNECTED     17322    
unix  3      [ ]         STREAM     CONNECTED     16676    /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     15932    /run/systemd/journal/stdout
`

**Comment by amefs** [comment]
Wiki 里之前提供的代码看起来确实少了一个 sock='php7.4-fpm' (目前已补)，应该会导致面板工作异常。但是无法解释你这里看不到 nginx 监听。

**Comment by zhujitop** [comment]
那现在可以取消绑定域名这点吗，恢复到直接用ip访问。
不然就只能重新安装系统了。

**Comment by amefs** [comment]
可以的，直接 `box remove lecert` 重置到初始状态就行了

**Comment by zhujitop** [comment]
这个命令重置提示：

Let's Encrypt haven't installed ...


清除系统内存正常box clean mem

**Comment by amefs** [comment]
```
sock='php7.4-fpm'
	cat >/etc/nginx/sites-enabled/default <<NGC
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    location /.well-known {
      alias /srv/.well-known;
      allow all;
      default_type "text/plain";
      autoindex    on;
    }

    location / {
      return 301 https://\$host\$request_uri;
    }
}

# SSL configuration
server {
    listen 443 ssl http2 default_server;
    listen [::]:443 ssl http2 default_server;
    server_name _;
    ssl_certificate /etc/ssl/certs/ssl-cert-snakeoil.pem;
    ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key;
    include snippets/ssl-params.conf;
    client_max_body_size 40M;
    server_tokens off;
    root /srv/;

    index index.html index.php index.htm;

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/$sock.sock;
        fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
    }

    include /etc/nginx/apps/*;

    location ~ /\.ht {
        deny all;
    }

    location /fancyindex {

    }
}
NGC
nginx -s reload
```

**Comment by zhujitop** [comment]
一样的错误...
我重装系统了，重新来一遍试试。

刚开始只是想创建个公开下载目录的，但是访问这个公开目录404错误，才想绑定域名来着。

如果还不行，就继续只用ip访问吧。

**Comment by zhujitop** [comment]
重新来了一遍流程也不对，和之前一样的错误。
包括重置也还是Let's Encrypt haven't installed ...

继续用ip访问了。

但是创建的公开目录：

http://ip/$pt.public

进去提示404，是还需要操作别的吗？

**Comment by amefs** [comment]
`Let's Encrypt haven't installed ...` 是因为你没有安装 Let's Encrypt。这个你需要针对你的域名安装 `box install lecert -d 你的域名`。创建你的公开目录时请确保 `alias /home/$username/public;` 存在。

**Comment by zhujitop** [comment]
放弃了....
重新安装系统之后，创建公开目录又出现了：
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/etc/ssl/certs/ssl-cert-snakeoil.pem"

不知道为什么创建目录会提示证书问题，今天上午创建还没有。

先这样用着吧，不折腾了，用FTP也还可以。

**Comment by amefs** [comment]
Warning 只是自签证书的一般警告，没有关系，当你替换成 Let's Encrypt 证书后就会消失了
