### ISSUE TITLE
FTP功能如何使用

### ISSUE THREAD

**Issue by tsukiikekaoru** [amefs/quickbox-lite#64]
看了下安装文档，默认是装了vsftpd的，安装盒子时建立的用户有ftp权限吗？用这个用户去连盒子的ftp始终无法连接。

**Comment by amefs** [comment]
安装盒子用的账户有 ftp 权限，使用的端口为 5757

**Comment by tsukiikekaoru** [comment]
> 安装盒子用的账户有 ftp 权限，使用的端口为 5757

我一直以为是21端口……怎么试都不对，原来是因为端口错了。
感谢迅速的回复解答，更感谢这个项目👍
