### ISSUE TITLE
可以和网站兼容吗？

### ISSUE THREAD

**Issue by zhujitop** [amefs/quickbox-lite#65]
在已经有quickbox-lite情况下。
还可以用nginx新建个网站目录吗？

我看有nginx、php就够了，不用数据库。

**Comment by amefs** [comment]
可以的，这是 Nginx 的特性 vhost，直接在 `/etc/nginx/sites-enabled` 中添加一个新的 config file，设置好你绑定的域名 vhost。那么这时候就可以使用你的域名访问。（注意，由于 quickbox 在使用 ip 的时候设置默认服务器为 quickbox dashboard，因此在以 ip 方式直连服务器的时候并不能兼容其他网站。

**Comment by zhujitop** [comment]
也就是需要给quickbox dashboard先绑定一个域名了才行？

**Comment by amefs** [comment]
至少你新建的站点需要绑定一个域名。如果你没办法做到这点，那就只能使用 subfolder 来解决

**Comment by zhujitop** [comment]
1、我在/srv文件夹里面新建了一个文件夹，test网站目录；
2、在/etc/nginx/sites-enabled里面新建了一个文件，testd；
3、然后在testd里面写入下面的规则，就是把原来default里面的规则，加了个域名、改了个路径、然后改了监听服务。
发现打开新建网站的域名，是进到quickbox dashboard界面，不是我新建网站目录里面的网页。
同时用服务器ip，也还能访问quickbox dashboard。

原来default里面的规则是：
`    listen 80 default_server;
    listen [::]:80 default_server;`

我把default_server删了，如果不删，就都无法访问。

`server {
    listen 80;
    listen [::]:80;
    server_name test.yu.com;

    location /.well-known {
      alias /srv/.well-known;
      allow all;
      default_type "text/plain";
      autoindex    on;
    }

    location / {
      return 301 https://\$host\$request_uri;
    }
}

# SSL configuration
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name _;
    ssl_certificate /etc/ssl/certs/ssl-cert-snakeoil.pem;
    ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key;
    include snippets/ssl-params.conf;
    client_max_body_size 40M;
    server_tokens off;
    root /srv/test;

    index index.html index.php index.htm;

    # resolve multi-redirect
    if ($request_uri ~ "^[^?]*?//") {
    rewrite "^" $scheme://$host$uri permanent;
    }

    location ~ \.php$
    {
      fastcgi_read_timeout 240;
      fastcgi_pass  unix:/run/php/php7.4-fpm.sock;
      include snippets/fastcgi-php.conf;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
    include /etc/nginx/apps/*.conf;

    location ~ /\.ht {
        deny all;
    }

    location /fancyindex {

    }
}

`

**Comment by amefs** [comment]
因为你在访问域名的时候，优先访问了 http method，在这个时候 nginx 进行了一次 301 redirect，将你的 url 变为 `https://$host$request_uri`。但是你的 443 端口监听 (https method) 并没有设置域名，最后被 fallback 到 default server 上，也就是回到了 quickbox dashboard

**Comment by zhujitop** [comment]
我刚才删了301跳转https://$host$request_uri和443也加了域名。

访问结果还是一样的，依旧全部到quickbox dashboard界面。

我看了下/srv/test的所有者也改成了www-data,testd规则文件权限也改成755了。

需要把ssl的也删了吗？
    if ($request_uri ~ "^[^?]*?//") {
    rewrite "^" $scheme://$host$uri permanent;
    }

新规则

`server {
    listen 80;
    listen [::]:80;
    server_name test.yu.com;

    location /.well-known {
      alias /srv/.well-known;
      allow all;
      default_type "text/plain";
      autoindex    on;
    }

  
}

# SSL configuration
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name test.yu.com;
    ssl_certificate /etc/ssl/certs/ssl-cert-snakeoil.pem;
    ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key;
    include snippets/ssl-params.conf;
    client_max_body_size 40M;
    server_tokens off;
    root /srv/test;

    index index.html index.php index.htm;

    # resolve multi-redirect
    if ($request_uri ~ "^[^?]*?//") {
    rewrite "^" $scheme://$host$uri permanent;
    }

    location ~ \.php$
    {
      fastcgi_read_timeout 240;
      fastcgi_pass  unix:/run/php/php7.4-fpm.sock;
      include snippets/fastcgi-php.conf;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
    include /etc/nginx/apps/*.conf;

    location ~ /\.ht {
        deny all;
    }

    location /fancyindex {

    }
}

`

**Comment by amefs** [comment]
暂且无法直接判断你的问题，建议尝试将default先移动到 `/etc/nginx/sites-available`。也就是说暂且屏蔽 quickbox 的 WebUI，检查一下你的配置是否正常工作。

**Comment by zhujitop** [comment]
把default移走之后，访问ip不能进入quickbox dashboard界面了，显示Welcome to nginx!页面。

但是访问那个域名网址，还是进入到quickbox dashboard界面。

**Comment by amefs** [comment]
我想起来了，你要删除 `include /etc/nginx/apps/*.conf;`

**Comment by zhujitop** [comment]
删掉include /etc/nginx/apps/*.conf;之后可以了。

这个新建ftp用户名和密码的命令是什么？box help没看见...

我想新建一个ftp用户，然后这个ftp的目录就是/srv/test
就是我新网站这个目录。

**Comment by amefs** [comment]
暂且没有做新建 ftp 用户的功能，如果你要达成这个目的，需要参照 [官方文档](https://help.ubuntu.com/community/vsftpd#Configure_VSFTPD_for_virtual_user) 创建一个虚拟用户，chroot 绑定你的目录。

**Comment by zhujitop** [comment]
好的，可以了，谢谢大佬，可以关了
