### ISSUE TITLE
Apache reverse proxy with cloudflare CDN

### ISSUE THREAD

**Issue by kazuma777** [amefs/quickbox-lite#66]
First quickbox in VM ip `192.168.122.49`
because i dont want disturb main server.

and main server i need reverse proxy with subdomain
`

    <VirtualHost *:80>
    ServerAlias sub.domain.com
    SSLProxyEngine On
    ProxyRequests Off
        <proxy>
        Require all granted
        </proxy>
    ProxyPass / https://192.168.122.49
    ProxyPassReverse / https://192.168.122.49
    </VirtualHost>`

but didn't not work..

**Comment by amefs** [comment]
Try following config in your server pls:

```
<VirtualHost *:80>
        ServerAlias sub.domain.com
        ProxyPreserveHost On
        ProxyPass / http://192.168.122.49/
        ProxyPassReverse / http://192.168.122.49/
</VirtualHost>

<VirtualHost *:443>
        ServerAlias sub.domain.com
        # SSL in Apache
        SSLEngine on
        SSLProtocol ALL -SSLv2 -SSLv3
        SSLHonorCipherOrder On
        SSLCipherSuite ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
        SSLCertificateFile /etc/ssl/certs/ssl-cert-snakeoil.pem
        SSLCertificateKeyFile /etc/ssl/private/ssl-cert-snakeoil.key
        ProxyRequests off
        # disable SSL check if your VM used a self signed cert
        SSLProxyVerify none
        SSLProxyCheckPeerCN off
        SSLProxyCheckPeerName off
        SSLProxyCheckPeerExpire off
        SSLProxyEngine on
        ProxyPass / https://192.168.122.49/
        ProxyPassReverse / https://192.168.122.49/
        ProxyPassReverseCookiePath / https://192.168.122.49/
        ProxyTimeout 600
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

**Comment by kazuma777** [comment]
> Try following config in your server pls:
> 
> ```
> <VirtualHost *:80>
>         ServerAlias sub.domain.com
>         ProxyPreserveHost On
>         ProxyPass / http://192.168.122.49/
>         ProxyPassReverse / http://192.168.122.49/
> </VirtualHost>
> 
> <VirtualHost *:443>
>         ServerAlias sub.domain.com
>         # SSL in Apache
>         SSLEngine on
>         SSLProtocol ALL -SSLv2 -SSLv3
>         SSLHonorCipherOrder On
>         SSLCipherSuite ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
>         SSLCertificateFile /etc/ssl/certs/ssl-cert-snakeoil.pem
>         SSLCertificateKeyFile /etc/ssl/private/ssl-cert-snakeoil.key
>         ProxyRequests off
>         # disable SSL check if your VM uses a self signed cert
>         SSLProxyVerify none
>         SSLProxyCheckPeerCN off
>         SSLProxyCheckPeerName off
>         SSLProxyCheckPeerExpire off
>         SSLProxyEngine on
>         ProxyPass / https://192.168.122.49/
>         ProxyPassReverse / https://192.168.122.49/
>         ProxyPassReverseCookiePath / https://192.168.122.49/
>         ProxyTimeout 600
>         ErrorLog ${APACHE_LOG_DIR}/error.log
>         CustomLog ${APACHE_LOG_DIR}/access.log combined
> </VirtualHost>
> ```

sorry late reply.
and thank you very much! this config  working for me 😍

**Comment by kazuma777** [comment]
> Try following config in your server pls:
> 
> ```
> <VirtualHost *:80>
>         ServerAlias sub.domain.com
>         ProxyPreserveHost On
>         ProxyPass / http://192.168.122.49/
>         ProxyPassReverse / http://192.168.122.49/
> </VirtualHost>
> 
> <VirtualHost *:443>
>         ServerAlias sub.domain.com
>         # SSL in Apache
>         SSLEngine on
>         SSLProtocol ALL -SSLv2 -SSLv3
>         SSLHonorCipherOrder On
>         SSLCipherSuite ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
>         SSLCertificateFile /etc/ssl/certs/ssl-cert-snakeoil.pem
>         SSLCertificateKeyFile /etc/ssl/private/ssl-cert-snakeoil.key
>         ProxyRequests off
>         # disable SSL check if your VM uses a self signed cert
>         SSLProxyVerify none
>         SSLProxyCheckPeerCN off
>         SSLProxyCheckPeerName off
>         SSLProxyCheckPeerExpire off
>         SSLProxyEngine on
>         ProxyPass / https://192.168.122.49/
>         ProxyPassReverse / https://192.168.122.49/
>         ProxyPassReverseCookiePath / https://192.168.122.49/
>         ProxyTimeout 600
>         ErrorLog ${APACHE_LOG_DIR}/error.log
>         CustomLog ${APACHE_LOG_DIR}/access.log combined
> </VirtualHost>
> ```

if i click rutorrent from dashboard, will automatic go https://192.168.122.49/rutorrent/ is not go domain name.

**Comment by amefs** [comment]
The following content is only on your apache proxy server:
Step1:
setup a host for your VM in your proxy by adding the following things at the end of `/etc/hosts`
```
192.168.122.49 sub.domain.com
```
Step2:
renew the apache proxy config:
```
<VirtualHost *:80>
        ServerAlias sub.domain.com
        ProxyPreserveHost On
        ProxyPass / http://sub.domain.com/
        ProxyPassReverse / http://sub.domain.com/
</VirtualHost>

<VirtualHost *:443>
        ServerAlias sub.domain.com
        # SSL in Apache
        SSLEngine on
        SSLProtocol ALL -SSLv2 -SSLv3
        SSLHonorCipherOrder On
        SSLCipherSuite ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
        SSLCertificateFile /etc/ssl/certs/ssl-cert-snakeoil.pem
        SSLCertificateKeyFile /etc/ssl/private/ssl-cert-snakeoil.key
        ProxyRequests off
        # disable SSL check if your VM uses a self signed cert
        SSLProxyVerify none
        SSLProxyCheckPeerCN off
        SSLProxyCheckPeerName off
        SSLProxyCheckPeerExpire off
        SSLProxyEngine on
        ProxyPass / https://sub.domain.com/
        ProxyPassReverse / https://sub.domain.com/
        ProxyPassReverseCookiePath / https://sub.domain.com/
        ProxyTimeout 600
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

**Comment by kazuma777** [comment]
> 192.168.122.49

is showing `Error 1000 DNS points to prohibited IP`
