### ISSUE TITLE
利用vps反代加速plex求教

### ISSUE THREAD

**Issue by tsukiikekaoru** [amefs/quickbox-lite#68]
您好,
我安装了plex服务，但是原服务器到国内速度比较慢，因此想利用另一台vps反代加速。我现在的想法是plex服务器新建一个网站，绑定域名后反代到127.0.0.1:32400，然后在加速用的vps上再新建一个站反代到刚才在plex服务器上新建的那个站，不知是否可行。但在操作的时候我有几个问题想咨询下：
1. 需要新建一个.conf配置文件吗
不过不知道该建在哪，因为/etc/nginx下有很多配置文件，apps和和conf.d下有几个类似的配置文件，不知道该如何处理，需要删除apps下的plex.conf吗
2. plex服务器上使用下面的配置文件内容是正确的吗:
```
server {
      listen 80;
      server_name plex.example.com;

      location / {
          proxy_pass http://127.0.0.1:32400;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

          #upgrade to WebSocket protocol when requested
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
      }
}
```

**Comment by amefs** [comment]
在我看来有几个办法可以实现：
1. VPN，通过建立 vpn 将 vps 和 Plex 服务器连接。
2. nginx 反代，你不必删除 apps 下的 plex.conf 这只是将 plex 服务器的 32400 端口反代到 80 端口的操作，并未屏蔽 32400 端口直连。
我认为你想要达成的加速功能可以通过 nginx 的 TCP 负载均衡模块搞定(stream模块)。它起到的作用就是直接反代你的 32400 所有的 TCP 流量，也就是说你可以通过访问 vps 来间接连接 Plex 服务器。该配置仅需 vps 设置即可。

**Comment by tsukiikekaoru** [comment]
> 在我看来有几个办法可以实现：
> 
> 1. VPN，通过建立 vpn 将 vps 和 Plex 服务器连接。
> 2. nginx 反代，你不必删除 apps 下的 plex.conf 这只是将 plex 服务器的 32400 端口反代到 80 端口的操作，并未屏蔽 32400 端口直连。
>    我认为你想要达成的加速功能可以通过 nginx 的 TCP 负载均衡模块搞定(stream模块)。它起到的作用就是直接反代你的 32400 所有的 TCP 流量，也就是说你可以通过访问 vps 来间接连接 Plex 服务器。
>    或者就用普通的反代
> 
> ```
> upstream plex.host {
>         # plex
>         server Plex服务器IP地址:32400;
> }
> server {
>         server_name plex.host;
>         listen 80 ;
>         access_log /var/log/nginx/access.log vhost;
>         return 301 https://$host$request_uri;
> }
> server {
>         server_name plex.host;
>         listen 443 ssl http2 ;
>         access_log /var/log/nginx/access.log vhost;
>         ssl_session_timeout 5m;
>         ssl_session_cache shared:SSL:50m;
>         ssl_session_tickets off;
>         ssl_certificate /etc/nginx/certs/plex.host.tld.crt;
>         ssl_certificate_key /etc/nginx/certs/plex.host.tld.key;
>         ssl_dhparam /etc/nginx/certs/plex.host.tld.dhparam.pem;
>         ssl_stapling on;
>         ssl_stapling_verify on;
>         ssl_trusted_certificate /etc/nginx/certs/plex.host.tld.chain.pem;
>         add_header Strict-Transport-Security "max-age=31536000" always;
>         location / {
>                 proxy_pass https://plex.host;
> }
> ```
> 
> 该配置仅需 vps 设置即可。

**Comment by amefs** [comment]
网络错误属于运营商干扰，这个也只能通过一些vps中转解决。Let's Encrypt 证书是会自动续期的，通常无需干预。
