### ISSUE TITLE
box update qbittorrent 不能升级3.0

### ISSUE THREAD

**Issue by newage11** [amefs/quickbox-lite#69]
qBittorrent will now be updated.

This process may take a few minutes
Please wait until the process is completed

➜ Fetching package list...
⚠ Nothing to be update

**Comment by amefs** [comment]
脚本不支持 qBittorrent 3.x，也没有任何计划做支持。qBittorrent 4.1.x 配合 libtorrent 1.1.x 已经足够稳定，未有明确证据显示有问题。

**Comment by newage11** [comment]
说错了 ，现在是4.25 想升级4.30

**Comment by amefs** [comment]
请通过 `box update qbittorrent --qb 4.3.0` 指定升级的版本
