### ISSUE TITLE
流量统计按日期排序

### ISSUE THREAD

**Issue by ly012** [amefs/quickbox-lite#71]
现在的流量统计只有按合计排，希望能增加按日期排序。
![Lily_Screenshot_1607487522](https://user-images.githubusercontent.com/30511978/101584980-bce76d00-39d6-11eb-80f7-72cc89b2a5c9.png)

**Comment by xiaoguiwk** [comment]
我还纳闷儿呢这怎么随机排序的，偶尔还丢几天，原来是按合计排的...

**Comment by tautcony** [comment]
开发分支中已合并该功能，请等待正式版发布。具体配置位置详见#103。

**Comment by amefs** [comment]
正式版已发布 e8c3cc36dd8baadd6dff609485b31515c79c8686
