### ISSUE TITLE
无法识别挂载的samba目录

### ISSUE THREAD

**Issue by wssfxtx** [amefs/quickbox-lite#74]
安装的时候无法选择默认的下载目录，挂载的samba目录页无法在dasboard显示，并且，在下载APP中设置目录为samba目录无法生效！

**Comment by amefs** [comment]
没有考虑过这种用法, 因此 dashboard 暂且不会显示这些内容. bt 软件不识别你挂载的 samba, 可能需要检查一下权限问题, bt 软件都只用用户权限启动.
