### ISSUE TITLE
CIFS/Samba connection issues + performance tuning

### ISSUE THREAD

**Issue by annaparker** [amefs/quickbox-lite#75]
Hello!

Some servers can't connect to Samba server based on QuickBox. I have found the solution:
https://support.apple.com/en-ca/HT205926

This is the solution why Synology NAS (and Plex) wasn't able to connect Samba. Now it connects and what's nice it's faster now.

Thank you.

**Comment by amefs** [comment]
It seems to be a solution of macOS that uses nsmb as samba service. I'm not sure if "client signing" and "server signing" in smbd the same thing as "signing_required" in nsmb.

**Comment by annaparker** [comment]
Not really, just provided the link to Apple, because it's nice tutorial. However it's applicable to default configuration of Samba in QuickBox-lite also. I have nsmb.conf file with signing_required=no and now I am able to connect Samba server from my Synology NAS, where it was impossible.

**Comment by amefs** [comment]
Maybe I can try to add one more option for CIFS installation. e.g. run `box install cifs --compatibility` to disable these Incompatible features. I will notify you once it finished.

**Comment by amefs** [comment]
Here is the patch in the development branch
