### ISSUE TITLE
一个流量统计问题，一个CIFS/Samba问题

### ISSUE THREAD

**Issue by MarsBaby9** [amefs/quickbox-lite#77]
**描述 Bug**
1、系统新增一块网卡后，不会进行流量统计了，如下图，不知是bug还是需要在哪里进行修改？
![流量问题](https://user-images.githubusercontent.com/37400928/103901922-c4647800-5134-11eb-9d5e-b89d53215593.png)
2、安装CIFS/Samba后，win下可以正常访问（文件），但是在安卓下的ES文件浏览器和Nplayer里面都无法访问到目录里面（分别表现在文件2和文件3），在ipad下面也是无法访问，提示的都是权限问题，权限也都正确，因为win下是正常的以及kodi里面是正常。连接方式选择的都是CIFS/Samba
![文件](https://user-images.githubusercontent.com/37400928/103902340-5a000780-5135-11eb-8fd1-dc36098a81bc.png)
![文件2](https://user-images.githubusercontent.com/37400928/103902344-5b313480-5135-11eb-9d30-933bb2652241.jpg)
![文件3](https://user-images.githubusercontent.com/37400928/103902347-5c626180-5135-11eb-95d0-2ad313533374.jpg)

**期望的结果**
不知道是可以通过设置修复这个设置吗？

**Comment by tautcony** [comment]
新增的是`ens192`这个网卡么，同时后续的网络流量都经由新的网卡走，而下面的流量统计范围并没有将其包括进去。

如果是这样的话，可以尝试执行如下指令
```bash
cp /srv/dashboard/db/interface.txt /srv/dashboard/db/interface.txt.bak
ip link show | grep -i broadcast | grep -m1 UP | cut -d: -f 2 | cut -d@ -f 1 | sed -e 's/ //g' > /srv/dashboard/db/interface.txt
box update quickbox
```
更新一下配置，应该可以更新流量统计范围。

参考内容：

https://github.com/amefs/quickbox-lite/blob/master/setup.sh#L878
https://github.com/amefs/quickbox-lite/blob/master/packages/system/update/qbUpdateDashboard#L37

**Comment by amefs** [comment]
CIFS 推测问题是 #75 一样的原理，会再后续版本尝试更新兼容模式。

**Comment by amefs** [comment]
请尝试切换到 development 分支，更新 quickbox。 随后重新安装 cifs，并使用参数: `box install cifs --compatibility`

**Comment by MarsBaby9** [comment]
CIFS/Samba的问题解决了，确实按照box install cifs --compatibility安装就可以。
但是流量问题按照上面做后，/srv/dashboard/db/interface.txt中存在网卡名称，但是流量统计什么都不显示了。
![192](https://user-images.githubusercontent.com/37400928/103985848-ae9e9380-51c4-11eb-99ad-619a9d17a4af.png)
![流量显示](https://user-images.githubusercontent.com/37400928/103985870-b65e3800-51c4-11eb-8d07-9755325c8bda.png)

**Comment by tautcony** [comment]
> 但是流量问题按照上面做后，/srv/dashboard/db/interface.txt中存在网卡名称，但是流量统计什么都不显示了。
> ![192](https://user-images.githubusercontent.com/37400928/103985848-ae9e9380-51c4-11eb-99ad-619a9d17a4af.png)
> ![流量显示](https://user-images.githubusercontent.com/37400928/103985870-b65e3800-51c4-11eb-8d07-9755325c8bda.png)

实际执行的是哪个呢？下半部分中`bash /usr/local/bin/quickbox/system/auxiliary/set_interface`这个指令不是很对，缺少了对几个文件的重置操作，如果是上面哪个`box`指令，应该是可以的。

**Comment by MarsBaby9** [comment]
之前是ens160，现在实际有流量的是ens192
按照如下操作后，都不显示了。
_cp /srv/dashboard/db/interface.txt /srv/dashboard/db/interface.txt.bak
ip link show | grep -i broadcast | grep -m1 UP | cut -d: -f 2 | cut -d@ -f 1 | sed -e 's/ //g' > /srv/dashboard/db/interface.txt
bash /usr/local/bin/quickbox/system/auxiliary/set_interface_

**Comment by tautcony** [comment]
执行`box set ens192`，或者执行`box update quickbox`

**Comment by MarsBaby9** [comment]
box update quickbox之前执行过无效。box set ens192刚才执行后出现如下：也没效果。
![设置图](https://user-images.githubusercontent.com/37400928/103991655-f544bb80-51cd-11eb-8f70-7deb611b60d4.png)

**Comment by amefs** [comment]
`box set interface ens192`

**Comment by MarsBaby9** [comment]
执行后重启过机器，等待了几分钟，还是这样的。
![依旧](https://user-images.githubusercontent.com/37400928/103992656-65a00c80-51cf-11eb-801e-56a51c01422c.png)

**Comment by amefs** [comment]
这个问题一般是因为你的网卡还没有被 vnstat 识别到，那么你需要手动添加。运行 `sudo -u vnstat vnstat --add -i ens192`

**Comment by MarsBaby9** [comment]
做过这条命令重启后可以了。非常感谢。
