### ISSUE TITLE
2.0.3的deluge支持

### ISSUE THREAD

**Issue by zhouruiwu1997** [amefs/quickbox-lite#78]
请问能在安装脚本多加不同版本的下载器版本吗？

**Comment by amefs** [comment]
你是希望在 `setup.sh` 中增加软件版本的选择？

**Comment by zhouruiwu1997** [comment]
对的。

**Comment by amefs** [comment]
下个版本会在 CLI 安装增加相应选项。

**Comment by zhouruiwu1997** [comment]
感谢

**Comment by amefs** [comment]
已完成支持，用法参见文档

**Comment by xiaoguiwk** [comment]
> > 已完成支持，适当认为文档
> > 感谢

请问de2.0你安装成功了吗？我遇到了一些问题，可以看一下我发的issue，谢谢。

**Comment by zhouruiwu1997** [comment]
> > > 已完成支持，适当认为文档
> > > 感谢
> 
> 请问de2.0你安装成功了吗？我遇到了一些问题，可以看一下我发的issue，谢谢。

我在开头安装时候就直接是选择de2.0安装的，没进面板选择
