### ISSUE TITLE
deluge如何以ip:port方式访问？

### ISSUE THREAD

**Issue by xiaoguiwk** [amefs/quickbox-lite#81]
在wiki中发现了qb的解决方式，但是没有提及deluge。
1.在preference中勾选了允许远程访问，通过ip+daemonport或者ui中提供的端口号均无法访问；
2.在修改了deluge/web.conf文件中的地址127.0.0.1为0.0.0.0后仍无法访问，但这个修改导致了deweb直接502了，改回去也没用了。
以下是修改后的web.conf
```json
{
  "file": 1, 
  "format": 1
}{
  "port": 15555, #这里的端口号和preference中ui下提供的端口号相同
  "enabled_plugins": [
    "TotalTraffic", 
    "ltConfig", 
    "Stats", 
    "Label", 
    "AutoRemovePlus"
  ], 
  "pwd_sha1": "54ee3bbe99db4a35627a8e", 
  "theme": "gray", 
  "show_sidebar": true, 
  "sidebar_show_zero": false, 
  "pkey": "ssl/daemon.pkey", 
  "https": false, 
  "sessions": {
    "3261fadba577": {
      "login": "admin", 
      "expires": 1614703325.0, 
      "level": 10
    }
  }, 
  "base": "/", 
  "interface": "0.0.0.0", #这里原本是127.0.0.1，修改后无法访问deweb界面，重启了web界面没有重启deluged
  "pwd_salt": "umk6t1ZZDCG0zkoWC", 
  "show_session_speed": true, 
  "first_login": false, 
  "cert": "ssl/daemon.cert", 
  "session_timeout": 3600, 
  "default_daemon": "63f85a5d8ac57c37efab4", 
  "sidebar_multiple_filters": true
}
```

**Comment by klr1018** [comment]
同问deluge的web端口在哪看，qbittorrent可以ip+web端口访问，不知道deluge怎么实现ip+web端口访问

**Comment by amefs** [comment]
查看端口：
```
cat /install/你的用户名.deluge-web.port
cat /install/你的用户名.deluged.port
```
通过 ip:port 访问：删除 `web.conf` 中的 `"interface": "127.0.0.1",` 这一行并重启 deluge-web

**Comment by xiaoguiwk** [comment]
通过上述方法调整后，ui界面仍然可以访问，但是ip:port方式仍然不能访问。
操作过程：
cat /install/你的用户名.deluge-web.port
vim /home/用户名/.config/deluge/web.conf    删除"interface": "127.0.0.1"

请求解答

**Comment by amefs** [comment]
是否有重启 deluge-web 进程？另外，访问时你将需要使用 http，而非https

**Comment by xiaoguiwk** [comment]
忘了说，重启过了.
您的意思是我应该在浏览器http://ip:port吗，这样不行，还是应该怎样访问？
感谢。

**Comment by amefs** [comment]
那么你查看以下
```bash
 netstat -tnlp | grep "deluge-web"
```

**Comment by xiaoguiwk** [comment]
这样的：
`tcp        0      0 127.0.0.1:15248         0.0.0.0:*               LISTEN      3450/deluge-web`

**Comment by xiaoguiwk** [comment]
应该是这样的，删除之后重启de-web，然后又重新出现了`"interface": "127.0.0.1"`

**Comment by xiaoguiwk** [comment]
在同路径下有一个web.conf~是不是应该先删除掉，然后再修改web.conf，之后重启de-web呢？
因为之前修改时删除掉了web.conf~然后修改`interface": "127.0.0.1`为`interface": "0.0.0.1`导致de-web直接502无法访问了，所以不敢尝试。
感谢

**Comment by xiaoguiwk** [comment]
在同路径下有一个web.conf~
是不是应该先删除掉，然后再修改web.conf，之后重启de-web呢？
因为之前修改时删除掉了web.conf然后修改interface": "127.0.0.1为interface": "0.0.0.1导致de-web直接502无法访问了，所以不敢尝试。
感谢

**Comment by amefs** [comment]
是的,要先 `systemctl stop deluge-web@用户名` 关闭进程后修改,然后再启动

**Comment by xiaoguiwk** [comment]
已成功连接，感谢帮助
