### ISSUE TITLE
拒绝了链接请求

### ISSUE THREAD

**Issue by hapshon** [amefs/quickbox-lite#82]
在hetzner上安装之后，通过ip访问dashboard 显示该ip拒绝了我们的连接请求。请问这是啥原因

**Comment by amefs** [comment]
请截图，或者附上浏览器报错，例如 `NET::ERR_CERT_AUTHORITY_INVALID`代表自签名证书不受信任。

**Comment by hapshon** [comment]
无法访问此网站5.9.136.108 拒绝了我们的连接请求。
请试试以下办法：

检查网络连接
检查代理服务器和防火墙
ERR_CONNECTION_REFUSED

**Comment by amefs** [comment]
在 SSH 中运行
```bash
netstat -tnlp | grep "80\|443"
```

**Comment by amefs** [comment]
无后续信息更新，暂且关闭该 Issue
