### ISSUE TITLE
安装完成flexget后建议增加安装transmission-rpc步骤

### ISSUE THREAD

**Issue by iigxdehuli** [amefs/quickbox-lite#85]
flexget已经使用transmission-rpc功能替代原from-transmission功能
因此需要安装transmission-rpc
当前面板安装flexget时不会自动安装transmission-rpc插件
需要用户手动进入以下位置手动执行pip install transmission-rpc
/home/${username}/.local/flexget3/bin/
希望作者能完善一下，谢谢

**Comment by amefs** [comment]
已定位到问题，下一个版本将会提供修复

**Comment by iigxdehuli** [comment]
谢谢大佬。
ps:安装transmission-rpc后在运行会报错‘BUG: Unhandled error in plugin transmission: name 'transmissionError' is not defined’，如果还有人遇到此问题，请尝试将python版本更新至3.8.7后再次尝试，本人更新后未复现此问题。

**Comment by amefs** [comment]
我似乎没有在 Python 3.7.7 遇到过你说的这个问题。

**Comment by amefs** [comment]
已在[新版本](https://github.com/amefs/quickbox-lite/blob/c40d33ca19714687a4bcce3ff13ea58da29e8ae3/packages/package/install/installpackage-transmission#L458)修复
