### ISSUE TITLE
请问是否考虑将deluge2.0版本作为默认版本

### ISSUE THREAD

**Issue by xiaoguiwk** [amefs/quickbox-lite#87]
**请描述您请求的功能**
通过观察peers列表发现其实很少有deluge1.3.5版本了，十个里面有一个。

**描述您想要的解决方案**
2.0版本获得了更多站点的支持，例如opencd，且具有更多功能（比如跳过校验）

**描述您考虑过的替代方案**
在安装过程或APP list中同时提供两种版本的选项来提示用户进行安装。

**附加内容**
最后问一个问题：我目前安装的是1.3.5的版本，请问是否可以通过box update deluge命令来升级到2.0版本？还是说必须卸载后重新安装？如果需要卸载后重装，那之前加载的种子和下载的问题是否可以转移或者保留呢？
感谢！

**Comment by amefs** [comment]
默认版本升级我会再做进一步的考察，你也可以在命令行直接通过指定版本号直接安装 deluge 2.0.3。 升级命令可以用于将 1.3.15 升级为 2.0。在没有指定其他 libtorrent 版本时，可以保留之前的种子。你可以考虑备份 `/home/$username/.config/deluge` 文件夹中的内容以防止意外的问题。

**Comment by xiaoguiwk** [comment]
emmmm,使用box update deluge 翻车了，现在无法启动.不知道还有没有救？：|

**Comment by amefs** [comment]
请尝试运行 `pip3 install --upgrade twisted[tls]` (root权限下)

**Comment by xiaoguiwk** [comment]
> 请尝试运行 `pip3 install --upgrade twisted[tls]` (root权限下)

twisted[tls]版本是最新的

`> pip3 install --upgrade twisted[tls]
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Requirement already up-to-date: twisted[tls] in /usr/local/lib/python2.7/dist-packages (20.3.0)
Requirement already satisfied, skipping upgrade: incremental>=16.10.1 in /usr/local/lib/python2.7/dist-packages (from twisted[tls]) (21.3.0)
Requirement already satisfied, skipping upgrade: attrs>=19.2.0 in /usr/local/lib/python2.7/dist-packages (from twisted[tls]) (20.3.0)
Requirement already satisfied, skipping upgrade: hyperlink>=17.1.1 in /usr/local/lib/python2.7/dist-packages (from twisted[tls]) (21.0.0)
Requirement already satisfied, skipping upgrade: PyHamcrest!=1.10.0,>=1.9.0 in /usr/local/lib/python2.7/dist-packages (from twisted[tls]) (1.10.1)
Requirement already satisfied, skipping upgrade: constantly>=15.1 in /usr/local/lib/python2.7/dist-packages (from twisted[tls]) (15.1.0)
Requirement already satisfied, skipping upgrade: Automat>=0.3.0 in /usr/local/lib/python2.7/dist-packages (from twisted[tls]) (20.2.0)
Requirement already satisfied, skipping upgrade: zope.interface>=4.4.2 in /usr/local/lib/python2.7/dist-packages (from twisted[tls]) (5.3.0)
Requirement already satisfied, skipping upgrade: service-identity>=18.1.0; extra == "tls" in /usr/local/lib/python2.7/dist-packages (from twisted[tls]) (18.1.0)
Requirement already satisfied, skipping upgrade: pyopenssl>=16.0.0; extra == "tls" in /usr/local/lib/python2.7/dist-packages (from twisted[tls]) (20.0.1)
Requirement already satisfied, skipping upgrade: idna!=2.3,>=0.6; extra == "tls" in /usr/lib/python2.7/dist-packages (from twisted[tls]) (2.0)
Requirement already satisfied, skipping upgrade: typing; python_version < "3.5" in /usr/local/lib/python2.7/dist-packages (from hyperlink>=17.1.1->twisted[tls]) (3.7.4.3)
Requirement already satisfied, skipping upgrade: six in /usr/lib/python2.7/dist-packages (from PyHamcrest!=1.10.0,>=1.9.0->twisted[tls]) (1.10.0)
Requirement already satisfied, skipping upgrade: setuptools in /usr/lib/python2.7/dist-packages (from zope.interface>=4.4.2->twisted[tls]) (20.7.0)
Requirement already satisfied, skipping upgrade: pyasn1 in /usr/lib/python2.7/dist-packages (from service-identity>=18.1.0; extra == "tls"->twisted[tls]) (0.1.9)
Requirement already satisfied, skipping upgrade: cryptography in /usr/lib/python2.7/dist-packages (from service-identity>=18.1.0; extra == "tls"->twisted[tls]) (1.2.3)
Requirement already satisfied, skipping upgrade: ipaddress; python_version < "3.3" in /usr/lib/python2.7/dist-packages (from service-identity>=18.1.0; extra == "tls"->twisted[tls]) (1.0.16)
Requirement already satisfied, skipping upgrade: pyasn1-modules in /usr/lib/python2.7/dist-packages (from service-identity>=18.1.0; extra == "tls"->twisted[tls]) (0.0.7)
`

**Comment by amefs** [comment]
你这个问题还挺奇怪的，pip3 命令本身应该是 python3 的，但是你却运行在 python2 上，我很难确定原因。如果还有问题的话可以到[星菊的群里](https://gist.github.com/Aniverse/cc885b91fb7c5d5139c3ffce7e28b0da)找我问一下。
