### ISSUE TITLE
升级ubuntu至“Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-72-generic x86_64)”，quickbox lite至1.46后，出现类似情况，不显示状态

### ISSUE THREAD

**Issue by tautcony** [amefs/quickbox-lite#88]
升级ubuntu至“Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-72-generic x86_64)”，quickbox lite至1.46后，出现类似情况，不显示状态

### **quickbox-lite当前是什么版本？**
1.4.6
### **quickbox-lite是升级到新版本的还是全新安装的新版本**
从1.4.5升级至1.4.6
### **用的是什么浏览器打开的面板？**
chrome
### **浏览器什么版本？**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36
其他浏览器edge,firefox也试过了，不行
### **有没有修改过ngnix的配置？**
没有
### **后台执行systemctl status quickbox-ws确认一下服务是否正常运行**
```
> systemctl status quickbox-ws
● quickbox-ws.service - QuickBox Status Update WebSocket Interface
Loaded: loaded (/etc/systemd/system/quickbox-ws.service; enabled; vendor preset: enabled)
Active: activating (auto-restart) (Result: exit-code) since Tue 2021-04-20 23:00:55 CST; 17s ago
Process: 87355 ExecStart=/usr/bin/node /srv/dashboard/ws/dist/server.js (code=exited, status=1/FAILURE)
Main PID: 87355 (code=exited, status=1/FAILURE)
```
![Snipaste_2021-04-20_18-51-33.png](https://i.loli.net/2021/04/20/UO1tTiN7Chn6dqe.png)

_Originally posted by @chenfangshuo in https://github.com/amefs/quickbox-lite/issues/45#issuecomment-823350141_

**Comment by tautcony** [comment]
请先在shell中执行`/usr/bin/node /srv/dashboard/ws/dist/server.js`，贴一下当前服务启动的具体报错信息。 @chenfangshuo

**Comment by chenfangshuo** [comment]
> journalctl -u quickbox-ws
-- Logs begin at Mon 2021-03-15 18:33:06 CST, end at Tue 2021-04-20 23:14:19 CST. --
-- Logs begin at Mon 2021-03-15 18:33:06 CST, end at Tue 2021-04-20 23:14:19 CST. --
3月 15 19:23:16 Hz systemd[1]: Started QuickBox Status Update WebSocket Interface.
3月 15 19:23:16 Hz node[21337]: quickbox-ws running...
3月 15 19:33:16 Hz systemd[1]: Stopping QuickBox Status Update WebSocket Interface...
3月 15 19:33:16 Hz systemd[1]: quickbox-ws.service: Succeeded.
3月 15 19:33:16 Hz systemd[1]: Stopped QuickBox Status Update WebSocket Interface.
-- Reboot --
3月 15 19:33:55 Hz systemd[1]: Started QuickBox Status Update WebSocket Interface.
3月 15 19:34:03 Hz node[501]: quickbox-ws running...
3月 15 19:37:13 Hz node[501]: 9Nvg_N1fRDLGD7FBAAAC connect from \60.249.25.19
3月 15 19:37:13 Hz node[501]: a9TWaaxtwYLD0VIVAAAD connect from \60.249.25.19
3月 15 19:38:23 Hz node[501]: Config reloaded at Mon Mar 15 2021 19:38:23 GMT+0800 (China Standard Time)
3月 15 19:38:43 Hz node[501]: a9TWaaxtwYLD0VIVAAAD disconnect
3月 15 19:38:43 Hz node[501]: 9Nvg_N1fRDLGD7FBAAAC disconnect
3月 15 19:38:45 Hz node[501]: ixAKgokMW_zs0ZqcAAAG connect from \60.249.25.19
3月 15 19:38:45 Hz node[501]: RQerfBz4cspLqrhFAAAH connect from \60.249.25.19
3月 15 19:39:05 Hz systemd[1]: Stopping QuickBox Status Update WebSocket Interface...
3月 15 19:39:05 Hz systemd[1]: quickbox-ws.service: Succeeded.
3月 15 19:39:05 Hz systemd[1]: Stopped QuickBox Status Update WebSocket Interface.
3月 15 19:39:05 Hz systemd[1]: Started QuickBox Status Update WebSocket Interface.
3月 15 19:39:05 Hz node[2413]: quickbox-ws running...
3月 15 19:39:08 Hz node[2413]: tMsjKGUlm1KdoLoqAAAC connect from \60.249.25.19
3月 15 19:39:09 Hz node[2413]: TSGjXnKE5SFyswDCAAAD connect from \60.249.25.19
3月 15 19:41:29 Hz sudo[3264]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/apt-key add -
3月 15 19:41:29 Hz sudo[3264]: pam_unix(sudo:session): session opened for user root by (uid=0)
3月 15 19:41:29 Hz sudo[3264]: pam_unix(sudo:session): session closed for user root
3月 15 19:41:29 Hz sudo[3524]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/add-apt-repository deb [arch=amd64] https://download.docker.com/linux/ubuntu focal sta>3月 15 19:41:29 Hz sudo[3524]: pam_unix(sudo:session): session opened for user root by (uid=0)
3月 15 19:41:37 Hz sudo[3524]: pam_unix(sudo:session): session closed for user root
3月 15 19:41:57 Hz groupadd[5539]: group added to /etc/group: name=docker, GID=998
3月 15 19:41:57 Hz groupadd[5539]: group added to /etc/gshadow: name=docker
3月 15 19:41:57 Hz groupadd[5539]: new group: name=docker, GID=998
3月 15 19:42:05 Hz sudo[5947]:     root : TTY=unknown ; PWD=/tmp ; USER=forsure ; COMMAND=/usr/bin/bash -c /usr/local/bin/filebrowser -d /home/forsure/.config/filebrowser-ee/datab>3月 15 19:42:05 Hz sudo[5947]: pam_unix(sudo:session): session opened for user forsure by (uid=0)
3月 15 19:42:05 Hz sudo[5947]: pam_unix(sudo:session): session closed for user forsure
3月 15 19:42:05 Hz sudo[5967]:     root : TTY=unknown ; PWD=/tmp ; USER=forsure ; COMMAND=/usr/bin/bash -c /usr/local/bin/filebrowser -d /home/forsure/.config/filebrowser-ee/datab>3月 15 19:42:05 Hz sudo[5967]: pam_unix(sudo:session): session opened for user forsure by (uid=0)
3月 15 19:42:05 Hz sudo[5967]: pam_unix(sudo:session): session closed for user forsure
3月 15 19:42:06 Hz sudo[5985]:     root : TTY=unknown ; PWD=/tmp ; USER=forsure ; COMMAND=/usr/bin/bash -c /usr/local/bin/filebrowser -d /home/forsure/.config/filebrowser-ee/datab>3月 15 19:42:06 Hz sudo[5985]: pam_unix(sudo:session): session opened for user forsure by (uid=0)
3月 15 19:42:06 Hz sudo[5985]: pam_unix(sudo:session): session closed for user forsure
3月 15 19:42:26 Hz node[2413]: tMsjKGUlm1KdoLoqAAAC disconnect
3月 15 19:42:26 Hz node[2413]: TSGjXnKE5SFyswDCAAAD disconnect
3月 15 19:42:41 Hz node[2413]: cgneyEGDjR2NUqzzAAAF connect from \60.249.25.19
3月 15 19:42:42 Hz node[2413]: 5IdMs2g9PrvJoHtcAAAH connect from \60.249.25.19
3月 15 19:46:03 Hz sudo[24335]:     root : TTY=unknown ; PWD=/home/forsure/.local/flexget3 ; USER=forsure ; COMMAND=/usr/bin/bash -c wget -q -O get-pip.py https://bootstrap.pypa.i>3月 15 19:46:03 Hz sudo[24335]: pam_unix(sudo:session): session opened for user forsure by (uid=0)
3月 15 19:46:03 Hz sudo[24335]: pam_unix(sudo:session): session closed for user forsure
3月 15 19:46:03 Hz sudo[24349]:     root : TTY=unknown ; PWD=/home/forsure/.local/flexget3 ; USER=forsure ; COMMAND=/usr/bin/bash -c /home/forsure/.local/flexget3/bin/python get-p>3月 15 19:46:03 Hz sudo[24349]: pam_unix(sudo:session): session opened for user forsure by (uid=0)
3月 15 19:46:06 Hz sudo[24349]: pam_unix(sudo:session): session closed for user forsure
3月 15 19:46:06 Hz sudo[24413]:     root : TTY=unknown ; PWD=/home/forsure/.local/flexget3 ; USER=forsure ; COMMAND=/usr/bin/bash -c /home/forsure/.local/flexget3/bin/pip install >...skipping...
4月 20 23:14:19 forsure.top node[88239]:     ^
4月 20 23:14:19 forsure.top node[88239]: TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received function WebSocketServer
4月 20 23:14:19 forsure.top node[88239]:     at validateString (internal/validators.js:124:11)
4月 20 23:14:19 forsure.top node[88239]:     at Module.require (internal/modules/cjs/loader.js:945:3)
4月 20 23:14:19 forsure.top node[88239]:     at require (internal/modules/cjs/helpers.js:88:18)
4月 20 23:14:19 forsure.top node[88239]:     at Server.init (/srv/dashboard/ws/node_modules/engine.io/lib/server.js:80:53)
4月 20 23:14:19 forsure.top node[88239]:     at new Server (/srv/dashboard/ws/node_modules/engine.io/lib/server.js:65:10)
4月 20 23:14:19 forsure.top node[88239]:     at Function.attach (/srv/dashboard/ws/node_modules/engine.io/lib/engine.io.js:124:18)
4月 20 23:14:19 forsure.top node[88239]:     at Server.initEngine (/srv/dashboard/ws/node_modules/socket.io/dist/index.js:168:27)
4月 20 23:14:19 forsure.top node[88239]:     at Server.attach (/srv/dashboard/ws/node_modules/socket.io/dist/index.js:155:14)
4月 20 23:14:19 forsure.top node[88239]:     at new Server (/srv/dashboard/ws/node_modules/socket.io/dist/index.js:67:18)
4月 20 23:14:19 forsure.top node[88239]:     at /srv/dashboard/ws/dist/server.js:1:5668 {
4月 20 23:14:19 forsure.top node[88239]:   code: 'ERR_INVALID_ARG_TYPE'
4月 20 23:14:19 forsure.top node[88239]: }
4月 20 23:14:19 forsure.top systemd[1]: quickbox-ws.service: Main process exited, code=exited, status=1/FAILURE
4月 20 23:14:19 forsure.top systemd[1]: quickbox-ws.service: Failed with result 'exit-code'.
4月 20 23:15:01 forsure.top systemd[1]: quickbox-ws.service: Scheduled restart job, restart counter is at 2717.
4月 20 23:15:01 forsure.top systemd[1]: Stopped QuickBox Status Update WebSocket Interface.
4月 20 23:15:01 forsure.top systemd[1]: Started QuickBox Status Update WebSocket Interface.
4月 20 23:15:03 forsure.top node[88495]: internal/validators.js:124
4月 20 23:15:03 forsure.top node[88495]:     throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
4月 20 23:15:03 forsure.top node[88495]:     ^
4月 20 23:15:03 forsure.top node[88495]: TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received function WebSocketServer
4月 20 23:15:03 forsure.top node[88495]:     at validateString (internal/validators.js:124:11)
4月 20 23:15:03 forsure.top node[88495]:     at Module.require (internal/modules/cjs/loader.js:945:3)
4月 20 23:15:03 forsure.top node[88495]:     at require (internal/modules/cjs/helpers.js:88:18)
4月 20 23:15:03 forsure.top node[88495]:     at Server.init (/srv/dashboard/ws/node_modules/engine.io/lib/server.js:80:53)
4月 20 23:15:03 forsure.top node[88495]:     at new Server (/srv/dashboard/ws/node_modules/engine.io/lib/server.js:65:10)
4月 20 23:15:03 forsure.top node[88495]:     at Function.attach (/srv/dashboard/ws/node_modules/engine.io/lib/engine.io.js:124:18)
4月 20 23:15:03 forsure.top node[88495]:     at Server.initEngine (/srv/dashboard/ws/node_modules/socket.io/dist/index.js:168:27)
4月 20 23:15:03 forsure.top node[88495]:     at Server.attach (/srv/dashboard/ws/node_modules/socket.io/dist/index.js:155:14)
4月 20 23:15:03 forsure.top node[88495]:     at new Server (/srv/dashboard/ws/node_modules/socket.io/dist/index.js:67:18)
4月 20 23:15:03 forsure.top node[88495]:     at /srv/dashboard/ws/dist/server.js:1:5668 {
4月 20 23:15:03 forsure.top node[88495]:   code: 'ERR_INVALID_ARG_TYPE'
4月 20 23:15:03 forsure.top node[88495]: }
4月 20 23:15:03 forsure.top systemd[1]: quickbox-ws.service: Main process exited, code=exited, status=1/FAILURE
4月 20 23:15:03 forsure.top systemd[1]: quickbox-ws.service: Failed with result 'exit-code'.
4月 20 23:15:45 forsure.top systemd[1]: quickbox-ws.service: Scheduled restart job, restart counter is at 2718.
4月 20 23:15:45 forsure.top systemd[1]: Stopped QuickBox Status Update WebSocket Interface.
4月 20 23:15:45 forsure.top systemd[1]: Started QuickBox Status Update WebSocket Interface.
4月 20 23:15:46 forsure.top node[88517]: internal/validators.js:124
4月 20 23:15:46 forsure.top node[88517]:     throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
4月 20 23:15:46 forsure.top node[88517]:     ^
4月 20 23:15:46 forsure.top node[88517]: TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received function WebSocketServer
4月 20 23:15:46 forsure.top node[88517]:     at validateString (internal/validators.js:124:11)
4月 20 23:15:46 forsure.top node[88517]:     at Module.require (internal/modules/cjs/loader.js:945:3)
4月 20 23:15:46 forsure.top node[88517]:     at require (internal/modules/cjs/helpers.js:88:18)
4月 20 23:15:46 forsure.top node[88517]:     at Server.init (/srv/dashboard/ws/node_modules/engine.io/lib/server.js:80:53)
4月 20 23:15:46 forsure.top node[88517]:     at new Server (/srv/dashboard/ws/node_modules/engine.io/lib/server.js:65:10)
4月 20 23:15:46 forsure.top node[88517]:     at Function.attach (/srv/dashboard/ws/node_modules/engine.io/lib/engine.io.js:124:18)
4月 20 23:15:46 forsure.top node[88517]:     at Server.initEngine (/srv/dashboard/ws/node_modules/socket.io/dist/index.js:168:27)
4月 20 23:15:46 forsure.top node[88517]:     at Server.attach (/srv/dashboard/ws/node_modules/socket.io/dist/index.js:155:14)
...skipping...
4月 20 23:14:19 forsure.top node[88239]:     ^
4月 20 23:14:19 forsure.top node[88239]: TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received function WebSocketServer
4月 20 23:14:19 forsure.top node[88239]:     at validateString (internal/validators.js:124:11)
4月 20 23:14:19 forsure.top node[88239]:     at Module.require (internal/modules/cjs/loader.js:945:3)
4月 20 23:14:19 forsure.top node[88239]:     at require (internal/modules/cjs/helpers.js:88:18)
4月 20 23:14:19 forsure.top node[88239]:     at Server.init (/srv/dashboard/ws/node_modules/engine.io/lib/server.js:80:53)
4月 20 23:14:19 forsure.top node[88239]:     at new Server (/srv/dashboard/ws/node_modules/engine.io/lib/server.js:65:10)
4月 20 23:14:19 forsure.top node[88239]:     at Function.attach (/srv/dashboard/ws/node_modules/engine.io/lib/engine.io.js:124:18)
4月 20 23:14:19 forsure.top node[88239]:     at Server.initEngine (/srv/dashboard/ws/node_modules/socket.io/dist/index.js:168:27)
4月 20 23:14:19 forsure.top node[88239]:     at Server.attach (/srv/dashboard/ws/node_modules/socket.io/dist/index.js:155:14)
4月 20 23:14:19 forsure.top node[88239]:     at new Server (/srv/dashboard/ws/node_modules/socket.io/dist/index.js:67:18)
4月 20 23:14:19 forsure.top node[88239]:     at /srv/dashboard/ws/dist/server.js:1:5668 {
4月 20 23:14:19 forsure.top node[88239]:   code: 'ERR_INVALID_ARG_TYPE'
4月 20 23:14:19 forsure.top node[88239]: }
4月 20 23:14:19 forsure.top systemd[1]: quickbox-ws.service: Main process exited, code=exited, status=1/FAILURE
4月 20 23:14:19 forsure.top systemd[1]: quickbox-ws.service: Failed with result 'exit-code'.
4月 20 23:15:01 forsure.top systemd[1]: quickbox-ws.service: Scheduled restart job, restart counter is at 2717.
4月 20 23:15:01 forsure.top systemd[1]: Stopped QuickBox Status Update WebSocket Interface.
4月 20 23:15:01 forsure.top systemd[1]: Started QuickBox Status Update WebSocket Interface.
4月 20 23:15:03 forsure.top node[88495]: internal/validators.js:124
4月 20 23:15:03 forsure.top node[88495]:     throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
4月 20 23:15:03 forsure.top node[88495]:     ^
4月 20 23:15:03 forsure.top node[88495]: TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received function WebSocketServer
4月 20 23:15:03 forsure.top node[88495]:     at validateString (internal/validators.js:124:11)
4月 20 23:15:03 forsure.top node[88495]:     at Module.require (internal/modules/cjs/loader.js:945:3)
4月 20 23:15:03 forsure.top node[88495]:     at require (internal/modules/cjs/helpers.js:88:18)
4月 20 23:15:03 forsure.top node[88495]:     at Server.init (/srv/dashboard/ws/node_modules/engine.io/lib/server.js:80:53)
4月 20 23:15:03 forsure.top node[88495]:     at new Server (/srv/dashboard/ws/node_modules/engine.io/lib/server.js:65:10)
4月 20 23:15:03 forsure.top node[88495]:     at Function.attach (/srv/dashboard/ws/node_modules/engine.io/lib/engine.io.js:124:18)
4月 20 23:15:03 forsure.top node[88495]:     at Server.initEngine (/srv/dashboard/ws/node_modules/socket.io/dist/index.js:168:27)
4月 20 23:15:03 forsure.top node[88495]:     at Server.attach (/srv/dashboard/ws/node_modules/socket.io/dist/index.js:155:14)
4月 20 23:15:03 forsure.top node[88495]:     at new Server (/srv/dashboard/ws/node_modules/socket.io/dist/index.js:67:18)
4月 20 23:15:03 forsure.top node[88495]:     at /srv/dashboard/ws/dist/server.js:1:5668 {
4月 20 23:15:03 forsure.top node[88495]:   code: 'ERR_INVALID_ARG_TYPE'
4月 20 23:15:03 forsure.top node[88495]: }
4月 20 23:15:03 forsure.top systemd[1]: quickbox-ws.service: Main process exited, code=exited, status=1/FAILURE
4月 20 23:15:03 forsure.top systemd[1]: quickbox-ws.service: Failed with result 'exit-code'.
4月 20 23:15:45 forsure.top systemd[1]: quickbox-ws.service: Scheduled restart job, restart counter is at 2718.
4月 20 23:15:45 forsure.top systemd[1]: Stopped QuickBox Status Update WebSocket Interface.
4月 20 23:15:45 forsure.top systemd[1]: Started QuickBox Status Update WebSocket Interface.
4月 20 23:15:46 forsure.top node[88517]: internal/validators.js:124
4月 20 23:15:46 forsure.top node[88517]:     throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
4月 20 23:15:46 forsure.top node[88517]:     ^
4月 20 23:15:46 forsure.top node[88517]: TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received function WebSocketServer
4月 20 23:15:46 forsure.top node[88517]:     at validateString (internal/validators.js:124:11)
4月 20 23:15:46 forsure.top node[88517]:     at Module.require (internal/modules/cjs/loader.js:945:3)
4月 20 23:15:46 forsure.top node[88517]:     at require (internal/modules/cjs/helpers.js:88:18)
4月 20 23:15:46 forsure.top node[88517]:     at Server.init (/srv/dashboard/ws/node_modules/engine.io/lib/server.js:80:53)
4月 20 23:15:46 forsure.top node[88517]:     at new Server (/srv/dashboard/ws/node_modules/engine.io/lib/server.js:65:10)
4月 20 23:15:46 forsure.top node[88517]:     at Function.attach (/srv/dashboard/ws/node_modules/engine.io/lib/engine.io.js:124:18)
4月 20 23:15:46 forsure.top node[88517]:     at Server.initEngine (/srv/dashboard/ws/node_modules/socket.io/dist/index.js:168:27)
4月 20 23:15:46 forsure.top node[88517]:     at Server.attach (/srv/dashboard/ws/node_modules/socket.io/dist/index.js:155:14)
4月 20 23:15:46 forsure.top node[88517]:     at new Server (/srv/dashboard/ws/node_modules/socket.io/dist/index.js:67:18)
4月 20 23:15:46 forsure.top node[88517]:     at /srv/dashboard/ws/dist/server.js:1:5668 {
4月 20 23:15:46 forsure.top node[88517]:   code: 'ERR_INVALID_ARG_TYPE'
4月 20 23:15:46 forsure.top node[88517]: }
4月 20 23:15:46 forsure.top systemd[1]: quickbox-ws.service: Main process exited, code=exited, status=1/FAILURE
4月 20 23:15:46 forsure.top systemd[1]: quickbox-ws.service: Failed with result 'exit-code'.
4月 20 23:16:28 forsure.top systemd[1]: quickbox-ws.service: Scheduled restart job, restart counter is at 2719.
4月 20 23:16:28 forsure.top systemd[1]: Stopped QuickBox Status Update WebSocket Interface.
4月 20 23:16:28 forsure.top systemd[1]: Started QuickBox Status Update WebSocket Interface.
4月 20 23:16:28 forsure.top node[88548]: internal/validators.js:124
4月 20 23:16:28 forsure.top node[88548]:     throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
4月 20 23:16:28 forsure.top node[88548]:     ^
4月 20 23:16:28 forsure.top node[88548]: TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received function WebSocketServer
4月 20 23:16:28 forsure.top node[88548]:     at validateString (internal/validators.js:124:11)
4月 20 23:16:28 forsure.top node[88548]:     at Module.require (internal/modules/cjs/loader.js:945:3)
4月 20 23:16:28 forsure.top node[88548]:     at require (internal/modules/cjs/helpers.js:88:18)
4月 20 23:16:28 forsure.top node[88548]:     at Server.init (/srv/dashboard/ws/node_modules/engine.io/lib/server.js:80:53)
4月 20 23:16:28 forsure.top node[88548]:     at new Server (/srv/dashboard/ws/node_modules/engine.io/lib/server.js:65:10)
4月 20 23:16:28 forsure.top node[88548]:     at Function.attach (/srv/dashboard/ws/node_modules/engine.io/lib/engine.io.js:124:18)
4月 20 23:16:28 forsure.top node[88548]:     at Server.initEngine (/srv/dashboard/ws/node_modules/socket.io/dist/index.js:168:27)
4月 20 23:16:28 forsure.top node[88548]:     at Server.attach (/srv/dashboard/ws/node_modules/socket.io/dist/index.js:155:14)
4月 20 23:16:28 forsure.top node[88548]:     at new Server (/srv/dashboard/ws/node_modules/socket.io/dist/index.js:67:18)
4月 20 23:16:28 forsure.top node[88548]:     at /srv/dashboard/ws/dist/server.js:1:5668 {
4月 20 23:16:28 forsure.top node[88548]:   code: 'ERR_INVALID_ARG_TYPE'
4月 20 23:16:28 forsure.top node[88548]: }
4月 20 23:16:28 forsure.top systemd[1]: quickbox-ws.service: Main process exited, code=exited, status=1/FAILURE
4月 20 23:16:28 forsure.top systemd[1]: quickbox-ws.service: Failed with result 'exit-code'.
-------------------------------------------------------------------------------------------------------------------------------------------
> /usr/bin/node /srv/dashboard/ws/dist/server.js
internal/validators.js:124
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received function WebSocketServer
    at validateString (internal/validators.js:124:11)
    at Module.require (internal/modules/cjs/loader.js:945:3)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Server.init (/srv/dashboard/ws/node_modules/engine.io/lib/server.js:80:53)
    at new Server (/srv/dashboard/ws/node_modules/engine.io/lib/server.js:65:10)
    at Function.attach (/srv/dashboard/ws/node_modules/engine.io/lib/engine.io.js:124:18)
    at Server.initEngine (/srv/dashboard/ws/node_modules/socket.io/dist/index.js:168:27)
    at Server.attach (/srv/dashboard/ws/node_modules/socket.io/dist/index.js:155:14)
    at new Server (/srv/dashboard/ws/node_modules/socket.io/dist/index.js:67:18)
    at /srv/dashboard/ws/dist/server.js:1:5668 {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by chenfangshuo** [comment]
> npm install --production
up to date, audited 78 packages in 3s                                                                                                                

1 high severity vulnerability

To address all issues, run:                                                                                                                          
  npm audit fix                                                                                                                                      

Run `npm audit` for details. 

> npm audit
npm ERR! code ENOLOCK
npm ERR! audit This command requires an existing lockfile.
npm ERR! audit Try creating one first with: npm i --package-lock-only
npm ERR! audit Original error: loadVirtual requires existing shrinkwrap file
                                                                                                                                                     
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/forsure/.npm/_logs/2021-04-20T15_40_36_863Z-debug.log

> npm audit fix
npm ERR! code ENOLOCK
npm ERR! audit This command requires an existing lockfile.
npm ERR! audit Try creating one first with: npm i --package-lock-only
npm ERR! audit Original error: loadVirtual requires existing shrinkwrap file
                                                                                                                                                     
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/forsure/.npm/_logs/2021-04-20T15_41_32_611Z-debug.log

> npm i --package-lock-only
up to date, audited 1 package in 319ms                                                                                                               
found 0 vulnerabilities

> npm audit fix                                                                                                          
up to date, audited 1 package in 185ms                                                                                                               
found 0 vulnerabilities

> npm install --production
up to date, audited 1 package in 12s                                                                                                                 
found 0 vulnerabilities

> nano /home/forsure/.npm/_logs/2021-04-20T15_41_32_611Z-debug.log
0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'audit', 'fix' ]                                                                                    
1 info using npm@7.10.0                                                                                                                              
2 info using node@v14.16.1                                                                                                                           
3 timing npm:load:whichnode Completed in 1ms                                                                                                         
4 timing config:load:defaults Completed in 1ms                                                                                                       
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 2ms                                                                           
6 timing config:load:builtin Completed in 2ms                                                                                                        
7 timing config:load:cli Completed in 2ms                                                                                                            
8 timing config:load:env Completed in 0ms                                                                                                            
9 timing config:load:project Completed in 0ms                                                                                                        
10 timing config:load:file:/home/forsure/.npmrc Completed in 1ms                                                                                     
11 timing config:load:user Completed in 1ms                                                                                                          
12 timing config:load:file:/usr/etc/npmrc Completed in 0ms                                                                                           
13 timing config:load:global Completed in 0ms                                                                                                        
14 timing config:load:validate Completed in 0ms                                                                                                      
15 timing config:load:setEnvs Completed in 1ms                                                                                                       
16 timing config:load Completed in 7ms                                                                                                               
17 timing npm:load:configload Completed in 7ms                                                                                                       
18 timing npm:load:setTitle Completed in 0ms                                                                                                         
19 timing npm:load:setupLog Completed in 1ms                                                                                                         
20 timing npm:load:cleanupLog Completed in 2ms                                                                                                       
21 timing npm:load:configScope Completed in 0ms                                                                                                      
22 timing npm:load:projectScope Completed in 0ms                                                                                                     
23 timing npm:load Completed in 12ms                                                                                                                 
24 timing config:load:flatten Completed in 2ms                                                                                                       
25 timing arborist:ctor Completed in 0ms                                                                                                             
26 timing command:audit Completed in 4ms                                                                                                             
27 verbose stack Error: loadVirtual requires existing shrinkwrap file                                                                                
27 verbose stack     at Arborist.loadVirtual (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-virtual.js:57:18)            
27 verbose stack     at async Arborist.audit (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/audit.js:23:18)                   
27 verbose stack     at async Audit.audit (/usr/lib/node_modules/npm/lib/audit.js:63:5)                                                              
28 verbose cwd /home/forsure                                                                                                                         
29 verbose Linux 5.4.0-72-generic                                                                                                                    
30 verbose argv "/usr/bin/node" "/usr/bin/npm" "audit" "fix"                                                                                         
31 verbose node v14.16.1                                                                                                                             
32 verbose npm  v7.10.0                                                                                                                              
33 error code ENOLOCK                                                                                                                                
34 error audit This command requires an existing lockfile.

**Comment by tautcony** [comment]
贴一下 /srv/dashboard/ws/package.json

**Comment by chenfangshuo** [comment]
直接运行显示Permission denied 
/srv/dashboard/ws/package.json
{
  "name": "quickbox-ws",
  "version": "1.0.0",
  "description": "QuickBox Status Update WebSocket Interface",
  "main": "server.js",
  "scripts": {
    "build": "webpack --config build/webpack.config.js",
    "test": "mocha -r ts-node/register 'tests/**/*.ts'",
    "lint": "eslint . --ext .ts",
    "test/server": "ts-node src/server.ts",
    "test/client": "ts-node tests/client.js",
    "audit": "npm audit --registry=https://registry.npmjs.org",
    "upgrade": "npm-check -u"
  },
  "author": "TautCony",
  "license": "GPL-3.0-or-later",
  "dependencies": {
    "axios": "^0.21.1",
    "express": "^4.17.1",
    "socket.io": "^4.0.1",
    "ws": "^7.4.4"
  },
  "devDependencies": {
    "@types/chai": "^4.2.16",
    "@types/express": "^4.17.11",
    "@types/mocha": "^8.2.2",
    "@types/node": "^14.14.37",
    "@types/ws": "^7.4.1",
    "@typescript-eslint/eslint-plugin": "^4.21.0",
    "@typescript-eslint/parser": "^4.21.0",
    "chai": "^4.3.4",
    "eslint": "^7.24.0",
    "eslint-loader": "^4.0.2",
    "mocha": "^8.3.2",
    "npm-check": "^5.9.2",
    "socket.io-client": "^4.0.1",
    "source-map-loader": "^2.0.1",
    "terser-webpack-plugin": "^5.1.1",
    "ts-loader": "^8.1.0",
    "ts-node": "^9.1.1",
    "typescript": "^4.2.4",
    "webpack": "^5.31.2",
    "webpack-cli": "^4.6.0",
    "webpack-merge": "^5.7.3",
    "webpack-node-externals": "^2.5.2",
    "webpackbar": "^5.0.0-3"
  },
  "optionalDependencies": {
    "bufferutil": "^4.0.3",
    "utf-8-validate": "^5.0.4"
  }
}

**Comment by tautcony** [comment]
挺奇怪的，依赖重新装一下吧

cd /srv/dashboard/ws
rm -rf node_modules
npm install --production

然后再提供一下node的版本

node --version

**Comment by chenfangshuo** [comment]
！现在好了

**Comment by chenfangshuo** [comment]
node版本 v14.16.1
