### ISSUE TITLE
WARNING: `pyenv init -` no longer sets PATH

### ISSUE THREAD

**Issue by kkw6387** [amefs/quickbox-lite#91]
**描述 Bug**
最近更新了服务器，重新安装完Ubuntu 18.04或者Ubuntu 20.04后，再安装quickbox-lite中的flexget或者autoremove torrents时都会出现如下错误：
WARNING: `pyenv init -` no longer sets PATH.
Run `pyenv init` to see the necessary changes to make to your configuration.

貌似是pyenv更新导致的？

**Comment by amefs** [comment]
查过 commit 记录，是有修改，后续会给出补丁。

**Comment by amefs** [comment]
对于已经出现这个情况可以这样修复.
```bash
cat > /root/.bash_pyenv <<EOF
# pyenv
export PYENV_ROOT="/opt/pyenv"
export PATH="/opt/pyenv/bin:\$PATH"
eval "\$(pyenv init --path)"
EOF
```

**Comment by amefs** [comment]
见 e8c3cc36dd8baadd6dff609485b31515c79c8686
