### ISSUE TITLE
Port of Deluge & Problem of ruTorrent

### ISSUE THREAD

**Issue by SingleRottenChips** [amefs/quickbox-lite#92]
What's the port of Deluge?
I tried 58846, but it doesn't work.

Moreover, I have a problem with ruTorrent. Could you please read this post I created?

**Comment by SingleRottenChips** [comment]
Sorry, I just connected to Deluge. But the problem of ruTorrent still. Could you help me with that?

**Comment by amefs** [comment]
Rutorrent uses Unix socket to communicate with rTorrent.

**Comment by SingleRottenChips** [comment]
> Rutorrent uses Unix socket to communicate with rTorrent.

So... you mean the problem of ruTorrent has something todo with the "Unix socket"?

So how can I do with it?

**Comment by amefs** [comment]
Ok, I misunderstood your problem about ruTorrent. I need to do some test later to known if it can reproduce.

**Comment by amefs** [comment]
Can not reproduce in my environment. I used Ubuntu 18.04 in Hetzner Cloud. Test with ruTorrent and RSS plugin. Please check which one crashed. rTorrent/ruTorrent? If you mean Auto-irssi, it's totally different from the RSS plugin I have tasted here.

**Comment by SingleRottenChips** [comment]
> Can not reproduce in my environment. I used Ubuntu 18.04 in Hetzner Cloud. Test with ruTorrent and RSS plugin. Please check which one crashed. rTorrent/ruTorrent? If you mean Auto-irssi, it's totally different from the RSS plugin I have tasted here.

I mean the RSS plugin. It usually takes several days before it crashed...

**Comment by amefs** [comment]
It's really hard to say what happened. It's stable in my server for about 2 years, but run with old version. Can you please upload the screenshot when it crashed?

**Comment by SingleRottenChips** [comment]
> It's really hard to say what happened. It's stable in my server for about 2 years, but run with old version. Can you please upload the screenshot when it crashed?

**Comment by amefs** [comment]
星菊那个我没有测试过兼容性，通常来说不行。你奔溃的是rTorrent，你可以尝试对照官方文档 https://github.com/rakshasa/rtorrent/wiki/Performance-Tuning#sample-config-entries 修改一些 rtorrent.rc 的参数。另外就我个人使用下来的感觉，0.9.8 的稳定性会好一些。你 RSS 更新时间的话建议5分钟+。

**Comment by SingleRottenChips** [comment]
> 星菊那个我没有测试过兼容性，通常来说不行。你奔溃的是rTorrent，你可以尝试对照官方文档 https://github.com/rakshasa/rtorrent/wiki/Performance-Tuning#sample-config-entries 修改一些 rtorrent.rc 的参数。另外就我个人使用下来的感觉，0.9.8 的稳定性会好一些。你 RSS 更新时间的话建议5分钟+。

大佬你好，我从昨天开始用Deluge，RSS更新时间设置5分钟，现在又挂了。种子无下载速度，有上传速度，我试着通过SCP往服务器上上传文件也失败。好像又出现“只能读取，不能写入”的问题了。
![image](https://user-images.githubusercontent.com/63144489/119235576-bf451a00-bb65-11eb-8d26-0aabe0a2823a.png)
![image](https://user-images.githubusercontent.com/63144489/119235605-ef8cb880-bb65-11eb-82c2-8b5a1172bc7d.png)

**Comment by amefs** [comment]
你这个看起来有点不妙，很可能是系统出现 Read-Only，原因一般是磁盘坏块，造成文件系统重新挂载为只读。你可以尝试在这个时候，从 SSH 登录，Root 下查看 `findmnt`。你需要查看 `/` 以及 `/home`(如果有的话)。最后一栏应 OPTIONS 该显示 ` rw,relatime,errors=remount-ro,stripe=256` 如果显示为 ro 那么应该是文件系统损坏了。这种情况一般建议通知 OneProvider 换机。

**Comment by SingleRottenChips** [comment]
> 你这个看起来有点不妙，很可能是系统出现 Read-Only，原因一般是磁盘坏块，造成文件系统重新挂载为只读。你可以尝试在这个时候，从 SSH 登录，Root 下查看 `findmnt`。你需要查看 `/` 以及 `/home`(如果有的话)。最后一栏应 OPTIONS 该显示 ` rw,relatime,errors=remount-ro,stripe=256` 如果显示为 ro 那么应该是文件系统损坏了。这种情况一般建议通知 OneProvider 换机。
![image](https://user-images.githubusercontent.com/63144489/119236956-d9362b00-bb6c-11eb-974a-765950680e57.png)
感谢回复！请问这样就是损坏了的意思吧...

**Comment by amefs** [comment]
是的，这个就是文件系统只读挂起了。虽然不能确定是由坏块引起。如果非要提供坏块报告的话
```bash
badblocks -nsv /dev/device
```
具体参见 [https://wiki.archlinux.org/title/badblocks](https://wiki.archlinux.org/title/badblocks)

**Comment by SingleRottenChips** [comment]
> 是的，这个就是文件系统只读挂起了。虽然不能确定是由坏块引起。如果非要提供坏块报告的话
> 
> ```shell
> badblocks -nsv /dev/device
> ```
> 
> 具体参见 https://wiki.archlinux.org/title/badblocks

它显示这个...
![image](https://user-images.githubusercontent.com/63144489/119237980-6039d200-bb72-11eb-8574-1c7c5078f6fc.png)
我用百度说的这个命令，它显示这个...
![image](https://user-images.githubusercontent.com/63144489/119237997-79428300-bb72-11eb-91a9-4b4c3879f218.png)
然而我已经把tickets上交给OP了...

**Comment by amefs** [comment]
这个你大概需要去 Rescue Mode 处理。因为你的文件系统现在它已经 RO 了。
