### ISSUE TITLE
你好，请问我的设备443和80端口被封禁了，装好 quickbox-lite无法直接通过ip或者域名访问，如何更改webUI的默认端口呢？

### ISSUE THREAD

**Issue by himonster1** [amefs/quickbox-lite#94]
## 你好，请问我的设备443和80端口被封禁了，装好 quickbox-lite无法直接通过ip或者域名访问，如何更改webUI的默认端口呢？

Hello, my device port 443 and 80 are blocked, and the installed quickbox-lite cannot be accessed directly through ip or domain name. How can I change the default port of webUI?

**Comment by amefs** [comment]
修改配置文件：`/etc/nginx/sited-enabled/default` 如下
```
server {
    listen 4443 ssl http2 default_server;
    listen [::]:4443 ssl http2 default_server;
```
修改完成后你可以直接通过https://ip:4443访问。80 端口跳转没有必要也不能在这里实现

**Comment by himonster1** [comment]
非常感谢,另外还有一个问题 我是先在域名运营商那里添加域名解析到我的ip ，然后在安装quickbox-lite的时候 会有一步让我填写域名对吧，我填了域名，它还是提示我 没有此a记录。这个是怎么回事呢

**Comment by amefs** [comment]
`curl -s https://api.ip.sb/ip` 然后运行 `dig <你的域名>` 确认你自己 IP 地址是否对应 A 记录。

**Comment by himonster1** [comment]
好的 明白了 感谢大佬 还有最后一个问题，就是quickbox-lite必须443端口吗？可以改成80端口吗？因为443 Chrome提示不安全链接访问不了。

如果必须用443，该怎么配置证书？我是不是只要Google搜索关键词“ nginx配置ssl证书”就可以解决Chrome访问不了的问题？

**Comment by amefs** [comment]
删除 https://github.com/amefs/quickbox-lite/blob/master/setup/templates/nginx/default.template#L6-L22 这么多内容就可以 80 端口访问。443的话 Let's Encrypt 就可以给你加免费证书，不过需要公网 + 443 端口，其他特殊端口你需要自己解决。

**Comment by himonster1** [comment]
谢谢您能解决小白的问题 非常感谢 感动的要哭了
