### ISSUE TITLE
安装过程中提示这个是什么情况，国内网络

### ISSUE THREAD

**Issue by qxwo** [amefs/quickbox-lite#95]
se8: can't read /srv/fancyindex/header.html: No such file or directory                   │                                                              │                          
        sed: can't read /srv/fancyindex/footer.html: No such file or directory 
安装过程中提示这个是什么情况，国内网络

**Comment by tautcony** [comment]
确实是网络问题，此处文件未能成功下载

https://github.com/amefs/quickbox-lite/blob/master/setup.sh#L800

**Comment by qxwo** [comment]
好的谢谢，已解决
