### ISSUE TITLE
HetZner、OneProvider杜甫Debian10系统下安装后无法连接管理网站。

### ISSUE THREAD

**Issue by LeiD215** [amefs/quickbox-lite#96]
全新操作系统，安装时选择SSL，不开BBR，不改变安装源，不修改SSH端口，不开FTP，只安装了QB。安装完成重启后80和443端口无法访问，有时提示错误100，有时提示102，HZ家Debian10多次重试，无法连接，在Ubuntu20.04下可以正常使用。OP家的Debian9，Debian10，Ubuntu18，Ubuntu20，全部都不行。哦还测试了不开SSL，依然无法连接。请问应该如何做？

**Comment by amefs** [comment]
首先，请在安装系统时选择 minimal install。HTTP 100/102 都属于 informational response，只代表服务器处理响应，而没有具体的结果，无法判定是否成功。

**Comment by LeiD215** [comment]
系统是服务商自带的，我一会晚点重新安装一遍系统和quickbox-lite，再联系您解决。谢谢

**Comment by LeiD215** [comment]
刚刚重装ubuntu18.04和quickbox-lite后，web还是无法访问，大佬方便给看一下吗？

**Comment by LeiD215** [comment]
检查nginx,报错。
nginx: [emerg] BIO_new_file("/etc/nginx/ssl/op1.ddamon.xyz/op1.ddamon.xyz-fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/ssl/op1.ddamon.xyz/op1.ddamon.xyz-fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)

**Comment by LeiD215** [comment]
使用 box install lecert -d <domain> 后：

Let's Encrypt will now be installed.

This process may take a few minutes
Please wait until the process is completed

➜ Building Let's Encrypt...
✓ Let's Encrypt Built.
➜ Configuring Let's Encrypt...
✓ Let's Encrypt configured.
➜ Configuring Let's Encrypt lock...
✓ Let's Encrypt lock configured.
➜ Starting Let's Encrypt...
✓ Let's Encrypt started.

ssl目录下没有证书。

**Comment by amefs** [comment]
如果有问题的话，姑且运行 `box remove lecert`，恢复到自签证书状态，我需要抽空做一下测试。

**Comment by LeiD215** [comment]
好的，等待修复。

**Comment by amefs** [comment]
已经在开发者分支推送了一个补丁，你现在可以切换到 dev 分支执行 `box install lecert -d`。

**Comment by LeiD215** [comment]
签发证书已经正常。
