### ISSUE TITLE
什么时候能支持arm64呢？

### ISSUE THREAD

**Issue by lw6644700** [amefs/quickbox-lite#99]
现在支持吗？或者什么时候能支持arm64呢？

**Comment by amefs** [comment]
有另外做过arm64的适配，但由于没有机器做测试，没有公开。

**Comment by lw6644700** [comment]
> 有另外做过arm64的适配，但由于没有机器做测试，没有公开。

谢谢大佬的回复，大佬可以试试用甲骨文的arm机器做测试

**Comment by amefs** [comment]
目前开不出新的机器，姑且没办法测试。

**Comment by amefs** [comment]
ARM64版，没有更合适的硬件测试条件，不保证稳定。https://github.com/amefs/quickbox-arm64
